JenkinsJobs/Builds/Y-build.groovy
Missed on closing Braces
Change-Id: Icf800d3af8c2ae13914c69f0363f72a77b33558e
=> Bug 577323 - Make Y-Build use GitHub

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testResults.php, production/testScripts/hudsonBootstrap/getEBuilder.xml
Change-Id: I0fe27ebab15bbe8fd1d96f95861a1b409662768e
=> Bug 577323 - Migrate org.eclipse.platform.releng.aggregator to github

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Change-Id: I213d6e5f549c84647ba572b48095f9eaba60c0d5
=> Bug 578004 - Eclipse 4.23 prerequisites: Orbit

cje-production/dockerfiles/build-centos_9.sh, cje-production/dockerfiles/build-centos_9_swt_build.sh, cje-production/dockerfiles/centos-gtk4-metacity/9-gtk4/Dockerfile, cje-production/dockerfiles/centos-gtk4-metacity/9-gtk4/scripts/uid_entrypoint, cje-production/dockerfiles/centos-gtk4-metacity/9-gtk4/scripts/xstartup_metacity.sh, cje-production/dockerfiles/centos-gtk4-metacity/9-gtk4/scripts/xstartup_mutter.sh, cje-production/dockerfiles/centos-gtk4-metacity/9-swtBuild/Dockerfile, cje-production/dockerfiles/centos-gtk4-metacity/9-swtBuild/scripts/uid_entrypoint, cje-production/dockerfiles/centos-gtk4-metacity/9-swtBuild/scripts/xstartup_metacity.sh, cje-production/dockerfiles/centos-gtk4-metacity/9-swtBuild/scripts/xstartup_mutter.sh
For: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/36
Added a gtk4 folder and centos 9 dockerfiles.
=> Add centos 9

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Change-Id: I81f1f3bb66cfb8ee08d18102d8f068770289157c
=> Bug 578003 - Eclipse 4.23 prerequisites: EMF

.mvn/extensions.xml
Change-Id: I60194c964a948bc9125870838fc408013e1fb0a5
=> Bug 579015 - Move to tycho 2.7.0

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list.txt
=> #64 Cleanup approved api list

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.sdk.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.p2.inf, production/testScripts/configuration/streamSpecific.properties, production/testScripts/test_runTests2.xml.sh
Change-Id: I73e8bdce272d1311c04d3333b917ee68ad1ac0b2
=> Update product version number to 4.24 across build script #60

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
To be merged after first successful build
=> 78 update comparator repo

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Update test framework dependencies

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
Change-Id: I6e6828f4ff9592ee37219b1d80472db6624188ef
=> Update to 4.23 RC2a across build scripts #93

eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java18patch/org.eclipse.jdt-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java18patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java18patch/org.eclipse.jdt.java18patch/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java18patch/org.eclipse.pde-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java18patch/org.eclipse.pde-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java18patch/org.eclipse.pde.java18patch/feature.xml
Change-Id: Idcaed59d57a8b3c6b6bb047ca1508a12d85386c5
=> Move java 18 p-build target to 4.23 RC2a #95

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
=> Update 4.23 maintenance branch with release version for 4.23+

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
=> Use 4.23 GA version across build scripts #113

cje-production/dockerfiles/centos-gtk4-mutter/9-gtk4/Dockerfile, cje-production/dockerfiles/centos-gtk4-mutter/9-swtBuild/Dockerfile
* use curl-minimal (provides only http/https/ftp)
* use dnf command
* use new webkit package name webkit2gtk3
* use Java 17 not Java 1.8
* drop useless GConf2 and cmake packages
=> Fix CentOS Stream9 containers

eclipse-platform-parent/pom.xml
Update to ecj 3.30.0 version having java 18 support
=> Update to ecj  #140

.gitmodules
=> Updating gitmodules for eclipse.jdt #142

.gitmodules
=> Migrate eclipse.platform.resources and eclipse.platform.runtime to

cje-production/mbscripts/mb620_promoteUpdateSite.sh, cje-production/promotion/makeVisible.sh, production/testScripts/hudsonBootstrap/getEBuilder.xml
=> No more use of raw.githubusercontent.

JenkinsJobs/SmokeTests/StartSmokeTests.groovy
Fixes Refactor Smoke tests and their jobs #156
=> Refactor Smoke tests and their jobs #156

.gitmodules
=> Move eclipse.platform.debug.git to github #162

.gitmodules
=> Move SWT repos to Github

README.md, production/README.md
and updating top level README.md to point to it.
=> adding README.md for Performance tests

.gitmodules
=> Issue #176 Github link for JDT Debug

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/179
=> Remove hamcrest-integration from target platform

.gitmodules
Fixes #177
Change-Id: If333659b6443f5b653e72f963297bea7e28b3c5d 
Signed-off-by: Vikas Chandra <Vikas.Chandra@in.ibm.com>
=> Migration of eclipse.pde.ui.git to github #177

cje-production/mbscripts/mb110_tagBuildInputs.sh
=> Update generation of git log report to generate from github

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Update to Jetty 10.0.9

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Pre reqs for M1

cje-production/mbscripts/mb110_tagBuildInputs.sh
=> Update generation of git log report to generate from github #184

cje-production/mbscripts/mb110_tagBuildInputs.sh
Fixes #184 
Fixed a typo in gitlog generation
=> Update generation of git log report to generate from github #184 

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Remove hamcrest.library from target.platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Helps to easily identify the Jetty dependencies which are frequently
updated.
=> Explicit block for Jetty in target definition fil

.gitmodules
=> Signed-off-by: Kalyan Prasad Tatavarthi <kalyan_prasad@in.ibm.com>

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml
Ensure all transtive dependencies are part of p2 repo.
=> Include all dependencies

eclipse-platform-parent/pom.xml
=> Downgrade tycho version used in aggregator to 2.7.0 #212

eclipse-platform-parent/pom.xml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#214
=> Revert "Downgrade tycho version used in aggregator to 2.7.0 #212"

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This reverts commit a4c47083c061592e507316f60eec851ada0217b2.
=> Revert "Revert "Add sat4j 2.3.6 to target""

JenkinsJobs/SmokeTests/StartSmokeTests.groovy
=> Add centos 9 test run to smoke tests #221

RELEASE.md
The wiki has a lot of extra info so as I learn releng tasks I'm adding them to md files in GIT so they're easy to find for anyone who might need them in the future.
=> Add RELEASE.md file with my notes on Milestone releases

eclipse.platform.releng.tychoeclipsebuilder/java18patch/org.eclipse.jdt.java18patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java18patch/org.eclipse.pde.java18patch/pom.xml
In PR #232 I forgot to adjust the groupId to the one of tycho-source-plugin.
=> Fix groupId of tycho-source-plugin

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Eclipse 4.24 M2 Prerequisites: Orbit

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Add `org.osgi.service.prefs` which is required for https://github.com/eclipse-equinox/equinox.bundles/pull/39.
=> Add OSGi service.prefs from Maven-Central

oomph/.project, oomph/.settings/org.eclipse.core.resources.prefs, oomph/.settings/org.eclipse.core.runtime.prefs, oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
Also include a .project file for the folder containing the setups so
that they are visible in the provisioned SDK workspace.
=> Fix the reference to the refactored PDE.setup from the SDK configuration

oomph/Platform.setup
eclipse.platform.releng.prereqs.sdk folder is done before resolving the
target platform.
=> Ensure that the .project file created in the

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Eclipse 4.24 M3 Prerequisites: Orbit

cje-production/promotion/makeVisible.sh, cje-production/promotion/promoteSites.sh
=> use github issue for signoff

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Eclipse 4.24 Prerequisites: EMF #171

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Eclipse 4.24 Orbit Release version

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list.txt
=> Cleanup approved api list #294

cje-production/cleaners/cleanupNightlyRepo.sh
=> Update builds and repo cleanup scripts for 4.25 #305

eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/updateTestResultsPages.sh
=> #302 Move previous version to 4.24RC2

eclipse.platform.releng.tychoeclipsebuilder/rcp.config/config.product, eclipse.platform.releng.tychoeclipsebuilder/rcp.config/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/rcp.config/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/313
=> Version bumps for 4.25 stream

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
=> Update to 4.24 RC2a across build scripts

Jenkinsfile
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/293
=> Switch aggregator verification build to use Java 17

JenkinsJobs/Builds/I-build.groovy, JenkinsJobs/Builds/Y-build.groovy
=> Switch aggregator I and Y builds to use Java 17

cje-production/scripts/collectTestResults.xml, cje-production/scripts/genTestIndexes.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/helper.xml, production/testScripts/genTestIndexes.xml
Remove usage of javascript.
Tracked in #293
=> Switch builds to use Java 17 JVM

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
=> Use 4.24 GA version across build scripts

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
=> Update 4.24 maintenance branch with release version for 4.24+

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
https://github.com/eclipse-platform/eclipse.platform/pull/27
=> Fix setup form merging eclipse.platform.runtime into eclipse.platform

cje-production/streams/repositories_master.txt
See eclipse-equinox/equinox.bundles#18
=> Fix I-build cloning to use new merged equinox repo

JenkinsJobs/SmokeTests/StartSmokeTests.groovy, Jenkinsfile
General one (not 6GB) but the centos7 is currently broken.
=> Switch verification build to CentOS 8

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
* MOckito to 4.6.1
* ByteBuddy to 1.12.10
* AssertJ to 3.23.1
=> Update test dependencies

cje-production/cleaners/cleanupNightlyRepo.sh
Fixes 
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/358
=> Update cleanup script to ignore unstable builds

RELEASE.md
There was a lot to add so if someone could review for accuracy/readability I'd very much appreciate it.
There are a lot of links but I found it useful to see what was done last release while I was learning for this one so I thought it would be good to include those references up front.
=> Update RELEASE.md with the GA release process.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/368
=> Jetty update r4.7

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/368
=> Jetty update r4.19

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/368
=> Jetty update r4.8

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/368
=> Jetty update r4.15

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Replace some Orbit deps by upstream ones

eclipse-platform-parent/pom.xml
Update ECJ compiler for 4.25 M1
=> Update ECJ compiler for 4.25 M1

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Requested as a transitive dependency of batik
=> Re-add commons-io to target

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/396
=> Update Jetty version in R4_23_maintenance branch to 10.0.11 #396

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
See #https://github.com/eclipse-platform/eclipse.platform/issues/45
=> Update Ant to 1.10.12 for 4.15 Maintenance branch

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
See #https://github.com/eclipse-platform/eclipse.platform/issues/45
=> Update Ant to 1.10.12 for 4.11 Maintenance branch

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
See #https://github.com/eclipse-platform/eclipse.platform/issues/45
=> Update Ant to 1.10.12 for 4.8 Maintenance branch

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
See #https://github.com/eclipse-platform/eclipse.platform/issues/45
=> Update Ant to 1.10.12 for 4.19 Maintenance branch

.mvn/extensions.xml
Fixes https://github.com/eclipse-equinox/equinox/issues/83
=> Update tycho-build to 2.7.4.

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/basicPerformance.php, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/performance.php
It's not fancy but it should work.
=> Updating php to use new performance tables and adding template php file.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This reverts commit 10fb61202130afe506c81b6005044a2041cb52bf.
=> Revert "Use Orbit bundle for commons-io"

.github/workflows/verifyFreezePeriod.yml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/427
=> Fix Calendar URL request

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/basicPerformance.php, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/performance.php
They're in the same folder so the paths were wrong.
=> Fix paths in performance.php and basicPerformance.php

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
https://github.com/eclipse-platform/eclipse.platform/pull/64
=> Accommodate the merge of team into platform

oomph/Platform.setup
https://github.com/eclipse-platform/.github/issues/10
Also remove the reference to platformText.setup which is no longer relevant.
=> Install m2e features as part of the setup

cje-production/P-build/buildproperties.txt
Changes to shell scripts
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/450
=> P-build infrastructure for Java 19 work

JenkinsJobs/Builds/I-build.groovy, JenkinsJobs/Builds/Y-build.groovy
JDT and Tycho issues should be fixed now.
This reverts commit 7fc3bb0ccde87a94bbcef0078324c212ccc81aac.
=> Revert "Revert "Switch aggregator I and Y builds to use Java 17""

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Update JUnit dependencies to 5.9.0

eclipse.platform.releng.tychoeclipsebuilder/java19patch/org.eclipse.jdt.java19patch/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java19patch/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/450
=> Add JDT Plugins for P Build

oomph/Platform.setup
Also simplify the workings sets for eclipse.platform to take advantage
of the nested folder structure.
https://github.com/eclipse-platform/eclipse.platform/issues/77
=> Accommodate merge of eclipse.platform.resources into eclipse.platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This reverts commit 4362560956327a60ef7db93ba3ff0c160d763ebc.
Fixes #476 which the details.
=> Revert "Update ICU4J to version 71.1"

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/361
=> Eclipse 4.25 Prerequisites: EMF

cje-production/streams/repositories_java19.txt
With latest change, we can use PDE from master stream for Y build
=> With latest change, we can use PDE from master stream for Y build

cje-production/Y-build/buildproperties.txt
Removing usage of specific javadoc version for Y-build
=> Removing usage of specific javadoc version for Y-build

cje-production/Y-build/buildproperties.txt
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/482
=> Switch JAVA_DOC_TOOL to Java 17

cje-production/dockerfiles/centos-gtk3-metacity/8-swtBuild/Dockerfile
Needed by
https://github.com/eclipse-platform/eclipse.platform.swt/issues/321
=> Update Java to 11 in SWT build image

cje-production/buildproperties.txt
required by https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/482
=> Generation of javadoc using java 17

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/361
=> EMF update for RC1

eclipse-platform-parent/pom.xml
Updating Compiler to 3.31.0.v20220824-0714 from RC1
=> Update compiler for 4.25 RC1

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/361
=> Update to EMF 2.31 release.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/360
=> Orbit update

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Also updated P2 repo. Tracked in #532
=> Updating comparator repo and eclipse run repo to 4.26-I-builds.  

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#536 once we have at least one build in 4.26-I-builds repo
=> Revert "Revert "Updating comparator repo and eclipse run repo to 4.26-I-builds.  ""

eclipse.platform.releng.tychoeclipsebuilder/rcp.config/config.product, eclipse.platform.releng.tychoeclipsebuilder/rcp.config/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/rcp.config/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/540
=> Version bumps for 4.26 stream

eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java19patch/org.eclipse.jdt-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java19patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java19patch/org.eclipse.jdt.java19patch/feature.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/550
=> Target java 19 patch to 4.25RC2

JenkinsJobs/Builds/Y-build.groovy
=> re enable windows tests for Y-builds

JenkinsJobs/Builds/AddToPComposite.groovy, JenkinsJobs/Builds/I-build.groovy
=> fix: use workspace variable instead of relative path

JenkinsJobs/Builds/AddToPComposite.groovy, JenkinsJobs/Builds/markStable.groovy, JenkinsJobs/Builds/markUnstable.groovy
#568 Extended email isn't working. Add back in later once everything else works.
=> fix: remove extended email

cje-production/scripts/checkComposites/checkComposites.sh
Removing verification 4.25-I-builds repo as the release is complete
=> Removing verification 4.25-I-builds repo

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Update the target platform.
Fixes  https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/578
=> Update Jetty to 10.0.12

eclipse-platform-parent/pom.xml
=> Moving to daily ecj snapshot

JenkinsJobs/AutomatedTests/FOLDER.groovy, JenkinsJobs/AutomatedTests/collectResults.groovy, JenkinsJobs/AutomatedTests/collectYbuildResults.groovy, JenkinsJobs/AutomatedTests/ep425Y-unit-cen64-gtk3-java11.groovy, JenkinsJobs/AutomatedTests/ep425Y-unit-cen64-gtk3-java17.groovy, JenkinsJobs/AutomatedTests/ep425Y-unit-cen64-gtk3-java19.groovy, JenkinsJobs/AutomatedTests/ep425Y-unit-mac64-java17.groovy, JenkinsJobs/AutomatedTests/ep425Y-unit-macM1-java17.groovy, JenkinsJobs/AutomatedTests/ep425Y-unit-win32-java11.groovy, JenkinsJobs/AutomatedTests/ep426I-unit-cen64-gtk3-java11.groovy, JenkinsJobs/AutomatedTests/ep426I-unit-cen64-gtk3-java17.groovy, JenkinsJobs/AutomatedTests/ep426I-unit-cen64-gtk3-java19.groovy, JenkinsJobs/AutomatedTests/ep426I-unit-mac64-java17.groovy, JenkinsJobs/AutomatedTests/ep426I-unit-macM1-java17.groovy, JenkinsJobs/AutomatedTests/ep426I-unit-win32-java11.groovy, JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/Builds/Y_build.groovy, JenkinsJobs/JobDSL.json
Many are the same and can be combined/parameterized later. 
Also added java 19 tests.
Tracked in #568
=> Initial addition of the automated test builds.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Update JUnit to 5.9.1

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> 4.26 prereqs update EMF

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Orbit updates for 4.26 M1

.mvn/extensions.xml
=> Upgrade build extension to 3.0.0

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/606
=> Use ASM 9.4

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/Builds/P_build.groovy, JenkinsJobs/Builds/Y_build.groovy, JenkinsJobs/Releng/CBIaggregator.groovy, JenkinsJobs/Releng/PublishJDTtoMaven.groovy, JenkinsJobs/Releng/PublishPDEToMaven.groovy, JenkinsJobs/Releng/PublishPlatformToMaven.groovy, JenkinsJobs/Releng/checkCompositesValidity.groovy, JenkinsJobs/Releng/createGenericComposites.groovy, JenkinsJobs/Releng/createMaintenanceBranch.groovy, JenkinsJobs/Releng/makeVisible.groovy, JenkinsJobs/Releng/newStreamRepos.groovy, JenkinsJobs/Releng/renameAndPromote.groovy, JenkinsJobs/Releng/tagEclipseRelease.groovy, JenkinsJobs/Releng/updateIndex.groovy
Also updated daily builds to not use a depreciated trigger method.
Tracked in #568
=> Adding Releng jobs to JenkinsJobs

JenkinsJobs/Cleanup/Clean_ppcle_build.groovy, JenkinsJobs/Cleanup/Clean_ppcle_buildTest.groovy, JenkinsJobs/Cleanup/Clean_ppcle_test.groovy, JenkinsJobs/Cleanup/Clean_win_tests_machine.groovy, JenkinsJobs/Cleanup/FOLDER.groovy, JenkinsJobs/Cleanup/clean_macM1_tests_machine.groovy, JenkinsJobs/Cleanup/cleanupDLsite.groovy, JenkinsJobs/Cleanup/cleanupReleaseArtifacts.groovy, JenkinsJobs/Cleanup/cleanup_mac_build_machine.groovy, JenkinsJobs/Cleanup/cleanup_mac_tests_machine.groovy, JenkinsJobs/Cleanup/cleanup_performance_tests_machine.groovy, JenkinsJobs/Cleanup/cleanup_win_builds_machine.groovy, JenkinsJobs/Cleanup/dailyCleanOldBuilds.groovy
All the jobs that were in the cleanup view (plus a couple others that fit) have been translated into JobDSL groovy files.
Tracked in #568
=> Add cleanup jobs and folder to git

eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/publish.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/publish2.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testConfigs.php
As Java 19 is released, Java 18 is EOL already.
=> Publish Java 19 tests

JenkinsJobs/SmokeTests/StartSmokeTests.groovy
Also removed java 18 test runs
=> Removed Ubuntu 20 and centos 8 test runs

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Release notes:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310100&version=12352370
=> Update Felix SCR to version 2.2.4

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Version 1.27 we have in target platform has the following CVEs: CVE-2022-38752
CVE-2022-38751
CVE-2022-38750
CVE-2022-38749
=> Update snakeyaml to 1.33

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Use latest versions for all of them.
=> Update mockito and friends

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Orbit update for 4.26 M2

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/Releng/collectResults.groovy
Use tests in the AutomatedTests Folder, which shoul…d in turn use Releng/Collect Results then Releng/Update Index.
For #568
=> Update I-build to use new test builds

JenkinsJobs/SmokeTests/FOLDER.groovy, JenkinsJobs/SmokeTests/smoke_test_arm64.groovy, JenkinsJobs/SmokeTests/smoke_test_centos7.groovy, JenkinsJobs/SmokeTests/smoke_test_centos8.groovy, JenkinsJobs/SmokeTests/smoke_test_centos9.groovy, JenkinsJobs/SmokeTests/smoke_test_opensuse_leap.groovy, JenkinsJobs/SmokeTests/smoke_test_ppcle.groovy, JenkinsJobs/SmokeTests/smoke_test_ubuntu18.groovy, JenkinsJobs/SmokeTests/smoke_test_ubuntu20.groovy, JenkinsJobs/SmokeTests/smoke_test_ubuntu22.groovy, JenkinsJobs/SmokeTests/smoke_test_ubuntuLatest.groovy, JenkinsJobs/SmokeTests/smoke_test_win32.groovy
=> Adding SmokeTests and folder

JenkinsJobs/AutomatedTests/ep426I_unit_cen64_gtk3_java20.groovy
Adding a Java 20 unit tests so we can get an idea of what's coming.
=> add Java 20 test

eclipse-platform-parent/pom.xml
@akurtakov, @mickaelistria any objections?
=> Build with Tycho 4.0.0-SNAPSHOT

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes:
* CVE-2022-42890
* CVE-2022-41704
=> Update Batik to 1.16

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/591
=> Update to ECF 3.14.34

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/589
=> Update to Orbit 2022-12 M3

JenkinsJobs/AutomatedTests/ep426I_unit_cen64_gtk3_java20.groovy, JenkinsJobs/Builds/AddToPComposite.groovy, JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/Cleanup/cleanupDLsite.groovy, JenkinsJobs/Cleanup/cleanupReleaseArtifacts.groovy, JenkinsJobs/Cleanup/dailyCleanOldBuilds.groovy, JenkinsJobs/Releng/CBIaggregator.groovy, JenkinsJobs/Releng/PublishJDTtoMaven.groovy, JenkinsJobs/Releng/PublishPDEToMaven.groovy, JenkinsJobs/Releng/PublishPlatformToMaven.groovy, JenkinsJobs/Releng/cleanupReleaseArtifacts.groovy, JenkinsJobs/Releng/createMaintenanceBranch.groovy, JenkinsJobs/Releng/newStreamRepos.groovy, JenkinsJobs/Releng/renameAndPromote.groovy, JenkinsJobs/Releng/tagEclipseRelease.groovy
Add Java 20 tests to I-builds now that they're working.
=> Update jenkins jobs to use centos-latest instead of migration. 

JenkinsJobs/AutomatedTests/ep426I_unit_cen64_gtk3_java11.groovy, JenkinsJobs/AutomatedTests/ep426I_unit_cen64_gtk3_java17.groovy, JenkinsJobs/AutomatedTests/ep426I_unit_cen64_gtk3_java19.groovy, JenkinsJobs/AutomatedTests/ep426I_unit_mac64_java17.groovy, JenkinsJobs/AutomatedTests/ep426I_unit_macM1_java17.groovy, JenkinsJobs/AutomatedTests/ep426I_unit_win32_java11.groovy, JenkinsJobs/Releng/collectResults.groovy
Missed some needed updates related to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/650.
=> Update CollectResults and tests to use new parameters.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://repo1.maven.org/maven2/com/ibm/icu/icu4j/72.1/
=> Update icu4j to latest 72.1

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/Releng/collectResults.groovy
And update CollectResults to use publish.xml instead of genTestIndexes
=> Switch to milestone build schedule

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Contains a number of bundle rebuilds for resigning purposes. Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/589
=> Update to latest Orbit

cje-production/mbscripts/mb300_gatherEclipseParts.sh
=> Fix gatherEclipseParts script

cje-production/scripts/publish.xml
The path to testResults.php was incorrect in publish.xml which is likely part of what is causing results not to show up.
=> Fix: updathing path in publish.xml

cje-production/scripts/publish.xml
Testing locally this change fixed #669
=> fix: add publishingFiles/ to testManifest.xml path

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/591
=> Update to ECF 3.14.27.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/590
=> Update to EMF 2.32 release

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/589
=> Update to Orbit 2022-12

JenkinsJobs/Releng/createMaintenanceBranch.groovy
Fix for https://ci.eclipse.org/releng/job/Releng/job/createMaintenanceBranch/2/console
=> Change command to --set-upstream-to origin branchName

JenkinsJobs/Releng/createMaintenanceBranch.groovy
Make the branch for aggregator first then call the make branch function in a loop for all subrepositories.
=> Make branch creation a loop in createMaintenanceBranch.groovy

JenkinsJobs/Releng/createMaintenanceBranch.groovy
=> Fix grep in createMaintenanceBranches

JenkinsJobs/Releng/deployPlatformParentPom.groovy, JenkinsJobs/Releng/deploySdkPom.groovy
And add into for parent pom groovy.
#701
=> Add SDK groovy

JenkinsJobs/JobDSL.json
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/700
=> Enable both 4.26 and 4.27 streams

JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java11.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java19.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java20.groovy, JenkinsJobs/AutomatedTests/I_unit_mac64_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_macM1_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_win32_java11.groovy, JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/PerformanceTests/FOLDER.groovy, JenkinsJobs/PerformanceTests/ILR_perf_lin64.groovy, JenkinsJobs/PerformanceTests/ILR_perf_lin64_baseline.groovy, JenkinsJobs/PerformanceTests/I_perf_lin64.groovy, JenkinsJobs/PerformanceTests/I_perf_lin64_baseline.groovy, JenkinsJobs/Releng/collectPerfResults.groovy
Should create new jobs for #702 
Will break if we run the 4.27 build since it will be looking for 4.27 performance tests but I'm going to convert those next.
=> Updating I build and unit tests to build new jobs from json

scripts/GAReleasePrep.sh, scripts/declareMilestone.sh, scripts/newReleasePrep.sh
Noticed some typos.
Leaving open for now in case I need to add new tasks etc.
=> New script

RELEASE.md
and have current instructions for setting up a new release.
=> Update documentation to be more readable 

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
=> Update previous release version to 4.26RC2

cje-production/cleaners/cleanupNightlyRepo.sh
=> Update cleanup script for 4.27

cje-production/scripts/checkComposites/checkComposites.sh
=> Update check composites script to verify 4.27 repos

eclipse.platform.releng.tychoeclipsebuilder/rcp.config/config.product, eclipse.platform.releng.tychoeclipsebuilder/rcp.config/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/rcp.config/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/725
=> Version bumps for 4.27 stream

production/testScripts/configuration/streamSpecific.properties
Additional change needed for #718
=> Update previous location for tests to 4.26RC2

cje-production/mbscripts/mb300_gatherEclipseParts.sh
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/181
=> Fixed ecj bundle location / name

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
=> Use 4.26 GA as previous release version

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
To progressively replace older javax ones from Orbit
=> Add official jakarta bundles from Central to TP

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/758 
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/759
=> Update the target platform's Maven dependencies to the latest available

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/759
=> Update the target platform's slf4j-api from 2.0.3 to 2.0.6

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/136
=> Remove lucene 8.4.1 from target platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Add ECF httpclientjava feature to the target for P2

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Update Orbit for 4.27 M1

JenkinsJobs/Cleanup/dailyCleanOldBuilds.groovy, JenkinsJobs/Releng/collectPerfResults.groovy
Also update a path in collectPerfResults.
=> Move daily clean job into the Cleanup folder.

Jenkinsfile
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/794
=> Disable signing except for master and maintenance branches

JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy, cje-production/scripts/publish.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testConfigs.php
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/756
=> Run windows tests with Java 17

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/364
=> Add asm-analysis to target

JenkinsJobs/YBuilds/FOLDER.groovy, JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy, JenkinsJobs/YBuilds/collectYbuildResults.groovy, JenkinsJobs/YBuilds/ep425Y_unit_cen64_gtk3_java17.groovy, JenkinsJobs/YBuilds/ep425Y_unit_cen64_gtk3_java20.groovy, JenkinsJobs/YBuilds/ep425Y_unit_mac64_java17.groovy, JenkinsJobs/YBuilds/ep425Y_unit_macM1_java17.groovy, JenkinsJobs/YBuilds/ep425Y_unit_win32_java17.groovy, cje-production/P-build/buildproperties.txt, cje-production/P-build/mb300_gatherEclipseParts.sh, cje-production/Y-build/buildproperties.txt, cje-production/Y-build/publish.xml, cje-production/Y-build/testConfigs.php, cje-production/scripts/testScripts/getEBuilder.xml, cje-production/scripts/testScripts/runTests2.xml, cje-production/streams/repositories_java19patch.txt, cje-production/streams/repositories_java20.txt, cje-production/streams/repositories_java20patch.txt
First pass at adding Y and P builds for Java 20
@akurtakov
I probably missed something.
=> Update Y and P builds for BETA_JAVA20 branch

eclipse.platform.releng.tychoeclipsebuilder/java20patch/eclipse.releng.repository.java20patch/antrunbuild.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/eclipse.releng.repository.java20patch/category.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/eclipse.releng.repository.java20patch/patchMatchVersion.xsl, eclipse.platform.releng.tychoeclipsebuilder/java20patch/eclipse.releng.repository.java20patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/.settings/org.eclipse.core.resources.prefs, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/.settings/org.eclipse.core.runtime.prefs, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/build.properties, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/feature.properties, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/forceQualifierUpdate.txt, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.dummy/.settings/org.eclipse.jdt.core.prefs, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.dummy/META-INF/MANIFEST.MF, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.dummy/build.properties, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/build.properties, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/feature.properties, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/sourceTemplateFeature/feature.properties, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/sourceTemplateFeature/p2.inf, eclipse.platform.releng.tychoeclipsebuilder/java20patch/pom.xml
=> Add java20patch folder to eclipse.platform.releng.tychoeclipsebuilder

README.md
Added link to https://ci.eclipse.org/releng/view/Builds/job/AutomatedTests/
=> Added test jobs location

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Update Orbit for 4.27 M2

JenkinsJobs/Releng/collectPerfResults.groovy, JenkinsJobs/SmokeTests/StartSmokeTests.groovy, JenkinsJobs/YBuilds/P_build.groovy, cje-production/streams/repositories_java20patch.txt
- Added a missing argument to collect results
- Set start smoketests to start the versions in the Smoke Tests folder
- Updates for P-builds
=> Build Updates

JenkinsJobs/YBuilds/ep425Y_unit_cen64_gtk3_java20.groovy, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/feature.xml
Fix JDT version for P-builds
Fix name of y-build java20 test
=> Y and P build fixes (again)

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Upstream scangelog https://github.com/java-native-access/jna/blob/5.13.0/CHANGES.md#release-5130
=> Update to JNA 5.13.0

JenkinsJobs/Builds/I_build.groovy, Jenkinsfile
Java 20 work is going in a branch and these tests can't succeed until this branch is merged in master.
=> Don't trigger Java 20 tests

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
Also specify Java 17 in the launch configuration.
=> Update Platform.setup to create a Java 17 JRE.

oomph/Platform.setup
https://github.com/eclipse/ecf/issues/25
=> Comment out m2e's nature and builder from ECF projects.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/778
=> Update to Orbit 2023-03 M3

eclipse.platform.releng.tychoeclipsebuilder/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/870
=> Force PGP sign org.jdom and org.jdom.source.

JenkinsJobs/YBuilds/Y_build.groovy
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/882
=> Stop generating source tarballs during y-builds

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy, cje-production/mbscripts/mb200_createSourceBundles.sh
added generation of eclipse.platform.releng.aggregator-${HASH}.zip file again
fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/882
=> Retire generation of source tar ball

.github/workflows/updateRelease.yml
Only config change to build scripts.
=> Use a recursive glob pattern to include all pom and manifest changes

.github/workflows/updateRelease.yml
Due to
- https://github.com/peter-evans/create-pull-request/issues/1665
=> add an extra include for the root pom.xml

cje-production/cleaners/cleanupNightlyRepo.sh
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/922
=> Update builds and repo cleanup scripts for 4.28

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/JobDSL.json, JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy, cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, cje-production/streams/repositories_R4_27_maintenance.txt, cje-production/streams/repositories_java20patch.txt
fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/933
=> Move 4.27-I builds to R4_27_maintenance branch

eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/updateTestResultsPages.sh, scripts/updateProductVersion.sh
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/931
=> Move previous version to 4.27RC2 across build scripts #931

JenkinsJobs/Releng/deployPlatformParentPom.groovy, JenkinsJobs/Releng/deploySdkPom.groovy
branch
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/936
=> Update Parent pom and target sdk deployment jobs for R4_27_maintenance

eclipse-platform-sources/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/eclipse.releng.repository.java20patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/rcp.config/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/rcp/pom.xml, pom.xml
- Releng
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/916
=> POM and product version changes for 4.28 release

JenkinsJobs/Builds/I_build.groovy
File : I_Build.groovy
@sravanlakkimsetti
=> IBuild Schedule changed

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/937
=> Update Comparator repo and eclipse run repo to 4.28-I-builds repo

cje-production/streams/repositories_java20.txt, cje-production/streams/repositories_java20patch.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/pom.xml
Below Modified Plugin added for Patch build
org.eclipse.jdt.ui
org.eclipse.jdt.core.manipulation
org.eclipse.jdt.astview
Files Changes :
1. ..java20patch.feature.xml
2. java20patch.pom.xml
3. platform-parent.pom.xml : Repo for Targeted build (4.27RC2).
@sravanlakkimsetti Please review it.
=> Modified Plugin for Java20 Patch build

cje-production/streams/repositories_java20.txt, cje-production/streams/repositories_java20patch.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/pom.xml
* Modified Plugin for Java20 Patch build (CherryPick #949)
Below Modified Plugin added for Patch build
org.eclipse.jdt.ui
org.eclipse.jdt.core.manipulation
org.eclipse.jdt.astview
Files Changes :
1. ..java20patch.feature.xml
2. java20patch.pom.xml
3. platform-parent.pom.xml
* Modified Plugin for Java20 Patch build
* Changes Done for BetaJava20 for Y/P build
eclipse.jdt.ui set to BETA_JAVA20 since plugins added to BETA_JAVA20
* Updated version for Java20
@sravanlakkimsetti Please review.
=> Modified Plugin for Java20 Patch build 4_27Maintenance

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/958
=> Update R4_27 maintenance branch with release version for 4.27+ changes

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
Tracked by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/957
=> Update previous release version to 4.27 GA across build scripts

.github/workflows/README.MD, .github/workflows/checkMergeCommits.yml
Fix https://github.com/eclipse-platform/eclipse.platform.releng/issues/214
=> Add a shared workflow to check for merge commits in a branch

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
And its dependency bytebuddy to 1.14.2
=> Update Mockito to 5.2.0

JenkinsJobs/Releng/collectResults.groovy
Fixes https://github.com/eclipse-platform/eclipse.platform.releng/issues/217
=> Run collectResults with Java 17

JenkinsJobs/Builds/I_build.groovy
@sravanlakkimsetti plz review.
=> Update Schedule for M1 Milestone

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/998
=> Update the target platform to EMF 2.34 M1

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/996
=> Update target platform to use Orbit's 2023-06 M1 repository

JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java20.groovy, JenkinsJobs/Builds/I_build.groovy
@sravanlakkimsetti Please check
=> Adding Java20 unit test.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- [net.bytebuddy](https://repo1.maven.org/maven2/net/bytebuddy/)
- [byte-buddy](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/) **[1.14.3](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.14.3)** < [1.14.4](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.14.4/)
- [byte-buddy-agent](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/) **[1.14.3](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.14.3)** < [1.14.4](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.14.4/)
- [org.bouncycastle](https://repo1.maven.org/maven2/org/bouncycastle/)
- [bcpg-jdk18on](https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/) **[1.72.2](https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.72.2)** < …
=> Update target platform versions

oomph/Platform.setup
https://github.com/eclipse-platform/.github/issues/113
=> Update Platform.setup to use latest webtools I builds

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
As it's test dependency only simplify the target file by using 0.0.0 so move to new reddeer becomes just updating the p2 url.
=> Update RedDeer to 4.5.0

production/README.md
@MohananRahul hopefully this should provide some more context for performance tests.
=> Update performance ReadMe with more information about how the tests run.

JenkinsJobs/YBuilds/Y_build.groovy, JenkinsJobs/YBuilds/Y_unit_cen64_gtk3_java21.groovy, cje-production/Y-build/buildproperties.txt, cje-production/Y-build/publish.xml, cje-production/Y-build/testConfigs.php, cje-production/streams/repositories_java21.txt
Tracked #1028 
Please check @sravanlakkimsetti
=> YBuild Update for Java21 (#1028)

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Please check
@sravanlakkimsetti
=> Update bundled jetty to version 10.0.15

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/998
=> Update target platform for EMF 2.34 M2

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/996
=> Update Orbit repository

eclipse-platform-parent/pom.xml
@sravanlakkimsetti @iloveeclipse Please review it 
#1076
=> Update cbi-ecj-version from M3

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/996
=> Update to Orbit's release repository

JenkinsJobs/JobDSL.json, cje-production/buildproperties.txt, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/eclipse-junit-tests.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.sdk.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.sdk.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/rcp.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/rcp.sdk.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product, eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/equinox-sdk.product, eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/EclipseRTOSGiStarterKit.product, production/testScripts/configuration/streamSpecific.properties, production/testScripts/test_runTests2.xml.sh, scripts/updateProductVersion.sh
=> Update product version number to 4.29 in build scripts

JenkinsJobs/Releng/deployPlatformParentPom.groovy, JenkinsJobs/Releng/deploySdkPom.groovy
branch
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1097
=> Update Parent pom and target sdk deployment jobs for R4_28_maintenance

eclipse-platform-parent/pom.xml, eclipse-platform-sources/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/eclipse.releng.repository.java20patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/org.eclipse.jdt.java20patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java20patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/rcp.config/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/rcp/pom.xml, pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1100
=> POM and product version changes for 4.29 release

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list.txt
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1120
=> Cleanup approved API changes

cje-production/buildproperties.txt
tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1089
=> Update product version number to 4.29 across build scripts

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1122
=> Update Comparator repo and eclipse run repo to 4.29-I-builds repo

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1136
@akurtakov @sravanlakkimsetti
=> Update previous release version to 4.28 GA across build scripts

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
* Mockito to 5.4.0
* ByteBuddy to 1.14.5
=> Update Mockito and ByteBuddy versions

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
update Batik version to 1.16 and its dependency
=> Update batik versions

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1175
=> Fix setup for merge of platform.common into platform.aggregator

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
https://github.com/eclipse-platform/eclipse.platform/pull/524
=> Update the setups for the merge eclipse-debug into eclipse-platform

eclipse-platform-parent/pom.xml
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1184
=> Promote next ecj build so it can be used to build SDK #1184

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
https://github.com/eclipse-platform/eclipse.platform.ua/issues/163
=> Update the Oomph setup for the merge of ua into platform:

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1197
=> Update to EMF 2.35's M1 milestone

eclipse.platform.releng.prereqs.sdk/.gitignore, eclipse.platform.releng.prereqs.sdk/.project, oomph/Platform.setup
Instead of generating it in the Oomph-setup.
@merks what do you think?
=> Add .project file for o.e.platform.releng.prereqs.sdk

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/42
=> Merge news into website

eclipse-platform-parent/pom.xml
=> Update ECJ version

cje-production/mbscripts/mb220_buildSdkPatch.sh
@sravanlakkimsetti 
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1203
=> Changes added to use current build compiler

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1216
=> Update set for merge of releng into aggregator

cje-production/streams/repositories_java21patch.txt
@sravanlakkimsetti @SDawley 
Adding this missing file.
=> Adding Java21 Patch file.

JenkinsJobs/YBuilds/Y_unit_cen64_gtk3_java21.groovy
=> Updating Ybuild java21 download

JenkinsJobs/Builds/I_build.groovy
=> Update I-Build Groovy

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-orbit/orbit-simrel/issues/8 https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1245
=> Use latest junit and hamcrest versions

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
It's no longer needed nor used.
=> Remove org.hamcrest.core 1.3.0

eclipse.platform.releng/features/org.eclipse.rcp/rootfiles/readme/readme_eclipse.html
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1262
cc @SarikaSinha
=> Readme file for 4.29

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1197
=> Update target platform to the EMF 2.35 release

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1199
=> Update the target platform to Orbit's 4.29 / 2023-09 release

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.28/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.29/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.29/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.29/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_29_porting_guide.html
Missing migration files for the 4.29rc2a
=> Missing migration files for the 4.29rc2a

.github/workflows/prepareRelease.yml
See 
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1289
=> Fix the workflow referencing the tycho released version

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/forceQualifierUpdate.txt, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/forceQualifierUpdate.txt, eclipse.platform.common/bundles/org.eclipse.pde.doc.user/forceQualifierUpdate.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/forceQualifierUpdate.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/forceQualifierUpdate.txt
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1304
=> Clean forceQualifierUpdate files for doc bundles

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list.txt
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1306
=> Cleanup approved api list

JenkinsJobs/Releng/deployPlatformParentPom.groovy, JenkinsJobs/Releng/deploySdkPom.groovy
branch
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1288
=> Update Parent pom and target sdk deployment jobs for R4_29_maintenance

cje-production/cleaners/cleanupNightlyRepo.sh
Track in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1312
=> Update builds and repo cleanup scripts for 4.30

cje-production/scripts/checkComposites/checkComposites.sh
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1314
=> Update check composites script to verify 4.30 repositories

JenkinsJobs/Builds/I_build.groovy, eclipse-platform-parent/pom.xml, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/jdtOptions.txt, eclipse.platform.common/bundles/org.eclipse.pde.doc.user/pdeOptions.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt, eclipse.platform.releng.tychoeclipsebuilder/java21patch/eclipse.releng.repository.java21patch/category.xml, eclipse.platform.releng.tychoeclipsebuilder/java21patch/org.eclipse.jdt.java21patch/sourceTemplateFeature/feature.properties
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1299
=> Update product version number to 4.30 across build scripts

JenkinsJobs/Builds/I_build.groovy, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/jdtOptions.txt, eclipse.platform.common/bundles/org.eclipse.pde.doc.user/pdeOptions.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt, eclipse.platform.releng.tychoeclipsebuilder/java21patch/eclipse.releng.repository.java21patch/category.xml, eclipse.platform.releng.tychoeclipsebuilder/java21patch/org.eclipse.jdt.java21patch/sourceTemplateFeature/feature.properties
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1299
=> Update product version number to 4.30 across build scripts #1299

eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.help-feature/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1319
=> version Bumps for 4.30

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml, eclipse.platform.common/bundles/org.eclipse.pde.doc.user/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.pde.doc.user/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1319
=> Version bumps for 4.30 stream

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr, eclipse.platform.releng/publish-to-maven-central/properties.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1328 
Changes to SDK4Mvn.aggr and properties.sh file for publishing 4.29 to maven central.
@sravanlakkimsetti 
@MohananRahul
=> Changes in SDK4Mvn.aggr and properties.sh

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1330
=> Update to Jetty 10.0.16

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1322
=> Update R4_29 maintenance branch with release version for 4.29+ changes

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1330
Ref: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1331
=> backport: Update to Jetty 10.0.16

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1349
=> Add org.eclipse.orbit.xml-apis-ext to the target platform

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/bundles/org.eclipse.releng.tests/ignoreFiles.txt, eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml
Replace some with org.mortbay.jasper.apache-jsp.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1251
=> Remove references to org.apache.jasper.glassfish

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1358
=> Remove references to org.glassfish.web.javax.servlet.jsp

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Required for
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/1129
=> Add jakarta.annotation / jakarta.inject 2.0 API

eclipse-platform-parent/pom.xml
includePackedArtifacts is gone in latest tycho
=> Remove useless target-platform-configuration

cje-production/scripts/publish.xml
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1381
=> Update publish.xml to use Java 21 build

JenkinsJobs/SmokeTests/StartSmokeTests.groovy
updating smoke test java 21 and removing java19
=> Update Smoke test java 21

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1391
=> Update target platform to EMF 2.36 M1

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1390 
https://github.com/eclipse-equinox/p2/issues/330
=> Update ECF to snapshot if fix for basic-auth problem

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
First step towards
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1384
=> Add Jetty 12 bundles to target platorm.

eclipse.platform.releng/features/org.eclipse.help-feature/forceQualifierUpdate.txt
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1419
=> Touch org.eclipse.help to "include" latest org.eclipse.equinox.http.jetty

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/jdtOptions.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/buildDoc.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt
as it was migrated from JDT to Platform
=> [Doc] Update links to LTK

eclipse-platform-parent/pom.xml
Tycho has some enhancements especially at API tools and transport handling (compression), that I would like to release soon, to perform some more confidence check I'd like update platform using the current SNAPSHOT until end of October to see if we have any issues that need to be fixed before the release.
=> Use Tycho 4.0.4-SNAPSHOT

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1391
=> Update target platform to EMF 2.36 M2

eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1444
=> Remove includes of org.eclipse.jetty.* from org.eclipse.help feature

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1392
=> Update target platform to Orbit m2

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1390
=> Update ECF to 3.14.40.v20231021-2127

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Jetty Version to 9.4.53.v20231009
=> Jetty version update

.mvn/extensions.xml, eclipse-platform-parent/pom.xml, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Update jetty 10.0.17 and bcprov 1.76
=> Update jetty and bcprov

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1463
=> Don't specify JVM memory limits in eclipse.ini

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Backport : Update jetty

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Jetty and Batik changes

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_director.html
Improve/simplify the documentation by generating it much like -help already generates it.
https://github.com/eclipse-equinox/p2/issues/365
=> Update p2 director documentation with latest arguments

eclipse.platform.releng.tychoeclipsebuilder/java21patch/org.eclipse.jdt-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java21patch/org.eclipse.jdt.java21patch/feature.xml, eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.platform-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.rcp/feature.xml, eclipse.platform.releng/features/org.eclipse.sdk.examples-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml, eclipse.platform.releng/features/org.eclipse.sdk/feature.xml, eclipse.platform.releng/features/org.eclipse.test-feature/feature.xml
Apply the result of https://github.com/eclipse-pde/eclipse.pde/issues/730
=> Remove unnecessary attributes from feature.xml files

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1391
=> Update target platform to EMF 2.36 M3

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1392
=> Update dependencies to Orbit m3

oomph/Platform.setup
https://github.com/eclipse-jdt/eclipse.jdt/issues/79
=> Encourage rebase on forks by configuring the clone default for that

eclipse-platform-parent/pom.xml
Merge after Job run
https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/
=> Update ECJ compiler 

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1392
=> Update dependencies to Orbit rc1

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
RC1 : https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1390
=> Eclipse 4.30 Prerequisites: ECF

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://www.bouncycastle.org/releasenotes.html#r1rv77
=> Update bouncycastle to 1.77

.github/workflows/verifyFreezePeriod.yml
Fix the link to the Platform calendar.
Fixes #1544.
=> verifyFreezePeriod.yml: Fix calendar link

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.30/faq.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.30/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.30/recommended.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/eclipse_4_30_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.30/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.30/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.30/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_30_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Porting.xml
Migration guide for Eclipse 4.30 from 4.29
=> Migration guide Eclipse 4.30

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1390
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1391
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1392
=> Update ECF, EMF, and Orbit to final release repositories in TP

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
With https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1558 the required action is done.
=> [TP] Remove resolved warning

eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/topics_WhatsNew.xml, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/whatsNew/jdt_whatsnew.html
Breaking change from JDT side that needs to be incorporated.
Ref: https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/93/files
=> New & Noteworthy 4.30 Edits : Changes from JDT side

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/whatsNew/platform_whatsnew.html
Fixes: https://github.com/eclipse-platform/www.eclipse.org-eclipse/issues/96
@MohananRahul @merks
=> N and N 4.30: Fix broken links

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/JobDSL.json, JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy, cje-production/buildproperties.txt
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1569
=> Move 4.30-I builds to R4_30_maintenance branch

JenkinsJobs/Releng/deployPlatformParentPom.groovy, JenkinsJobs/Releng/deploySdkPom.groovy
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1571
=> Update pom target sdk deployment jobs for R4_30_maintenance branch

eclipse.platform.releng/bundles/org.eclipse.rcp/META-INF/MANIFEST.MF, eclipse.platform.releng/bundles/org.eclipse.sdk.examples/META-INF/MANIFEST.MF, eclipse.platform.releng/bundles/org.eclipse.sdk.tests/META-INF/MANIFEST.MF, eclipse.platform.releng/features/org.eclipse.platform-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.platform-feature/rootfiles/.eclipseproduct, eclipse.platform.releng/features/org.eclipse.rcp/feature.xml, eclipse.platform.releng/features/org.eclipse.sdk.examples-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml, eclipse.platform.releng/features/org.eclipse.sdk/feature.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1557
=> Update product version number

cje-production/cleaners/cleanupNightlyRepo.sh, eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list.txt
and Cleanup approved api list
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1557
=> Update builds and repo cleanup scripts for 4.31

cje-production/scripts/checkComposites/checkComposites.sh
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1557
=> Update check composites script to verify 4.31 repositories

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml, eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.help-feature/pom.xml
Tracked in eclipse-platform/eclipse.platform.releng.aggregator#1590
=> Version bumps for 4.31 stream

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1557
=> Update Comparator repo and eclipse run repo to 4.31-I-builds repo

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/PerformanceTests/ILR_perf_lin64.groovy, JenkinsJobs/PerformanceTests/ILR_perf_lin64_baseline.groovy, JenkinsJobs/PerformanceTests/I_perf_lin64.groovy, JenkinsJobs/PerformanceTests/I_perf_lin64_baseline.groovy
=> IBuild schedule update and Performance test fixing

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#1592 PR, Still we don't have stable build and will create PR again after stable build
=> Revert "Update Comparator repo and eclipse run repo to 4.31-I-builds repo"

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr, eclipse.platform.releng/publish-to-maven-central/properties.sh
Publishing 4.30 to maven central
Fixes:https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1616
@MohananRahul
=> Publish 4.30 to maven central

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Lets see if we can have license checks here...
=> Add bndtools API for templating

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
Changing version from 4.30 to 4.31 I-builds
Fixes: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1616
@MohananRahul
=> Changing version from 4.30 to 4.31 I-builds

eclipse-platform-parent/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1630
=> Add JUnitTestRunnerInterceptor for JUnit4 Parameterized tests #1630

oomph/Platform.setup
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1605
=> Disable the platform setup's early redirect

JenkinsJobs/YBuilds/Y_build.groovy, JenkinsJobs/YBuilds/Y_unit_cen64_gtk3_java22.groovy, cje-production/P-build/buildproperties.txt, cje-production/P-build/mb300_gatherEclipseParts.sh, cje-production/Y-build/buildproperties.txt, cje-production/Y-build/publish.xml, cje-production/Y-build/testConfigs.php, cje-production/streams/repositories_java21patch.txt, cje-production/streams/repositories_java22.txt, cje-production/streams/repositories_java22patch.txt
Updating Y and P build for Java 22
=> YBuild Update for Java 22

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1377
=> Fix maven mapping for org.eclipse.orbit.xml-apis-ext

eclipse-platform-parent/pom.xml
did not work
This reverts commit efcc7c7167834f0a8aa69c9e987ae919d4969bdf. 
This reverts commit 17d93aab9fd650befc4ba5c9d341dcbd41172e86.
=> Revert "JUnitTestRunnerInterceptor" #1641

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Required for 
- https://github.com/eclipse-pde/eclipse.pde/pull/999
=> Add jakarta.activation-api to the target

eclipse.platform.releng/bundles/org.eclipse.releng.tests/src/org/eclipse/releng/tests/TouchBundles.java
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1686
=> Small fix for TouchBundles to properly touch PDE

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/features/org.eclipse.test-feature/forceQualifierUpdate.txt
Use Orbit m1.
Use EMF m1.
Update batik to 1.17.0.
Update lucene to 9.9.1.
Update to Jetty 12.0.5.
Update jna to 5.14.0.
Update icu4j to 74.2.
Update jsoup to 1.17.2.
Update slf4j to 2.0.10.
Update assertj to 3.25.0.
=> Update the target platform

eclipse.platform.releng.tychoeclipsebuilder/rcp.config/forceQualifierUpdate.txt
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1714
=> I20240112-0450 build is unstable (Mac launcher)

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1698
=> Update ECF to 3.14.41

JenkinsJobs/Builds/I_build.groovy
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1724#issuecomment-1892602584
=> Revert declaration of maven tool to unbreak sshagent step in I-build

eclipse-platform-parent/pom.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1904
=> Update to newer ecj batch compiler

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/removals.html
removed with
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1563
=> org.eclipse.ui.commands API removal

eclipse-platform-parent/pom.xml
3.37.0.v20240131-1047
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1760
=> Update latest ECJ batch Version

eclipse-platform-parent/pom.xml, eclipse.platform.releng/bundles/org.eclipse.test.performance/pom.xml
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1628
=> remove code.ignoredWarnings

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
Use this release repositories instead of the previos ones.
=> Use 4.31/2024-03 p2 repo url

eclipse-platform-parent/pom.xml
See
- https://github.com/eclipse-tycho/tycho/pull/3430
- https://github.com/eclipse-tycho/tycho/pull/3447
- https://github.com/eclipse-tycho/tycho/pull/3451
- https://github.com/eclipse-tycho/tycho/pull/3459
- https://github.com/eclipse-tycho/tycho/pull/3460
=> Use 4.0.6-SNAPSHOT for latest fixes/enhancements

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-10.htm
Refer to:
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1626
=> Document "Incremental View Updates" preference

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-11.htm
Remove no longer available options and add not yet documented options.
=> Update documentation of the "Compare / Patch" Preference Page

oomph/Platform.setup
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1612
=> uniformly use 4GB Heap on Workspace

eclipse-platform-parent/pom.xml
Finishes work for
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1781
=> Use latest ecj batch compiler

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1696
=> Update to EMF M3

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-12.htm
Make the "Allow in-place system editors" more clear.
=> Improve "Editors" Preference Page

eclipse.platform.releng/publish-to-maven-central/CBIaggregator.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1815
=> Avoid removing "unittest" bundles from the Maven publishing

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Update lucene to 9.10.0
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1697
=> Update to Orbit RC1

eclipse.platform.releng/features/org.eclipse.rcp/rootfiles/readme/readme_eclipse.html
=> Readme for Eclipse4.31

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1696
=> Update to the EMF 2.37 release

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.31/faq.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.31/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.31/recommended.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/eclipse_4_31_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.31/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.31/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.31/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_31_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Porting.xml
Migration guide for Eclipse 4.31 from 4.30
=> Migration Guide Eclipse 4.31

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-startup.htm
Documentation for
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1453
=> Add Documentation for Windows Defender Check

.github/workflows/prepareRelease.yml, .github/workflows/updateRelease.yml
=> Update Workflow with Tycho released Version.

JenkinsJobs/Releng/deployPlatformParentPom.groovy, JenkinsJobs/Releng/deploySdkPom.groovy
Fixes: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1847
=> Update Parent pom and target sdk deployment jobs for R4_31_maintenance branch

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/JobDSL.json, JenkinsJobs/YBuilds/Y_build.groovy
Update I and Y builds
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1850
=> Update DSL for new test and Build

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh, scripts/updateProductVersion.sh
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1857
=> Move previous version to 4.31RC2 across build scripts

cje-production/cleaners/cleanupNightlyRepo.sh
Fixes in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1865 Cleanup change
=> Update builds and repo cleanup scripts for 4.32

cje-production/scripts/checkComposites/checkComposites.sh
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1869
=> Update check composites script to verify 4.32 repositories

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1871
=> Update Comparator repo and eclipse run repo to 4.32-I-builds repo

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Update R4_31 maintenance branch with release version for 4.31+ changes
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1883
@MohananRahul : Can you review and merge this please.
=> Update R4_31 maintenance branch with release version for 4.31+ changes

eclipse.platform.releng/publish-to-maven-central/CBIaggregator.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1882
=> Aggregate without org.eclipse.ecf.provider.filetransfer.httpclientjava

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1882
=> Map org.eclipse.e4.ui.swt.gtk 1.2.100.v20231030-204 to maven 1.2.101

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1882
=> Map org.eclipse.ui.cocoa 1.3.100.v20230214-1401 to 1.3.101

JenkinsJobs/Builds/I_build.groovy, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1894
=> Update previous release version to 4.31 GA across build scripts

eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java22patch/org.eclipse.jdt-feature-dummy/feature.xml, eclipse.platform.releng.tychoeclipsebuilder/java22patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java22patch/org.eclipse.jdt.java22patch/feature.xml
=> Version Update for PBuild

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_director.html
A new option is introduced by
https://github.com/eclipse-equinox/p2/issues/484.
=> Update P2 director documentation with new option -addJREIU

eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml
Required for https://github.com/eclipse-equinox/equinox/pull/562
=> Replace deprecated core.launcher.Main by equinox.launcher.Main

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1951
=> Update ASM to 9.7

eclipse-platform-parent/pom.xml
Should fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1960
=> Update to latest ecj compiler

eclipse-platform-parent/pom.xml
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1979
=> Updated ecj to 3.38.0.v20240415-2034

eclipse-platform-parent/pom.xml
Configured , Please run https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ and Merge this PR
=> Update ECJ version for M2

JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java21.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java22.groovy, JenkinsJobs/AutomatedTests/I_unit_mac64_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_macM1_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy
=> [I-Build-Tests] Unify descriptions, parameter and log-rotation specs

eclipse-platform-parent/pom.xml
See
- https://github.com/eclipse-tycho/tycho/pull/3806#issuecomment-2093630793
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1203
=> Use Tycho 4.0.8-SNAPSHOT

eclipse-platform-parent/pom.xml
Need to merge after
https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ run @iloveeclipse
=> ECJ Update for M3

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
There are no content changes relative to the milestone
=> Update target platform to the EMF 2.38.0 release

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
There are no content changes relative to the milestone
=> Update target platform to the Orbit 4.32.0

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
=> Use 4.32 / 2024-06 URLs in available sites

JenkinsJobs/Releng/deployPlatformParentPom.groovy, JenkinsJobs/Releng/deploySdkPom.groovy
fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2066
=> Update Parent pom and target sdk deployment jobs for R4_32_maintenance

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/JobDSL.json, JenkinsJobs/YBuilds/Y_build.groovy
tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2069
=> Update DSL to 4.33 for Test and Build

eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh, scripts/updateProductVersion.sh
fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2080
=> Move previous version to 4.32RC2a across build scripts

cje-production/cleaners/cleanupNightlyRepo.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2090
=> Update builds and repo cleanup scripts for 4.33

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml, eclipse.platform.releng/features/org.eclipse.platform-feature/rootfiles/.eclipseproduct
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2085
=> Version Bump for 4.33

cje-production/scripts/checkComposites/checkComposites.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2092
=> Update check composites script to verify 4.33 repositories

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2094
=> Update Comparator repo and eclipse run repo to 4.33-I-builds repo

JenkinsJobs/Builds/I_build.groovy
Schedule updated for 4.33 I-Build
=> Update IBuild Schedule for 4.33

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2111
=> Update previous release version to 4.32 GA across build scripts

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Update R4_32 maintenance branch with release version for 4.32+ changes
Fixes #2063
@MohananRahul : Can you review and merge this please.
=> Update R4_32 maintenance branch with release version for 4.32+ changes

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr, eclipse.platform.releng/publish-to-maven-central/properties.sh
Publish to maven central 4.32
Update SDK4Mvn.aggr and properties.sh file
=> publish 4.32 to maven central 

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
Changing the versions from 4.32 to 4.33-I-builds after publishing to maven central
Refs: #2102 
=> Changing the versions from 4.32 to 4.33-I-builds

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- This updates lucene to 9.11.0.
=> Update the target platform to Orbit 4.33 M0

JenkinsJobs/YBuilds/Y_build.groovy, cje-production/Y-build/publish.xml, cje-production/Y-build/testConfigs.php
=> Update YBuild Test

eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml
Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2614
=> Added org.eclipse.jdt.core.tests.builder.mockcompiler to test feature

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Backporting Jetty version to 12.0.10
=> Upgrade Jetty to 12.0.10

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy
Fixes a regression from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2149
=> [I/Y/P-Builds] Restore mount of toolchains.xml in K8 pod definitions

eclipse-platform-parent/pom.xml
Available : https://repo.eclipse.org/content/repositories/eclipse-staging/org/eclipse/jdt/ecj/
=> Update ECJ for M1

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This should get me going in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1523
Thanks, @merks ! :)
=> Markdown support for JEP 467

eclipse-platform-parent/pom.xml
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4845#note_2548373 and https://github.com/eclipse-cbi/org.eclipse.cbi/issues/496
=> Bump cbi plugins version to 1.5.0

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2164 
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2166
=> Update EMF and Orbit dependencies

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html
This new argument just got added. See https://github.com/eclipse-equinox/equinox/pull/595. Here we add the documentation for it.
=> Document the new --launcher.noRestart launcher argument.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Update sshd-osgi to 2.13.2.
- Update xz to 1.10.
- Update jetty to 12.0.12.
=> Update target platform dependencies

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2165
=> Update target-platform with latest version of ECF

JenkinsJobs/Builds/I_build.groovy, eclipse-platform-parent/pom.xml
Configured and needs to run : https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ then merge this PR
=> Update ECJ and Ibuild Schedule for RC1

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2165
=> Update target-Platform ECF for RC2

eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/tips/jdt_tips.html
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2243
=> Remove new tag from old entries in JDT tips

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2166
=> Update EMF to the 2.39.0 release repository

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2164
=> Update Orbit repository to the 4.33.0 release

eclipse.platform.releng/features/org.eclipse.rcp/rootfiles/readme/readme_eclipse.html
Readme changes for Eclipse 4.33
=> Readme changes for Eclipse 4.33

cje-production/P-build/buildproperties.txt, cje-production/P-build/mb300_gatherEclipseParts.sh
updating PBuild properties and script
=> PBuild Update for Java23

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/JobDSL.json
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2282
=> Update JobDSL for 4.34-I-builds

eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/test_runTests2.xml.sh, production/testScripts/updateTestResultsPages.sh, scripts/updateProductVersion.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2290
=> Move previous version to 4.33RC2 across build scripts

eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.help-feature/pom.xml
Contributes to
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2299
=> Version bump for 4.34 stream

.github/workflows/updateTarget.yml
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4943#note_2814821
@fredg02 can you review / approve?
=> Fix Bot E-mail

cje-production/scripts/checkComposites/checkComposites.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2306
=> Update check composites script to verify 4.34 repositories

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2308
=> Update Comparator repo and eclipse run repo to 4.34-I-builds repo

cje-production/buildproperties.txt
=> Update product version number to 4.34 build script

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2290
=> Move previous version to 4.33RC2a across build scripts

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr, eclipse.platform.releng/publish-to-maven-central/properties.sh
Publish 4.33 to maven central 
Update SDK4Mvn.aggr and properties.sh file
Refs: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2321
=> Publish 4.33 to maven central

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2325
=> Update previous release version to 4.33 GA across build scripts

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2317
=> Update R4_33 maintenance branch with release version for 4.33+ changes

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/testManifest.xml, eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml, production/testScripts/configuration/sdk.tests/testScripts/test.xml
https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/484
=> add org.eclipse.jdt.debug.jdi.tests to daily build

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Update org.apache.ant to 1.10.15.
=> Update target platform to Orbit M0.

eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/eclipse-junit-tests.product
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2332
=> Include plugins missing from the eclipse-Automated-Tests zip

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/discussions/2375
=> Update target platform to EMF M1

JenkinsJobs/Builds/I_build.groovy
As openjdk-jdk17-latest is stuck on older version.
=> Use temuring-jdk17-latest for I-builds

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2394
=> Add linxu/gtk/riscv64 the SDK4Mvn.aggr

eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/pom.xml
Caused by
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2392
=> Fix broken verification build

eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/AwtScreenshot.java
for "Eclipse-BundleShape: dir" in MANIFEST.MF
fix "Error: Could not find or load main class
org.eclipse.test.AwtScreenshot"
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1486
=> AwtScreenshot: Do not add "bin" to classpath #1486

eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/Screenshots.java
Screenshots must be taken before dispose
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1518
=> add ScreenshotOnFailure.onFailure(Supplier<Widget> shell)

oomph/Platform.setup
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2430
=> Add the PDE and SWT spies to the target platform

JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2468
=> Update JVM path for Windows Tests

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/forceQualifierUpdate.txt
Jquery version should be upgraded, therefore done force qualifier update in **R4_31_maintenance** branch
=> force qualifier update for the jQuery upgrade

production/testScripts/configuration/sdk.tests/testConfigs/linux/testAll.sh, production/testScripts/configuration/sdk.tests/testConfigs/macosx/testAll.sh, production/testScripts/configuration/sdk.tests/testConfigs/windows/testAll.bat
respectively enforce the presence of the corresponding variables.
=> [I-Build] Unify 'testAll' scripts and remove unused default values

.github/workflows/publishVersionCheckResults.yml
to harden workflow against poisoned pipeline executions (PPE).
=> Use environment variables in workflow for automated version increments

cje-production/streams/repositories_java24.txt
include:
* jdt.ui
* jdt.debug
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2505
=> More plugins to join Y-Builds from their BETA_JAVA24 branch

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Update Jetty version to 10.0.24 for 4_23 maintenance branch
=> Update Jetty version to 10.0.24

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> commons-io upgrade (ref: CVE-2024-47554)

JenkinsJobs/AutomatedTests/I_unit_linux.groovy
Save the complexity of a customized kubernetes pod configuration which doesn't seem to be necessary.
@akurtakov or @sravanlakkimsetti do you know any reason that requires a special image?
I'm currently experimenting with this change by replaying the latest I-build test execution for Linux-java17 at
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep434I-unit-linux-x86_64-java17/18/
This should confirm if this a save change.
At least when running only the `UI` suite all tests passed:
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep434I-unit-linux-x86_64-java17/17/
=> [I-Build-Tests] Run Linux tests on default 'centos-8' agent

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Update orbit to m3 repository
=> Update Jetty to 2.0.15

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Update Bouncycastle version in R4_27
=> Backport : Update Bouncycastle version

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Update sshd to 2.14

eclipse-platform-parent/pom.xml
Merge after running https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ @jarthana @mpalat
=> Update latest ECJ version for RC2

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/JobDSL.json, JenkinsJobs/YBuilds/Y_build.groovy
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2559
=> Create new test jobs for 4.35

eclipse.platform.releng/features/org.eclipse.platform-feature/rootfiles/.eclipseproduct
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2568
=> Update Product Version to 4.35

cje-production/scripts/checkComposites/checkComposites.sh
Fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2586
=> Update check composites script to verify 4.35 repositories

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2588
=> Update Comparator repo and eclipse run repo to 4.35-I-builds repo

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/images/redo_edit.svg, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/images/undo_edit.svg
Contributes to:
https://github.com/eclipse-platform/eclipse.platform.images/issues/113
=> Fix undo / redo icons according to standard

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
Fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2607
=> Update previous release version to 4.34 GA across build scripts

JenkinsJobs/Builds/AddToPComposite.groovy, JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/Builds/markStable.groovy, JenkinsJobs/Builds/markUnstable.groovy, JenkinsJobs/Cleanup/cleanupDLsite.groovy, JenkinsJobs/Cleanup/cleanupReleaseArtifacts.groovy, JenkinsJobs/Cleanup/dailyCleanOldBuilds.groovy, JenkinsJobs/Cleanup/pruneDailyRepos.groovy, JenkinsJobs/Releng/CBIaggregator.groovy, JenkinsJobs/Releng/PublishJDTtoMaven.groovy, JenkinsJobs/Releng/PublishPDEToMaven.groovy, JenkinsJobs/Releng/PublishPlatformToMaven.groovy, JenkinsJobs/Releng/checkCompositesValidity.groovy, JenkinsJobs/Releng/collectPerfResults.groovy, JenkinsJobs/Releng/collectResults.groovy, JenkinsJobs/Releng/createGenericComposites.groovy, JenkinsJobs/Releng/createMaintenanceBranch.groovy, JenkinsJobs/Releng/makeVisible.groovy, JenkinsJobs/Releng/newStreamRepos.groovy, JenkinsJobs/Releng/renameAndPromote.groovy, JenkinsJobs/Releng/tagEclipseRelease.groovy, JenkinsJobs/Releng/updateIndex.groovy, JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy, JenkinsJobs/YBuilds/collectYbuildResults.groovy
and run all other infrastructure-work jobs on the 'basic' image.
See https://www.eclipse.org/lists/cross-project-issues-dev/msg19990.html
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2610
=> [Build] Run I-/Y-/P-builds on ubuntu-2404

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr, eclipse.platform.releng/publish-to-maven-central/properties.sh
Publish to Maven central 4.34
Update SDK4Mvn.aggr and properties.sh file
Refs: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2606
=> Publish 4.34 to Maven central 

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Update R4_34 maintenance branch with release version for 4.34+ changes
Fixes #2556
=> Update R4_34 maintenance branch with release version for 4.34+ changes

JenkinsJobs/SmokeTests/StartSmokeTests.jenkinsfile
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2310
=> [Build] Add smoke test for linux.riscv64

eclipse-platform-parent/pom.xml
Prereq for https://github.com/eclipse-equinox/equinox/pull/716
=> Configure NotThreadSafe javadoc tag

production/testScripts/configuration/sdk.tests/testScripts/test.xml
=> sdk.tests/testScripts/test.xml: Kill msedgewebview2.exe processes

.github/workflows/checkVersions.yml, .github/workflows/codeQLworkflow.yml, .github/workflows/prepareRelease.yml, .github/workflows/updateRelease.yml, .github/workflows/updateTarget.yml
Prereq for
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2654
=> Use Java 21 for GH actions

JenkinsJobs/AutomatedTests/I_unit_linux.groovy, JenkinsJobs/AutomatedTests/I_unit_mac.groovy, JenkinsJobs/AutomatedTests/I_unit_win32.groovy
to get better statistics
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2653
=> Jenkins: longer i-Build history without artifacts #2653

JenkinsJobs/AutomatedTests/I_unit_mac.groovy, JenkinsJobs/Builds/I_build.groovy, cje-production/scripts/publish.xml
Fixes https://github.com/eclipse-platform/eclipse.platform/issues/1665
=> Switch Mac I-build tests to Java 21

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.p2.inf
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2623
=> Delete unconfigure touchpoint to remove -Djava.security.manager=allow

Jenkinsfile
I have already verified that the result is the same.
=> [Build] Simplify deployment of RelEng scripts in master branch build

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy
=> [Build] Unify tool-installation and PGP-settings in I-/Y-builds

JenkinsJobs/YBuilds/Y_build.groovy, JenkinsJobs/YBuilds/Y_unit_linux.groovy, JenkinsJobs/YBuilds/Y_unit_mac.groovy, JenkinsJobs/YBuilds/Y_unit_win32.groovy, cje-production/Y-build/publish.xml, cje-production/Y-build/testConfigs.php
Synchronizes the Y-build with all the changes recently applied to the I-build.
=> [Y-Build] Move Y-build and its tests on Java-21 and above

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy, cje-production/mbscripts/mb110_tagBuildInputs.sh
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/678
=> [Build] Skip scheduled I/Y-build if nothing has changed since last build

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
4.27 maintenance build failing due to reddeer termination
https://projects.eclipse.org/projects/technology.reddeer
=> Change Reddeer Repo to its archive location

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/equinox-sdk.product, eclipse.platform.releng/features/org.eclipse.sdk/feature.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2725
=> Remove references to all of ECF's ssl bundles and features

JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/YBuilds/P_build.groovy
The typo in the credential-id was discovered in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2731#discussion_r1906164328
=> [Build] Adapt to fixed credential-id of releng PGP-key passphrase

eclipse.platform.common/bundles/org.eclipse.jdt.tips.user/pom.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.tips/pom.xml, eclipse.platform.releng/bundles/org.eclipse.ant.optional.junit/pom.xml, eclipse.platform.releng/bundles/org.eclipse.rcp/pom.xml, eclipse.platform.releng/bundles/org.eclipse.releng.tests/pom.xml, eclipse.platform.releng/bundles/org.eclipse.sdk.examples/pom.xml, eclipse.platform.releng/bundles/org.eclipse.sdk.tests/pom.xml, eclipse.platform.releng/bundles/org.eclipse.test.performance.win32/pom.xml, eclipse.platform.releng/bundles/org.eclipse.test.performance/pom.xml, eclipse.platform.releng/bundles/org.eclipse.test/pom.xml
- Also fix test bundles and examples for simply for consistency.
=> Fix maven group id to match the actual deployment

.github/workflows/README.MD, .github/workflows/checkDependencies.yml
This adds a new shared workflow to check for inconsistencies in version ranges based on byte code analysis.
=> Add a shared workflow to check dependency version ranges

.github/workflows/checkDependencies.yml
this will only slow down things without a benefit
=> Skip test for dependency tests

JenkinsJobs/YBuilds/P_build.groovy, eclipse.platform.releng.tychoeclipsebuilder/java23patch/pom.xml
Apply the clean-ups recently applied to I/Y-builds also to the P-build job definition.
=> [P-build] Various clean-ups of Jenkins pipeline job definition

eclipse-platform-parent/pom.xml
This enables the cleanup of private fields that can be made final and replacing of deprecated method calls.
=> Enhance cleanup profile to include private final fields and deprecation

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2816
=> Remove bundles category.xml that are included by included features

.mvn/maven.config
=> Enable printout of memory infos

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2828
=> Update SDK product update sites to 4.35 release version

JenkinsJobs/Builds/FOLDER.groovy, JenkinsJobs/JobDSL.json
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2853
=> Create new test jobs for 4.36

.mvn/extensions.xml, eclipse-platform-parent/pom.xml
=> Update to Tycho 4.0.12

.github/workflows/prepareRelease.yml
Causing https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/actions/runs/13625275852/job/38081306024
=> Update Prepare Workflow

.github/workflows/updateRelease.yml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#2583
=> Revert "Adding *.product file for update release."

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2867
=> Move previous version to 4.35RC2 across build scripts

cje-production/cleaners/cleanupNightlyRepo.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2872
=> Update builds and repo cleanup scripts for 4.36

eclipse-platform-parent/pom.xml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#2876
=> Revert "Switch sdk repo to 4.35 as there is no 4.36 yet"

cje-production/buildproperties.txt, cje-production/scripts/checkComposites/checkComposites.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2882
and Update check composites script to verify 4.36 repositories.
=> Update eclipse run repo to 4.36-I-builds repo

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2884
=> Update maven publishing to publish 4.36.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
See
- https://github.com/eclipse-pde/eclipse.pde/issues/877
=> Add OSGi test dependencies

eclipse-platform-parent/pom.xml
As these are not pushed to maven central dependabot seems to not update them.
=> Update cbi plugins to 1.5.2

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2896
=> Update R4_35 maintenance branch with release version for 4.35+ changes

JenkinsJobs/Releng/publishToMaven.jenkinsfile
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2889
=> Remove guard preventing all javadoc.jar files from being created

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties, production/testScripts/updateTestResultsPages.sh
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2908
=> Update previous release version to 4.35 GA across build scripts

JenkinsJobs/Releng/collectResults.groovy
This allows control over JVM used to run buildtools.
=> Fix collectResult to run locally in Jenkins

oomph/Platform.setup
- Flesh in the values needed for the end of the 4.36 cycle
=> Disable the platform setup to redirect 4.34 to 4.35 and 4.35 to 4.36

Jenkinsfile
- There was another  heap space error building the war today.
=> Increase MAVEN_OPTS = '-Xmx3500m' to avoid out-of-memory building war

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Update to orbit milestone S202503161736 for com.sun.jna 5.17.0 and update jna-platform to 5.17.0.
- Update mockito-core to 5.16.1.
- Update jupiter to 5.12.1 and junit 1.12.1.
=> Target platform update

Jenkinsfile
- There was another  heap space error building the war today.
=> Increase MAVEN_OPTS = '-Xmx3800m' to avoid out-of-memory building war

cje-production/buildproperties.txt
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2931
=> Fixes update site link for org.eclipse.wtp.releng.tools.feature

oomph/Platform.setup
- WWD supports formatting and completion for  html, css, and javascript as used by the eclipse website project.
=> Update setup for website repository to install wildwebdeveloper

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
Set the wwd wrapLineLength to zero to avoid formatting changes to avoid formatting changing the entire file.
=> Remove the SWT website from the SDK configuration

Jenkinsfile
- There was another heap space error building the war last week.
=> Increase MAVEN_OPTS = '-Xmx4000m' to avoid out-of-memory building war

eclipse-platform-parent/pom.xml
As discussed in
- https://github.com/eclipse-equinox/equinox/pull/936#discussion_r2072660096
=> Enable 'Remove unnecessary array creation' in the cleanup profile

JenkinsJobs/Builds/build.jenkinsfile, cje-production/streams/repositories_java25.txt
Update YBuild config for Java 25
=> YBuild for Java25

.github/workflows/cleanCode.yml
Verification build will not test this.
=> Enable error stacktraces for the cleanup action

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
Products should have 4.36/2025-06 update sites rather then previous release ones.
=> Update p2 repos in products to current

eclipse-platform-parent/pom.xml
Should help unlock https://github.com/eclipse-pde/eclipse.pde/pull/1771
=> Enable clean-up to remove unused imports

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/index.template.php
Acknowledgment Readme and Project Plan. Changing link instead Static html page.
=> Download Page link Updation.

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3099
=> Update SDK4Mvn.aggr to 4.37-I-builds

production/testScripts/configuration/streamSpecific.properties
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3114
=> Update previous release version to 4.36 GA

oomph/Platform.setup
- Flesh in the values needed for the end of the 4.37 cycle
=> Disable the platform setup to redirect 4.35 to 4.36 and 4.36 to 4.37

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_repositorytasks.htm
to add documentation about the new support for source repositories.
Complements
- https://github.com/eclipse-equinox/p2/pull/875
=> Update documentation of p2.composite.repository ANT task

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
Source bundles will be included automatically.
=> Include e4.core.tools feature not its source

JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile
Follow-up on
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3078
=> [Build] Add missing version updates in release preparation pipeline

eclipse-platform-parent/pom.xml
I have now tested this with Equinox repo (that is the only one where it is currently enabled) and beside some edge cases it seem to work quite fine now.
The remaining issues are better addressed on concrete code samples that allow discussion of possible mitigates directly at the PR.
=> Enable Manifest Cleanup "removeUnusedDependencies"

cje-production/promotion/promoteSites.sh, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/cp-content.xsl, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml
This reverts commit c15c95578cefed05792fb28875a5665a70800ec7.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3188
=> Revert "[Build] Restore compressed content.xml for platform repository"

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- This is just for consistency with no actual bundle version changes.
=> Update ECF, EMF, and Orbit repositories to latest versions

eclipse.platform.releng/deploy-to-maven/SDK4Mvn.aggr
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3264
=> Add a dependency mapping rule to avoid bogus SWT fragment dependencies

eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/tips/jdt_tips.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/whatsNew/jdt_whatsnew.html
=> HTML validation fixes for jdt.doc.user

eclipse.platform.releng/features/org.eclipse.sdk.examples-feature/forceQualifierUpdate.txt
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3337
=> Touch org.eclipse.sdk.examples-feature

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_breakpoints.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_debug.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_expressions.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_adding.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_comparators.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_groups.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_java.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_processfactories.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_sourcelocators.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_status.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_ui.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_uiimages.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_launch_uishortcuts.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_model.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_presentation.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/debug_ui.htm
=> Convert "Debug" pages to HTML5

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_accessibility.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_commands_handlers.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_efs_resources.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_encoding.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_keyBindings.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_keyBindings_accelConfig.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_keyBindings_accelSet.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_keyBindings_actionDef.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_keyBindings_contexts.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_marker_support.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_markerhelp.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_markerresolution.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_markers.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_services.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_singleclick.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_undo.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_undo_ide.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/wrkAdv_workingsets.htm
=> Migrate "Advanced workbench concepts" to HTML5
