eclipse-platform/eclipse.platform.releng.aggregator

.github/dependabot.yml
As dependabot tries to figure submodules and failes if run on /
=> Enable dependabot for eclipse-platform-parent

cje-production/dockerfiles/centos-gtk3-metacity/8-gtk3/Dockerfile, cje-production/dockerfiles/centos-gtk3-metacity/8-swtBuild/Dockerfile
For [issue 29](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/29).
=> Updating centos 8 dockerfiles to use the latest 8.5 universal base image

production/testScripts/configuration/sdk.tests/testScripts/runtests.sh
Setting the rpm query to look for gtk3 since it's broken:
[https://ci.eclipse.org/releng/view/Performance%20Tests/job/ep423I-perf-lin64/68/console](https://ci.eclipse.org/releng/view/Performance%20Tests/job/ep423I-perf-lin64/68/console)
=> RPM fix for performance tests

.gitmodules
Removed the "rt" prefix from repos as these are no longer under RT TLP
for very long time.
Not adding "eclipse" as it's just redundant making paths longer.
Fixes #103
=> Migrate Equinox to GitHub

.github/workflows/licensecheck.yml
The `setup-java` action provides a [cache for Maven dependencies](https://github.com/actions/setup-java/#caching-packages-dependencies). Under the hood it uses [actions/cache](https://github.com/actions/cache) but it makes the configuration simpler.
=> [License-Check] use built in cache of setup-java action

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Refers to Maven artifacts directly instead of using them from
intermediate p2 repo created by us.
Part of #130 .
=> Update to Jetty 10.0.8 in prereqs file

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/rcp.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/rcp.sdk.product
Fix for #135 went too far and we ended up without org.eclipse.rcp.id.*
IUs in the repository.
=> Restore rcp.product and rcp.sdk.products in the repo.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
With Bug 568936 Orbit is dropping the old CVS sourced
bundles. This change splits out these two locations so
that while needed the older bundles can be collected
from the last place that CVS bundles were published.
@SDawley this is part one of the update. You can take this one, or wait until I complete the 2022-06 M1 build of Orbit to get the final URL for 2022-06 M1.
As of now the 2022-06 M1 for Orbit has the same contents (except for dropped CVS sourced bundles) as 2022-03 R.
=> Split CVS vs EBR sourced Orbit bundles #172

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Older sat4j will be removed later when dependent features and bundles
have migrated to use 2.3.6.
eclipse-equinox/p2#28
=> Add sat4j 2.3.6 to target

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
So bundles can start using it. Older references will be removed later
once all consumers have updated the necessary Required-Bundles or
feature.xml content.
See also eclipse-pde/eclipse.pde.ui#11
=> Add upstream ASM 9.3 to target-platform

.github/workflows/callFreezePeriodCheck.yml, .github/workflows/verifyFreezePeriod.yml, Jenkinsfile
This PR moves the Freeze-Period verification from the Jenkins build to a dedicated reusable workflow to get more detailed/clear PR checks as I have suggested on the [Mailing-Lists](https://www.eclipse.org/lists/platform-releng-dev/msg38299.html).
Each repository that requires the code-freeze check can add the following workflow-file
named `.github/workflows/verifyFreezePeriod.yml`:
```
name: Check Code Freeze Period
on:
pull_request:
branches: 
- 'master'
jobs:
check-freeze-period:
uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/verifyFreezePeriod.yml@master
```
This PR was originally developed at https://github.com/eclipse-platform/eclipse.platform.releng/pull/24
=> [RelEng] Add reusable verifyFreezePeriode workflow

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Add the org.osgi.util-bundles to the Eclipse-SDK prerequisite target, which is required for [#eclipse-equinox/equinox.framework/41](https://github.com/eclipse-equinox/equinox.framework/pull/41).
@tjwatson are you fine with the versions?
=> Add org.osgi.util-bundles from Maven-Central

eclipse-platform-parent/pom.xml
It's gone in 3.0.0-SNAPSHOT now.
=> Stop using deprecated appArgLine in tycho-eclipserun-plugin config

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Add more osgi bundles to the Eclipse-SDK prerequisite target, which are required for:
- https://github.com/eclipse-equinox/equinox.framework/pull/44
- https://github.com/eclipse-equinox/equinox.bundles/pull/26
@tjwatson are you again fine with the versions? I selected the latest ones again.
=> Add osgi-services, -app, -coordinator, -log bundles from Maven-Central

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Orbit 2022-06 M2 includes newer version of Jackson. Instead of
pointing at that newer version, consume Jackson directly from
Maven central as it is a proper OSGi bundle.
=> Eclipse 4.24 M2 Prerequisites: Orbit (fixup jackson)

cje-production/dockerfiles/ubuntu-gtk3-metacity/22.04-gtk3/Dockerfile
Added tigervnc-tools package to get vncpasswd
fixes #160
=> Add Ubuntu 22.04 test run in smoke tests #160

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
After some considerations we decided to not use the `org.osgi:org.osgi.service.application` dependency, so it is not used and can be removed again:
https://github.com/eclipse-equinox/equinox.bundles/pull/26#issuecomment-1112647217
=> Remove org.osgi:org.osgi.service.application

pom.xml
It's merged into pde. See
https://github.com/eclipse-pde/eclipse.pde/pull/39
=> Remove pde.build module from aggregator

.gitmodules, cje-production/streams/repositories_java18.txt, cje-production/streams/repositories_java18patch.txt, cje-production/streams/repositories_master.txt, eclipse.platform.releng.tychoeclipsebuilder/java18patch/pom.xml
https://github.com/eclipse-pde/eclipse.pde/pull/39 merged PDE build
into the PDE repo so we need to update the aggregator.
=> Update aggregator with move of PDE build modules

eclipse-platform-parent/pom.xml
In some cases, the skipAPIAnalysis=true property can be exported from
Ant into the Maven session or some parent (instead of current project
properties). This might be related to pom-less generating a static value
for this property.
The `skipAPIAnalysis` is useless here anyway because people who want a
flag to skip API Analysis can explicitly exclude the profile already.
=> Always check for API analysis when profile is on #174

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Currently shipped version 1.3.2 has a CVE
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1000031 .
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/250
=> Update to commons-fileupload 1.4

oomph/Platform.setup
The eclipse.platform.releng.prereqs.sdk folder contains a .gitignore
that ignored the .project file so we can create a .project file
automatically without dirtying the repository.
Also use absolute URIs to reference the child projects now that the
setup itself can be opened via a workspace project.
=> Ensure that a project containing the eclipse-sdk-prereqs.target is available in the workspace.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
They were locked at the old CVS repo as they were not available in the
new recipes way until very recently.
=> Switch some Orbit deps to latest I-build

oomph/Platform.setup
eclipse.platform.releng.prereqs.sdk folder is not done during bootstrap
but rather after the clone task as created the clone.
=> Ensure that the .project file created in the

cje-production/dockerfiles/centos-gtk3-metacity/7-gtk3/Dockerfile, cje-production/dockerfiles/centos-gtk3-metacity/8-gtk3/Dockerfile, cje-production/dockerfiles/centos-gtk3-metacity/8-swtBuild/Dockerfile, cje-production/dockerfiles/centos-gtk4-mutter/9-gtk4/Dockerfile, cje-production/dockerfiles/centos-gtk4-mutter/9-swtBuild/Dockerfile, cje-production/dockerfiles/opensuse-gtk3-metacity/15-gtk3/Dockerfile, cje-production/dockerfiles/ubuntu-gtk3-metacity/18.04-gtk3/Dockerfile, cje-production/dockerfiles/ubuntu-gtk3-metacity/20.04-gtk3/Dockerfile, cje-production/dockerfiles/ubuntu-gtk3-metacity/22.04-gtk3/Dockerfile
So Jenkins/OpenShift user can write there, see
https://docs.openshift.com/container-platform/3.9/creating_images/guidelines.html#use-uid
Should fix
https://github.com/eclipse-platform/eclipse.platform.swt/issues/108 as
newer WebKitGTK transitively needs to write in HOME folder.
=> Make $HOME open to the 'root' group

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Updates #171 
I noticed org.eclipse.emf.databinding.feature.group and org.eclipse.emf.databinding.feature.group were still set to 1.8 so I've updated them to 1.9.0.v20220516-1117 but asking for review from @merks to make sure they weren't left at 1.8 for a reason.
=> EMF Update for 4.24 M3

.github/workflows/verifyFreezePeriod.yml
As requested in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/206#issuecomment-1129257714 this PR implements a first minor improvement of the freezePeriod check workflow, by printing the queried calendar on the console.
So in case of a freeze period one can check manually when it has started and when it ends.
Additionally the script could be enhanced to print the end of the freeze period. This could be determined by querying the calendar in a loop until the first day is encountered that has no "stabilization" entry. Technically this would be feasible but I'm not sure if this is wanted. Usually the re-opening of the master is announced via the mailing-list, so I'm not sure what's the source of truth here. On the other hand, if this check is triggered on the …
=> Improve verifyFreezePeriod workflow

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
=> #298 Updating Comparator repo and eclipse run repo to 4.25-I-builds repo

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml, oomph/Platform.setup
It contains only cdc/osgiminimum env which are useless nowadays.
Removes the feature from Oomph setup file too.
Part of https://github.com/eclipse-pde/eclipse.pde/issues/102
=> Do not publish apitools.ee.feature

.gitmodules, pom.xml
Switches aggregator build to use the new merged equinox repository
instead of the old split ones.
See https://github.com/eclipse-equinox/equinox.bundles/issues/18
=> Change aggregator build to use merged equinox repo

JenkinsJobs/Builds/I-build.groovy, JenkinsJobs/Builds/Y-build.groovy
Reverts eclipse-platform/eclipse.platform.releng.aggregator#331
It exposed the following jdt.core bugs:
* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/147
* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/114
=> Revert "Switch aggregator I and Y builds to use Java 17"

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Use the latest Jars from Maven-Central for the following Apache Felix bundles:
- org.apache.felix.scr
- org.apache.felix.gogo.runtime
- org.apache.felix.gogo.command
- org.apache.felix.gogo.shell
This updates the version of the first two. For completeness I also added the latter two, but I'm a bit concerned if that can cause problems due to different build qualifiers respectively I expect that the previous variants will not be updated if available (but that should actually not be a problem then).
This is not intended to be merged after the master for the next Eclipse release cycle has opened and not before the upcoming Apache-Felix release. 
Although the versions are not yet final, we can discuss the change itself already.
=> Add felix.scr and felix.gogo.command/runtime/shell from Maven-Central

.gitignore, eclipse-platform-parent/pom.xml
and also simplify this check for 'api-generation' profile.
For the check ANT's 'resourcecontains'-condition is used:
https://ant.apache.org/manual/Tasks/conditions.html#resourcecontains
This avoids most of the `<skipAPIAnalysis>true<skipAPIAnalysis>` properties in poms, because if an API-analysis is not wanted the API-analysis nature and builder can simply be removed from the .project file.
In most cases where `<skipAPIAnalysis>true<skipAPIAnalysis>` is specified the nature+builder are already absent any ways (e.g. for test-plugins) and that property is only specified to avoid problems during build.
Automatically detecting based on the presence of the nature ensures consistently enabled/disabled API-analysis during build and in the UI.
Even more important allows to remove the …
=> Skip API-analysis automatically on absent api.tools.apiAnalysisNature

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Recently there [was a demand to use the bnd annotations](https://github.com/eclipse-equinox/equinox/issues/27) and there is a [open PDE issue to support the bundle annotations](https://github.com/eclipse-pde/eclipse.pde/issues/69), for both use cases we would need the bnd/osgi annotation available at the targetplatform.
=> Add the bundle and bnd annotations to the target platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Because of https://github.com/eclipse/tycho/issues/1133 causing errors
at building .target
=> Use Orbit bundle for commons-io

README.md
The proposed procedure to get started building only mentions how to clone the parent module, then goes on to show how to build the various submodules. However this will not work as the submodules have not been initialised and pulled. This merge request adds the missing step.
=> Add command to clone submodules

eclipse-platform-parent/pom.xml
Tracked in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/241
=> Update to ecj version 3.30.100.v20220717-1600

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml
Updating repository pom.xml to use jetty from maven central
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/396
=> Update Jetty version in R4_23_maintenance branch to 10.0.11

eclipse-platform-parent/pom.xml
That was missed during 4.25 version changes.
See comments on
https://github.com/eclipse-platform/eclipse.platform/issues/59
=> Updated 4.25 release name to 2022-09

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
There was on old version of BND annotations included and the version annotations are missing.
=> Use more recent BND annotations and include versioning annotations

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This reverts commit 6d78dba714504b6ddb0a917f000a0afa7b6efa48.
BouncyCastle uses jarsigner and certificates that are not rooted in
cacerts, resulting in Trust dialog showing up.
Revert to Orbit variant until p2 can better handle this case.
=> Revert "Remove bouncycastle originating from Orbit"

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testResults.php, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/index.template_java19.php, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/index.template_master.php
Found another reference to global_fp.php. We aren't currently generating fingerprint files so we should only check for performance.php which actually exists. Hopefully this will make performance tests accessible.
=> Remove global_fp check from index templates.

eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/publish.xml
xml links in https://download.eclipse.org/eclipse/downloads/drops4/I20220802-1800/performance/performance.php are broken. 
The php file includes an html file that's one directory up from it. The html is written to work from that location and it used to work when pulled into the php file but for some reason now the paths need to work from the php files directory. This should fix it.
=> Fix broken link in Performance Table

JenkinsJobs/Builds/I-build.groovy
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1618
Use CentOS 8 docker image with JDK11
=> Releng JIPP fails builds due to using Java 8

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Version shipped was 2.8.9. Changelog available at
https://github.com/google/gson/blob/master/CHANGELOG.md
=> Update Google GSON to 2.9.1

JenkinsJobs/Builds/Y-build.groovy
tracked in https://github.com/eclipse-jdt/eclipse.jdt/issues/30
=> Y-build move to java 11 based container

eclipse-platform-parent/pom.xml
Changes/removal/additions in the .gitignore file should not lead to a change of the artifact. Therefore the build-timestamp should not be influenced by a change of that file.
=> Ignore .gitignore for jgit-timestamp computation

eclipse-platform-parent/pom.xml
Since Tycho 3.0 the 'tycho-packaging-plugin' provides the property 'tycho.buildqualifier.format' to specify its 'format' config property. 
Instead of configuring a custom property ('qualifier.format') with the same purpose, use Tycho's default property for that. Using more defaults if possible is IMHO a good thing.
When searching my platform-aggregator workspace I found no other references to `qualifier.format` than those adjusted in the platform-parent pom.
@akurtakov any objections?
=> Use Tycho-3.0's 'tycho.buildqualifier.format'-property instead of custom property

.github/workflows/verifyFreezePeriod.yml
With the dots being printed one that clicks on the printed link opens an invalid URL.
=> [Freeze-Check] simplify URL and remove the dots

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This version updates CLDR to 41 and adds Unicode 14 support.
=> Update ICU4J to version 71.1

oomph/Platform.setup
With the following two PRs the exclusions in the targlat of the Platform-Oomph-setup can now be removed.
- https://github.com/eclipse-platform/eclipse.platform/pull/78
- https://github.com/eclipse-platform/eclipse.platform/pull/110
=> Remove exclusions of now fixed projects from Platform-Oomph-setup

oomph/Platform.setup
This partially reverts the project reference relativization of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/474, which caused a `StackOverflowError`, as written in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/474#issuecomment-1214138487.
@merks I'm going to merge this right now. Maybe you want to have a look at this and debug it. Since the message was that there was an error while displaying an error, I suspect that this change was not correct.
=> Revert relativation of project references

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
These are published under groupdId org.eclipse.jetty.orbit and have jar signatures that use very old certificates that are no longer rooted in a modern Java's cacerts while Orbit provides versions with newer signatures. This applies specifically for com.sun.el and
org.apache.jasper.glassfish.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/438
=> Don't use old Orbit bundles that Jetty published to Maven 

oomph/PlatformSDKConfiguration.setup
The Platform-Resources repository was merged into Eclipse-Platform via:
https://github.com/eclipse-platform/eclipse.platform/pull/76
=> Accommodate the merge of resources into platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This allows a finer control of the dependencies, and also avoid
duplicated artifacts in different versions.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/489
=> Do not add transitive Maven deps to .target

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#534 as there is nothing in the repo published until we get good build.
=> Revert "Updating comparator repo and eclipse run repo to 4.26-I-builds.  "

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Reverts eclipse-platform/eclipse.platform.releng.aggregator#477 as it was reverted so it can land early in 4.26 stream.
=> Revert "Revert "Update ICU4J to version 71.1""

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Finalizers are removed from java 18 and this latest version adapts this change
=> Update jna version to 5.12.1

eclipse-platform-parent/pom.xml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#581
Reverting this one as this is causing PR validation to fail
=> Revert "Moving to daily ecj snapshot"

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
There are IP issues with parts of bcprov https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/3008#note_1020135 therefore be explicit to not consume the bcprov from Maven Central
For now the Maven central one wasn't ending up in the p2 output, so AFAICT this makes no difference to what is published.
=> Remove bcprov from Maven Central from target platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
bcprov is now IP-cleared from MAven Central!
This reverts commit f503ae14579b9d418829b93abf5752453c380ab3.
=> Revert "Remove bcprov from Maven Central from target platform"

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Use slf4j from upstream Maven instead of Orbit

eclipse-platform-parent/pom.xml
@akurtakov WDYT? I'd like to use that in P2 as an incubator and it seems better to be configured in the parent so it can be enabled by a simple property than to be override the whole execution in the child modules.
=> Add two new properties for modules to control pom descriptor

eclipse-platform-parent/pom.xml
When deploying artifacts to maven it is common to provide also javadoc artifacts. This adds a profile that could be used in sub-projects to accomplish this.
I was able to use this for equinox to generate javadoc artifacts, but though it might be more appropriate to have this in the master so other projects might easily reuse that as well. This also will allow us to catch javadoc errors earlier than with the current "doc-build".
=> Add a profile to generate and attach javadoc artifacts

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This version fixes CVE
https://github.com/jhy/jsoup/security/advisories/GHSA-gp7f-rwcx-9369
=> Update to JSoup 1.15.3

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Makes sure target platform is not using older version than Orbit. See https://github.com/eclipse-equinox/p2/issues/153 for details.
=> Update target platform to bouncycastle 1.72

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/Releng/collectResults.groovy, JenkinsJobs/Releng/collectYbuildResults.groovy
Fix performance test location in I-builds.
Change the collect result jobs to use JOB_BASE_NAME since JOB_NAME includes folder.
Tracked in #568
=> Fix performance test location in I-builds

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes the following CVEs:
https://www.cvedetails.com/cve/CVE-2022-40146/
https://www.cvedetails.com/cve/CVE-2022-38648/
https://www.cvedetails.com/cve/CVE-2022-38398/
=> Update Batik to 1.15

JenkinsJobs/Builds/AddToPComposite.groovy, JenkinsJobs/Builds/markStable.groovy, JenkinsJobs/Builds/markUnstable.groovy, JenkinsJobs/Cleanup/cleanupDLsite.groovy, JenkinsJobs/Cleanup/cleanupReleaseArtifacts.groovy, JenkinsJobs/Cleanup/dailyCleanOldBuilds.groovy, JenkinsJobs/Releng/CBIaggregator.groovy, JenkinsJobs/Releng/PublishJDTtoMaven.groovy, JenkinsJobs/Releng/PublishPDEToMaven.groovy, JenkinsJobs/Releng/PublishPlatformToMaven.groovy, JenkinsJobs/Releng/checkCompositesValidity.groovy, JenkinsJobs/Releng/cleanupReleaseArtifacts.groovy, JenkinsJobs/Releng/collectResults.groovy, JenkinsJobs/Releng/createGenericComposites.groovy, JenkinsJobs/Releng/createMaintenanceBranch.groovy, JenkinsJobs/Releng/makeVisible.groovy, JenkinsJobs/Releng/newStreamRepos.groovy, JenkinsJobs/Releng/renameAndPromote.groovy, JenkinsJobs/Releng/tagEclipseRelease.groovy, JenkinsJobs/Releng/updateIndex.groovy, JenkinsJobs/YBuilds/collectYbuildResults.groovy
Currently the jobs are created and set to use the first SSH agent on the list, but using the IDs set in jenkins instead of the name should fix that.
=> Update sshAgent to use IDs so jobs are configured correctly.

eclipse-platform-parent/pom.xml
It's used for running tests in jdt.core and jdt.debug but all at different version.
This is first step towards standardizing.
=> Manage version of maven-toolchains-plugin.

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
The [Metatype Service Specification](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.metatype.html) defines a set of [annotations](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.metatype.html#service.metatype-metatype.annotations) to allow defining possible configuration options of a service as code.
These annotations are only retained at class level and can the used at build time to generate the proper XML definition, we should enable PDE users to use these annotations as well, so this information can then be used for example in Tycho or BND builds.
=> Add metatype annotation to target

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
m2eclipse already uses BND for a while to generate missing manifest for maven dependencies and PDE can (re-)use BND as well for different tasks.
This also moves the bnd annotations to the new BND section and adds org.osgi.service.repository API bundle as it is a dependency of BND lib.
@akurtakov WDYT? 
FYI @HannesWell
=> Add BND lib to the target

Jenkinsfile
As discussed in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/653#issuecomment-1306869654 this PR changes the Jenkins-Pipeline of the `eclipse.platform.releng.aggregator` to deploy the `eclipse-platform-parent/pom.xml` and `eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target` in the beginning of the master-branch build of this repo.
This makes the following two Jenkins jobs obsolete and also speeds up the deployment of the mentioned files but at the same time reduces the number of deployments:
- https://ci.eclipse.org/releng/job/deploy-eclipse-platform-parent-pom/
- https://ci.eclipse.org/releng/job/deploy-eclipse-sdk-target-pom/
From looking at those jobs it looks like nothing more has to be done. Maybe only some credentials are missing, but we …
=> Deploy platform-parent pom and platform-releng target in 'master' build

Jenkinsfile
As suggested in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/657#issuecomment-1309274976, a follow up to automatically have maintenance branches prepared to deploy the `eclipse-platform-parent/pom.xml` and `eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target` in the beginning of the build.
=> Deploy platform-parent-pom/eclipse-sdk-target in 'maintance' build too

JenkinsJobs/Releng/collectResults.groovy
I had previously added a line to disable the new Collect Results job by default while it was broken and that is no longer needed.
=> Enable collectResults by default.

eclipse.platform.releng.tychoeclipsebuilder/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/661
=> Force PGP signatures of old Orbit bundles unsigned in LST Java versions

JenkinsJobs/Releng/collectResults.groovy, cje-production/scripts/publish.xml, scripts/collectResultsLocal.sh
Should address:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/680
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/cje-production/mbscripts/mb300_gatherEclipseParts.sh already passes -DEBuilderDir to helper.xml
=> Fix: Updating publish.xml to use a variable instead of relying on current directory

JenkinsJobs/Releng/collectResults.groovy, cje-production/scripts/collectTestResults.xml, scripts/collectResultsLocal.sh
I commented out an xml download in collectTestResults.xml because I did not know what it does.
Turns out it is used for the test summary table. 
I've updated collectResults to get the xml again and added a comment stating why it's still needed.
=> Fix for #668

JenkinsJobs/Releng/createMaintenanceBranch.groovy
The new parameter name is --set-upstream-to.
Remove useless parts of the script while at it.
=> Fix git branch --set-upstream no longer recognized

JenkinsJobs/Releng/deployPlatformParentPom.groovy
For #701 
The job hadn't been converted to a groovy file yet so made it and added the 4.26 maintenance branch.
The second job was identical so I saw no reason to add it.
=> Add deployPlatformParentPom.groovy

JenkinsJobs/Releng/CBIaggregator.groovy, JenkinsJobs/Releng/PublishJDTtoMaven.groovy, JenkinsJobs/Releng/PublishPDEToMaven.groovy, JenkinsJobs/Releng/PublishPlatformToMaven.groovy, JenkinsJobs/Releng/makeVisible.groovy, JenkinsJobs/Releng/renameAndPromote.groovy
Credentials now named secret-subkeys.asc for PDE/JDT/Releng, and using the correct one instead of JDT keys for everything. 
Moved the tagging job to run after the promotion job, since for GA release make visible is run later.
=> Fix maven publish jobs. Move release tagging to after promotion.

eclipse-platform-parent/pom.xml
The `tycho-apitools-plugin` provides a mojo now to generate the description file, this should be faster and easier to use/understand than the ANT calls.
Lets see if this causes any issues...
=> Use the tycho-apitools-plugin to generate the api description file

cje-production/scripts/checkComposites/checkComposites.sh
Only 4.27 and 4.27-I-builds exist and are in development so nothing else should be checked.
=> Fix checkComposites script

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Moves targetJRE to Java 17 as this version requires it. First step towards
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/648
=> Update target platform to RedDeer 4.4.0

eclipse-platform-sources/sources.xml
Should have been done long ago when repos were merged.
=> Properly exclude native libs from source tarball

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
So changes due to Orbit rebuilds are separated from dependency updates.
=> Move to latest Orbit I-build

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
A more recent javax.servlet.jsp from Maven-Central was added in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/407 so the old one from Eclipse-Orbit is probably obsolete.
But the build will tell if not.
=> [SDK-TP] Remove javax.servlet.jsp from Eclipse-Orbit

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
The package names are still javax.el in older version, so keeping the package name will facilitate a milestone.
=> Use older jakarta.el version

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
To allow building against it.
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/136
=> Add Lucene 9.4.2 to target platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/pom.xml
to progressively replace Orbit's org.apache.jasper.glassfish
=> Add org.glassfish.web.javax.servlet.jsp to TP

README.md
This has been the case for a while now but readme was not adjusted.
=> Update Readme with the fact Java 17 is required for the build

eclipse-platform-parent/pom.xml
Corrected the p2 repo url from https://download.eclipse.org/eclipse/updates/R-4.26-202211231800 to https://download.eclipse.org/eclipse/updates/4.26/R-4.26-202211231800
=> Corrected the p2 repo url

oomph/Platform.setup
Use webtools/CI/3.29.0/I-latest repo, 3.28.0 is gone now
Fixes https://github.com/eclipse-platform/.github/issues/83
=> OOmph fails "No repository found webtools/CI/3.28.0 (#83)

JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy
tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/756
=> Update the java paths using 8dot3 notation

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This reverts commit 644c8ab54506ec0c1333d74eb3ad7a0c37abe3c3.
This commit breaks SDK building with error
```
[ERROR] Failed to execute goal
org.eclipse.tycho:tycho-p2-repository-plugin:4.0.0-SNAPSHOT:assemble-repository
(default-assemble-repository) on project eclipse.platform.repository:
Could not assemble p2 repository: Mirroring failed: Messages while
mirroring artifact descriptors.: [Failed to transfer artifact packed:
osgi.bundle,org.jdom.source,1.1.1.v201101151400.: [Download of
osgi.bundle,org.jdom.source,1.1.1.v201101151400 failed on repository
file:/resolution-context-artifacts@%252Fdata%252F4x_platform%252Feclipse.platform.releng.aggregator%252Feclipse.platform.releng.tychoeclipsebuilder%252Feclipse.platform.repository.
```
See discussion on …
=> Revert "Replace jxpath by upstream one from Maven Central"

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This reverts commit cd659acf75ce18b5ee79dfe0a7bdf1fa0f9a9e82.i Now that jxpath isn't directly included anymore (comes transitively) and Tycho issues are resolved, we can finally re-try this.
=> Revert "Revert "Replace jxpath by upstream one from Maven Central""

eclipse-platform-parent/pom.xml
Prep work for https://github.com/eclipse-platform/eclipse.platform.ui/pull/527 due to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/585
=> Update to ECJ from M1

JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy
- removed quotes around set JAVA_HOME, that broke java startup from Ant
- removed duplicated PATH entries (cleanup only)
See https://github.com/eclipse-platform/eclipse.platform.releng/issues/190
=> Trying to fix Windows test execution (#190)

JenkinsJobs/SmokeTests/smoke_test_arm64.groovy, JenkinsJobs/SmokeTests/smoke_test_ppcle.groovy
Formatting resulted in an extra space at the top of the script in Jenkins which broke the arm64 and ppcle builds.
=> Fix extra line in arm64 and ppcle smoke tests

eclipse-platform-parent/pom.xml
This migrates some javadoc config that is generic enough from equinox to the platform parent.
=> Migrate the javadoc config from equinox > platform-parent

JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java19.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java20.groovy, JenkinsJobs/YBuilds/Y_unit_cen64_gtk3_java17.groovy, JenkinsJobs/YBuilds/Y_unit_cen64_gtk3_java19.groovy, JenkinsJobs/YBuilds/Y_unit_cen64_gtk3_java20.groovy
Increased memory requested by Linux container to avoid container startup issues / aborted jobs on Linux.
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2478
=> Fix for "Releng JIPP not connecting to svc cluster"

eclipse-platform-parent/pom.xml
Temporary disable as we are late in 2022-03 stream and a some things are still work in progress on Tycho and PDE side.
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/853 for details.
=> Stop generating OSGi headers from source

JenkinsJobs/SmokeTests/StartSmokeTests.groovy
1. Added Java 19 ppcle job (Centos 8.x ppc64le Java19')
2. Java 20 Smoke Test Job(Ubuntu 22.04 Java20,Opensuse Leap Java20,Centos 9.x Java20,Centos 8 arm64 Java20).
3. Added Email in Different Failure and success.
Fixes #868
@sravanlakkimsetti Please review the PR
=> Adding SmokeTest for Java 19 ppcle and Java 20 #868

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Multiple CVEs are fixed compared to 1.8.0 used and it removes one more dependency from ancient Orbit that had to special treated to get signed. Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/870
=> Update beanutils to 1.9.4

eclipse-platform-parent/pom.xml
If running a build, one can specify `-Pvb` to automatically bump the version(s) of plugins that have changed.
=> Add a profile to bump versions

cje-production/mbscripts/mb500_createRepoReports.sh
This is a Temurin-derived JRE and is same JRE that is used with all the SimRel products.  Using this URL avoids rate limits that often affect direct Temurin JREs.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/870
=> Run the p2analyze report using the latest JustJ Java 17 JRE

Jenkinsfile
This adds a new condition where poms are deployed when the branch start with the prefix 'prepare_R' and skip the build in such case.
@akurtakov @sravanlakkimsetti what do you think? The idea is that with some automation one can create the `prepare_R...` automatically (I'll prepare a PR for this as well), then a build is triggered and the pom is deployed so it could be used by other steps soon. As other repos needs to be adjusted to use the new master, a build is skipped in this case as this can't work anyways...
=> Deploy the poms also on branches that are preparing a release

.github/workflows/prepareRelease.yml
This workflow is triggered by the milestone creation and automatically performs the updates of the master pom and target to be prepared for usage in the submodules and creates a PR. This PR will then trigger the deploy of the changed xmls, so it can be used immediately to adjust the sub-projects.
FYI @akurtakov @sravanlakkimsetti this is the workflow mentioned here:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/875
It then creates a PR automatically once the milestone is created and the description of the milestone includes "Release" in the description like this:
- https://github.com/laeubi/eclipse.platform.releng.aggregator/pull/7
If you agree, I'd like to merge this (together with the Jenkins file) and create a new milestone 4.28 in this repository (we …
=> Add a workflow to prepare the next release cycle

.gitmodules, cje-production/streams/repositories_master.txt, pom.xml
eclipse.platform.ui.tools was merged into eclipse.platform.ui so we can remove it from the aggregator build.
=> Removes eclipse.platform.ui.tools from aggregator build

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
=> Update Orbit to permanent R url for 4.27

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list.txt
None but changing the version for the sake of readability although I believe this is useless step nowadays.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/941
=> Cleanup approved API changes

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Contains some useful bnd-plugins to read repositories ... as I plan to enhance BND support in PDE this will be required then.
=> Add biz.aQute.repository to the target for usage by PDE

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
With https://github.com/eclipse-pde/eclipse.pde/pull/479 the PDE-spies have been moved into a dedicated feature, which has to be added to the eclipse/updates p2-repo.
Can anybody verify that with this change the new feature ends up in the next I-builds repo at https://download.eclipse.org/eclipse/updates/4.28-I-builds ?
I don't think we should add it to the o.e.sdk feature.
=> Add o.e.pde.spies feature to eclipse/updates repo

eclipse-platform-parent/pom.xml
Preliminary step for Eclipse requiring Java 17 for 2023-06 release
=> Use JavaSE-17 EE for eclipserun tycho plugin

eclipse-platform-parent/pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/960
=> Deploy ecj compiler from 4.27 GA and use it for 4.28 M1 build

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy
With https://github.com/eclipse-platform/eclipse.platform.swt/pull/514 SWT-natives are build as part of the SWT master-branch build.
@SDawley I'm not sure if it is sufficient to change the scripts here or if they have to be deployed to the Releng Jenkins in order to take effect? Are there more places that have to be adjusted?
=> Remove SWT-Natives build step from I/Y-builds pipelines

cje-production/dockerfiles/buildDockerImages.sh, cje-production/dockerfiles/pushDockerImages.sh
=> Remove Ubuntu 18/20 from aggregator scripts too

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#951
With https://github.com/eclipse-platform/eclipse.platform.releng/pull/212 the new pde.spies feature is included in the `o.e.sdk` and therefore is transitively included into the eclipse-sdk repo.
=> Revert "Add o.e.pde.spies feature to eclipse/updates repo"

cje-production/scripts/checkComposites/checkComposites.sh
=> Fix checkComposites

eclipse-platform-parent/pom.xml
The `tycho-apitools-plugin:generate` mojo already checks if a project has a manifest file and if not silently skips its execution. Therefore it is not necessary to guard it with a profile activated with the condition 
`<file><exists>META-INF/MANIFEST.MF</exists></file>`.
Mojo code:
https://github.com/eclipse-tycho/tycho/blob/757d125589b36f68bd553db9140803ad8c9bcef1/tycho-apitools-plugin/src/main/java/org/eclipse/tycho/apitools/ApiFileGenerationMojo.java#L85-L86
See also https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/973.
From the discussion in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/419#issuecomment-1246575930 I wonder if the generate-mojo should skip its execution if the .project files does not have the …
=> Move 'tycho-apitools-plugin:generate' execution to build/plugins section

eclipse-platform-parent/pom.xml
Since the transition to Java 17 certain things previously handled as a warning are now hard errors in the javadoc tool what currently makes the javadoc profile quite unusable.
=> Fix tag definition and make the build more quiet

eclipse-platform-parent/pom.xml
Current Version :
org.eclipse.jdt.core.compiler.batch_3.34.0.v20230405-0323
=> Update cbi-ecj-version from M1

RELEASE.md
At the moment it seems unclear when the master branches will reopen after a freeze period.
After the RC freeze period there is a dedicated mail that announces the reopening of the master branch after all preparation work has completed. As far as I understand there is no preparation work form M1 to M2 and therefore the master branch is open as as soon as M1 has been officially released/declared.
Therefore it would be good if the mail to announce the M1 release will also mention that the master branch is now open again.
In case there wont be a M1 freeze in the future this section can be removed again (https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/discussions/863).
@MohananRahul, @sravanlakkimsetti can you please check if that is correct?
=> Mention reopening of the master branch after freeze week

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy
The `eclipsecbi/jiro-agent-centos-8-jdk11` image is no longer supported and uses an outdated remoting version. It was only used to test for regressions before the `eclipsecbi/jiro-agent-centos-8` image was switched to JDK11 by default.
Please also fix this in any other repo that still uses the `eclipsecbi/jiro-agent-centos-8-jdk11` image.
=> Use eclipsecbi/jiro-agent-centos-8 image instead of *-jdk11 image

README.md
The mentioned path in the readme does not exits and results seem to be moved under eclipse.platform.repository now.
@akurtakov can you verify this? At least for my local build I did not find the mentioned location but the proposed new one here where some products are located.
=> Adjust the path of the results

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Refs: https://github.com/eclipse/jetty.project/security/advisories/GHSA-p26g-97m4-6q7c
/CC @sravanlakkimsetti @MohananRahul
=> meta: upgrade jetty server version

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Refs: https://github.com/eclipse/jetty.project/security/advisories/GHSA-p26g-97m4-6q7c
/cc @sravanlakkimsetti @MohananRahul
=> meta: upgrade jetty version (4.8)

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Refs: https://github.com/eclipse/jetty.project/security/advisories/GHSA-p26g-97m4-6q7c
/cc @sravanlakkimsetti @MohananRahul
=> meta: update jetty version (4.7.3)

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Refs: https://github.com/eclipse/jetty.project/security/advisories/GHSA-p26g-97m4-6q7c
/cc @sravanlakkimsetti @MohananRahul
=> meta: bump jetty version (4.23)

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml
Use the javax namespace bundles provided by Jakarta.
Remove all javax bundles provided by Orbit.
Remove the unused javax.xml bundle, the modern JREs provide the contained packages by default.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056
Additionally configure the `tycho-p2-repository-plugin` to include all sources. This allows to remove the javax-bundles from containing features (see https://github.com/eclipse-platform/eclipse.platform.ui/pull/745) and at the same time to keep the main artifacts (which are pulled in as transitive dependencies) plus their sources in the created p2-repo for the Eclipse SDK.
=> Add javax.inject/annotation provided by Jakarta from Maven-Central and include all sources in Eclipse SDK repo

.github/workflows/mavenBuild.yml
- Update mavenBuild workflow to use maven 3.9.1
- Ignore Maven test errors and failures in mavenBuild workflow
This allows the Maven build check itself to pass and have a green check mark in the GH UI if there are only test errors/failures. The test errors/failures themself are still reported via the 'Publish Test Results' checks that is shown as failure if there are test failures/errors. This setup simplifies to distinguish between only test errors/failures in the build and more severe failures like compilation failures.
=> Use Maven 3.9.1 in mavenBuild workflows

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
Follow up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1057 to remove the now unused javax.xml bundle, the modern JREs provide the contained packages by default.
Also revert explicit inclusion of jakarta.inject/annotation bundles in eclipse.platform.repository, because they will be transitively included from now on.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056
This probably requires the currently running I-build to succeed first (see https://github.com/eclipse-platform/eclipse.platform.common/pull/145#issuecomment-1535932554).
=> Remove all javax bundles provided by Eclipse-Orbit

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Required for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/981.
@tomaswolf FYI
=> Update Apache SSHD OSGi to 2.10.0

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Since version 2.0.7 the slf4j.api bundle exports the user-api package 'org.slf4j' in version 2.x.y and 1.7.36.
This allows to also use libraries, which are programmed against slf4j-1 and import the package 'org.slf4j' with an exclusive upper bound of 2 like '[1.7,2)', with the slf4-api version 2 in OSGi environments.
According to SLF4J the client/user facing API is compatible with slf4j-1:
- https://www.slf4j.org/faq.html#changesInVersion200
- https://www.slf4j.org/faq.html#compatibility
Only the logging-backends/bindings/providers have match the requirements of the specific slf4j version.
The corresponding SLF4J issue and change is
- https://jira.qos.ch/browse/SLF4J-579
- https://github.com/qos-ch/slf4j/pull/331
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/ …
=> Update the Eclipse SDK TP's slf4j-api to 2.0.7 and remove 1.7 version

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fix for both eclipse/ecf#26 and eclipse/ecf#27 are included in 3.14.38.
Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/997
=> Update ECF to 3.14.38

eclipse-platform-parent/pom.xml
This version contains ECJ changes made after M3 build, no other ECJ changes are planned as of today.
=> Update ECJ to RC1 version from I20230524-0600 (same as I202305250350)

JenkinsJobs/Builds/AddToPComposite.groovy, JenkinsJobs/Builds/markStable.groovy, JenkinsJobs/Builds/markUnstable.groovy, JenkinsJobs/Releng/collectPerfResults.groovy, JenkinsJobs/Releng/collectResults.groovy, JenkinsJobs/YBuilds/collectYbuildResults.groovy, cje-production/cleaners/cleanupNightlyRepo.sh, cje-production/mbscripts/mb620_promoteUpdateSite.sh, cje-production/promotion/makeVisible.sh
Should fix SDK build fails after I20230609-1800.
Looks like some environment or build script change finally caused latest 4.28 SDK builds to be used for building 4.29, and antRunner application requires Java 17 since 4.28.
See https://github.com/eclipse-platform/eclipse.platform.releng/issues/240
=> Updated build paths in scripts to use Java 17

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Changes Done in 4.28 Maintenance branch Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1110
@sravanlakkimsetti
=> Update R4_28 maintenance branch with release version for 4.28+ changes

.github/actions/maven-license-check-action/action.yml, .github/actions/maven-license-check-action/licenseCheckMavenSettings.xml, .github/workflows/licensecheck.yml, .github/workflows/mavenLicenseCheck.yml
As discussed in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1163#issuecomment-1599258027 this PR copies the re-usable license-check GH workflows from https://github.com/eclipse/dash-licenses/tree/master/.github (with the state of https://github.com/eclipse/dash-licenses/pull/247) into this repository in order to have the necessary fixes faster.
In my opinion this is only a temporary solution and the workflow is still best placed at `eclipse/dash-licesens`, but until that project is more active we maintain the copy of the workflow here in order to use it for eclipse-platform (or others that need it). But he ultimate goal should be to make `dash-licenes` more active so that we can consume it from there and can revert this again. So everybody that want's to …
=> Copy re-usable license-check GH workflows from eclipse/dash-licenses

oomph/Platform.setup
After https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1180 the excludedWorkingSet of the Platform Releng Aggregator working set seem to be off by one: It was `@setupTasks.3` but probably should have been `@setupTasks.2`.
This caused errors when I opened the Platform setup.
To make this more robust against future changes I added ids to all working-set task and changed the exclusion property to use that reference as @merks advocated somewhere else in the past.
=> [Setup] Fix incorrect Working-Set task index and assign IDs to WS-tasks

eclipse-platform-parent/pom.xml
Currently it fails with "pattern matching in instanceof is not supported in -source 11" or similar in builds.
=> Force Java 17 source for javadoc profile

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/forceQualifierUpdate.txt
So that the changes from https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/278 are picked up to fix https://github.com/eclipse-platform/eclipse.platform/issues/561.
=> Enforce qualifier update to pick-up JDT extension-point doc fixes

.gitignore
Multiple doc-html directories shown as untracked after SDK build:
Untracked files:
(use "git add <file>..." to include in what will be committed)
eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/samples/org.eclipse.compare.examples.xml/
eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/samples/org.eclipse.compare.examples/
eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/samples/org.eclipse.swt.examples.launcher/
eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/samples/org.eclipse.swt.examples.ole.win32/
eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/samples/org.eclipse.swt.examples.views/
eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/samples/org.eclipse.swt.examples/ …
=> Ignore generated/copied samples doc-html directories

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1199
=> Update the target platform for Orbit m2

oomph/Platform.setup
This PR does two things:
1. Add eclipse-sdk-prereqs.target to platform.releng.aggr Targlet
And explicitly import `eclipse.platform.releng.prereqs.sdk` to ensure the `eclipse-sdk-prereqs` target is available in the workspace when the targlet-task is executed.
2. Exclude releng.aggregator sub-modules from releng.aggr Targlet
This prevents the imports of large parts of the SDK even if their setups are not included in the workspace setup.
For example I have eclipse-platform base, ui, releng.aggregator and equinox and p2 in one workspace but not PDE and JDT (I have them in a separate one). Without the exclusion I then get many projects from PDE and JDT imported, when I also apply the releng.aggreator setup to this workspace.
=> [Setup] Add eclipse-sdk-prereqs.target to platform.releng.aggr Targlet and exclude releng.aggregator sub-modules

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.sdk.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
This allows the slf4j-api bundle to find the nop binding and thus prevents error messages about missing bindings.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1094
@jonahgraham I'm a bit unhappy that the slf4j.nop bundle also has to be auto-started, but unfortunately spi-fly only considers bundles that are in STARTING or ACTIVE (i.e. have been started successfully).
Equinox sets bundles with `Bundle-ActivationPolicy: lazy` automatically in the STARTING state. So at least for Equinox a solution would be to add `Bundle-ActivationPolicy: lazy` to the slf4j-providers (i.e. slf4j.nop, slf4j.simple, logback, ...).
Alternativly one could ask in Apache aries to also consider bundles in resolved state, but I guess they have a reason for that behavior.
If we …
=> Add silent slf4j-simple to Platform/SDK-products and auto-start Aries SPI Fly and slf4j-simple

.project
This is particularly relevant to avoid eclipse-sdk-prereqs.target appearing twice in the workspace.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1197
=> Filter out the workspace content of folders that are nested projects

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.28/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.29/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.29/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.29/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_29_porting_guide.html
Add missing migration files that have been merged into R4_29 maintenance branch in #1290 also to master branch.
See https://github.com/eclipse-platform/eclipse.platform/issues/668
=> Missing migration files for the 4.29rc2a

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1328
Changing the I-Builds from 4.29 to 4.30 for publishing to maven central
cc/ @sravanlakkimsetti 
@MohananRahul
=> changing the I-Builds to 4.30 for maven publishing.

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1349
=> Remove ancient org.w3c.* bundles from the target platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Fixes:
* CVE-2022-42890
* CVE-2022-41704
/cc @akurtakov
=> backport: Update Batik to 1.16

eclipse.platform.releng.tychoeclipsebuilder/pom.xml
Use the bc signer because it's much faster.
Use <skipIfJarsignedAndAnchored> to avoid a <forceSignature> list; this will PGP sign any jar that's not considered to be signed and anchored, so it handles the jce-signed jars as well as any jars with old no-longer-supported weak jar signatures.
=> Simply gpg signing

eclipse.platform.releng/bundles/org.eclipse.releng.tests/src/org/eclipse/releng/tests/BuildTests.java
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1349
=> Fix BuildTests.testPluginFiles() to ignore org.eclipse.orbit

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt
Continuation of
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1105
=> Fix javadoc generation after search.core being split

oomph/Platform.setup
Create a .project file for infocenter-web so that it's imported into the workspace; this file is ignored by .gitignore so this doesn't dirty the clone.
=> Fix redirection problems with the root Platform.setup

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/jdtOptions.txt
Continuation of
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/725cacd808359189e38bda85b416ed80d03bda22
=> Fix finding search.core classes for javadoc

eclipse-platform-parent/pom.xml
There are many warnings in the platform builds in the following form:
'build.plugins.plugin.version' for
org.codehaus.mojo:build-helper-maven-plugin is missing
this is injected automatically by tycho-build-extension but as the extension can't know the desired version it has to be configured in the configurator-pom (or parent like here),
=> add build-helper-maven-plugin to pluginManagement section

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
So we can start consuming the new httpclientjava and getting rid of httpclient5.
The snapshot repo must be replaced by release one as soon as ECF provides a release, before Eclipse 4.30.M3.
See https://github.com/eclipse-equinox/p2/pull/206
=> Temporary use ECF snapshots

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/buildDoc.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/plugin.xml
Add references to new org.eclipse.search.core bundle
Follow-up of
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1054
=> Adapt to moved org.eclipse.search.textEngingSearch

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This was needed only for RedDeer and that dependency is already removed.
=> Remove jackson from the target platform

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt, eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/equinox-sdk.product, eclipse.platform.releng/features/org.eclipse.sdk/feature.xml
https://github.com/eclipse-equinox/p2/issues/205
=> Replace ECF's filetransfer.httpclient5 with filetransfer.httpclientjava

.github/workflows/mavenBuild.yml
The toolchains.xml generated by the setup-java GitHub action has '8' as 'version' value for the Java-1.8 JDK and therefore the tycho-compiler-plugin does not match it when has 'useJDK=BREE' configured for a Plugin with BREE JavaSE-1.8.
Therefore explicitly set the 'id' of each jdk-toolchain to match the corresponding BREE identifier so that the tycho-compiler-plugin can find it via this secondary way.
=> [GH] Explicitly specify mvn-toolchain-id for setup JDKs to match BREEs

.github/workflows/codeQLworkflow.yml
Follow-up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1399
=> [GH] Explicitly specify mvn-toolchain-id for setup JDKs to match BREEs in codeQLworkflow.yml

cje-production/mbscripts/mb220_buildSdkPatch.sh
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1435 
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1395
=> Disable baseline validation/replace when building the compiler-compiler

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Follow-up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1370
@akurtakov I assume we can merge this now, even in M1 week since this should not have an external effect, can't we?
=> Place jakarta-EE annotation bundles in one target location

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
https://github.com/eclipse-platform/.github/issues/155
=> Use org.glassfish:jakarta.el instead of org.glassfish:javax.el

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Another step towards
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1384
=> Add Jetty EE8 bundles to target platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Caused by new launcher binaries
https://github.com/eclipse-equinox/equinox.binaries/commit/e186a1b573faabb9ad5ec5d9a2b4762b8074cc05
=> Touch to fix comparator errors

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Reverts eclipse-platform/eclipse.platform.releng.aggregator#1414 as this is completely different patch from what was ment.
=> Revert "Touch to fix comparator errors"

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml
Should be the last part to land for
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1384
=> Remove Jetty 10 from target platform

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt
Tracked in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1384
=> Fix platform javadoc build with Jetty 12

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/removals.html
Moving classic search and MultiPageEditor to removed section.
=> Document removals in 4.30

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
The Import-Package version ranges already have been widened in https://github.com/eclipse-pde/eclipse.pde/pull/781 to work with the new version too.
=> Update BND-lib to 7.0.0

.mvn/maven.config, Jenkinsfile, cje-production/P-build/mb220_buildSdkPatch.sh, cje-production/mbscripts/mb220_buildSdkPatch.sh, eclipse-platform-parent/pom.xml, pom.xml
The property 'project.build.sourceEncoding' is already defined in the eclipse-platform-parent/pom.xml used as parent for all modules, thus it is not necessary to explicitly add it in the Jenkinsfile.
Moving the definition of the 'aggregatorBuild' property to the maven.config simplifies local builds because then the property does not have to be declared.
=> Move common build arguments to maven.config and remove unnecessary

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/features/org.eclipse.help-feature/forceQualifierUpdate.txt
Jetty 12.0.2, which provides the fixed metadata, is staged according to:
https://github.com/eclipse/jetty.project/issues/10649
=> Update to Jetty 12.0.2

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This includes slightly updated versions of batik as well as new versions of lucene.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1392
=> Update target platform to Orbit pre-m1

eclipse.platform.common/pom.xml, eclipse.platform.releng/pom.xml, pom.xml
They have been wrong since the merge of repos and lead to wrong scm urls in bundles.
=> Remove wrong tycho.scmUrls

eclipse.platform.releng/bundles/org.eclipse.test.performance/META-INF/MANIFEST.MF, eclipse.platform.releng/bundles/org.eclipse.test.performance/src/org/eclipse/test/internal/performance/tests/AllTests.java, eclipse.platform.releng/bundles/org.eclipse.test.performance/src/org/eclipse/test/internal/performance/tests/PerformanceMeterFactoryTest.java, eclipse.platform.releng/bundles/org.eclipse.test.performance/src/org/eclipse/test/internal/performance/tests/SimplePerformanceMeterTest.java, eclipse.platform.releng/bundles/org.eclipse.test.performance/src/org/eclipse/test/internal/performance/tests/VariationsTests.java
The tests in `org.eclipse.tests.performance` are still written in JUnit 3, i.e., the test classes extend `TestCase`.
This change
* migrates tests and test suite to JUnit 5, and
* adds the missing `SimplePerformanceMeterTest` to the according test suite.
Note that these tests are not automatically executed at all, as they are neither part of a test plug-in nor does the plug-in seem to be configured to execute the tests via surefire or some ant script. But they run well when started from within the IDE. Making them executed in a CI build may be a follow-up task.
=> Migrate tests in org.eclipse.test.performance to JUnit 5

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml
These bundles are included by the org.eclipse.help feature but are not actually needed at runtime.
Also remove the include of com.sun.el.javax.el from the org.eclipse.help feature to eliminate its last 3rd party bundle include; the org.eclipse.equinox.jsp.jasper bundle's package requirement of the com.sun.el package is sufficient.
Remove these also from the places where the doc.isv mentions then.
And finally, remove them from the target platform itself.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1361
=> Remove jakarta.servlet-api, javax.servlet.jsp-api, javax.el-api

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Some smaller products have narrower dependencies that are satisfied by these, even if the SDK itself doesn't need/use them.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1361
=> Add jakarta.servlet-api, javax.servlet.jsp-api, javax.el-api to target

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml
The javadoc build seems to need them.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1361
=> Add jakarta.servlet-api, javax.servlet.jsp-api, javax.el-api to isv.

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
This avoids "Setting Security Manager is not supported" errors logged if running ant related tooling on Java 21.
Fixes https://github.com/eclipse-platform/eclipse.platform/issues/709
=> Add -Djava.security.manager=allow to SDK & Platform products

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1463
Re-opening this PR, as we see OOM's also without this change.
I plan to push it once https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3896 is fixed, to not mix possible regressions coming from this PR with "other" OOM issues we see right now.
=> Don't specify JVM memory limits in eclipse.ini

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
And remove the unnecessary specification of the property `org.eclipse.equinox.p2.type.product=true`, which Tycho/P2 already set by
default.
Additionally unify max-memory launcher-arguments of Platform/SDK products
P2 and Tycho 4.0.4 already support names for Product Update repositories with
- https://github.com/eclipse-equinox/p2/pull/353
- https://github.com/eclipse-tycho/tycho/pull/2929
but I think it is good to not submit this before PDE has Editor support for that as well as described in https://github.com/eclipse-equinox/p2/issues/345.
A similar simplification can then also be applied to all EPP packages.
=> Move more product configuration from p2.inf to product-file

.github/workflows/mavenBuild.yml
Platform UI has unstable tests that are hard to debug and platform specific. They save screenshots but build system does not archive anything but Junit reports in XML format. As screenshots are essential for failure analysis and test stabilization this change adds them to test artifacts.
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/1253#issuecomment-1783909424 for an example of test failure investigation.
=> Add screenshots of failed tests to Platform UI test artifacts

eclipse.platform.releng/bundles/org.eclipse.releng.tests/test.xml
In case of issues build is supposed to fail now.
=> Do not check pde/jdt schema logs in build tests

eclipse-platform-parent/pom.xml
Currently the javadoc plugin is configured in a profile for one explicit execution. If we want to use it on other plcaes it is better configured in the pluginManagement
=> Move Javadoc config to the pluginManagement

eclipse.platform.common/bundles/org.eclipse.jdt.tips.user/.settings/org.eclipse.core.resources.prefs, eclipse.platform.common/bundles/org.eclipse.platform.doc.tips/.settings/org.eclipse.core.resources.prefs, eclipse.platform.releng/bundles/org.eclipse.test.performance/.settings/org.eclipse.core.resources.prefs, eclipse.platform.releng/publish-to-maven-central/.settings/org.eclipse.core.resources.prefs
It was done using a "Quick Fix" and the value set (UTF-8) is the same value that any other project in the workspace uses. The objective of this commit is to declutter the "Problems" view.
=> Set a bunch of project encodings to UTF-8

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
... to ensure it is provided and to maintain backwards compatibility until support for javax annotations is finally removed.
Since https://github.com/eclipse-platform/eclipse.platform/pull/792 (and two follow-ups) the `javax.inect/annotation` providing bundles are not required by the `eclipse-platform-sdk` anymore and therefore not part of the sdk-repo automatically.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056
=> Add javax.inject/annotation providing bundles to eclipse.sdk repository

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
For fallback configuration we want to still ship both implementations in 2023-12 release.
@merks @akurtakov Requires PMC/PL approval, still using @mickaelistria 
See also
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1390
- https://github.com/eclipse-equinox/p2/issues/381#issuecomment-1807081486
=> Add the ecf http5 feature back to the target platform

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Apache Aries 1.3.7 contains fixes that simplify its usage and add support for Java-21:
- https://github.com/apache/aries/pull/233
- https://github.com/apache/aries/pull/243
I'm currently updating m2e to that version, which I plan to contribute to SimRel for the december release:
- https://github.com/eclipse-m2e/m2e-core/pull/1594
Since it will be in the SimRel anyways I suggest to update it here in the SDK now as well.
=> Update Apache Aries SPIFly to version 1.3.7

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr, eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggran
It should be mapped to two following as batik generally does:
https://repo1.maven.org/maven2/xml-apis/xml-apis-ext/1.3.04/
=> Don't publish org.eclipse.orbit.xml-apis-ext to Maven

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/removals.html
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056
I also added a corresponding N&N entry: https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/79
=> Add deprecation notice for javax support by the E4 injector

.github/workflows/licensecheck.yml
Context: https://github.com/eclipse/dash-licenses/pull/286
=> [License-Workflow] explicitly specify least required permission

eclipse-platform-parent/pom.xml
It is good style in maven to manage the used plugin versions in the parent, we already have some there but maven-deploy plugin is currently missing.
=> Manage version of maven-deploy-plugin

cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#1595
Now that there is content in I-builds 4.31 composite repo it's time to build against it.
=> Revert "Revert "Update Comparator repo and eclipse run repo to 4.31-I-builds repo""

RELEASE.md
This has been decided in the PMC call at the November 2023 call as it's extra work for releng.
=> Document all Milestones being lightweight

eclipse-platform-parent/pom.xml
See
- https://github.com/eclipse-pde/eclipse.pde/pull/913
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4011
With only a few plugins actually using a lower BREE < 9 we could also think about dropping this completely over time and instead rely on the `-release` option of modern JDKs
=> Make use of BREE configurable and fix documentation link

eclipse-platform-parent/pom.xml
Currently there is a (hidden) timestamp generated in the javadoc what is not very useful for our use case where we want to replace artifacts by the baseline version what means we have changes on each build.
This disable the generation of timestamps for javadoc to get more reproducible builds.
=> Don't include timestamp in javadoc

Jenkinsfile, eclipse-platform-parent/pom.xml
As tycho 4.0.5 contains some important Api Tools fixes we should use the snapshot until the release.
**This should be merged as soon as master is opened for next development cycle.**
=> Use Tycho 4.0.5 SNAPSHOT

oomph/PlatformSDKConfiguration.setup
After few days of doing much work in platform workspace across several repositories i use to end up in OOME.
I never could find a single point of failure, memory is allocated by jdt, platform, jgit, pde, classloader ... it seems like it just sums up
If anybody wants that heapdump just tell me
=> use 3GB Heap on Platform Workspace

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml
Broken in
https://download.eclipse.org/eclipse/downloads/drops4/I20231205-0520/compilelogs/platform.doc.isv.javadoc.txt
=> Fix platform javadoc build

eclipse-platform-parent/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1640
=> JUnitTestRunnerInterceptor: Add missing dependency #1640

.github/dependabot.yml
Example is
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1629 and https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1627
The config on "/" is enough as eclipse-platform-parent is a module of the top pom.
This is leftover from the past as initially the repo was mostly pointing to other subrepos and only eclipse-platform-parent was considered for updates. When config for / was added the one for eclipse-platform-parent should have been removed.
=> Prevent two PRs for same update from dependabot

eclipse.platform.releng/bundles/org.eclipse.releng.tests/forceQualifierUpdate.txt, eclipse.platform.releng/bundles/org.eclipse.releng.tests/src/org/eclipse/releng/tests/TouchBundles.java, eclipse.platform.releng/bundles/org.eclipse.test.performance/forceQualifierUpdate.txt, eclipse.platform.releng/bundles/org.eclipse.test/forceQualifierUpdate.txt
Also added TouchBundles to run over extracted artifactcomparisons.zip and touch every bundle that need to be touched.
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1394 
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1659
=> Touch bundles affected by the changed ecj version

eclipse-platform-parent/pom.xml
https://github.com/eclipse-platform/eclipse.platform/pull/973 identified that IDE builds and maven builds produce different bytecode due to ignoring project settings which shouldn't be the case
=> Config tycho-compiler-plugin to use project settings

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
This is to temporary resolve the issue with warning about unsatisfied contracts / packages of org.osgi.service.http and
org.osgi.service.http.whiteboard once we have resolved the discrepancy in org.eclipse.osgi.services this can be replaced / removed again.
=> Add org.apache.felix.http.servlet-api to resolve maven warnings

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
With https://github.com/eclipse-equinox/equinox/pull/403 the sources of org.osgi.service.http are provided in a re-packed bundle from Equinox, that also provides the OSGi capabilities which where temporarily provided by felix.http.servlet-api.
As planned, this also reverts https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1672 because it is not necessary anymore.
=> Remove org.osgi.service.http and felix.http.servlet-api from SDK TP

eclipse-platform-parent/pom.xml
Fix https://github.com/eclipse-platform/eclipse.platform/issues/1017
FYI @HeikoKlare
=> Add old javax.inject as an additional javadoc dependency

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt
Adapt to https://github.com/eclipse-equinox/equinox/pull/403 as requested in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1677#issuecomment-1862138451.
Based on what has changed in https://github.com/eclipse-equinox/equinox/pull/403 and what currently fails I assume these are the right changes.
@akurtakov or @laeubi can you confirm this?
=> Adapt java-doc build to replacement of embedded service.http sources

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/removals.html
This adds notices for the deprecation for removal for 
- The bundle `org.eclipse.osgi.services`:
https://github.com/eclipse-equinox/equinox/issues/18
- The class `PluginVersionIdentifier`:
https://github.com/eclipse-equinox/equinox/pull/427
Besides adding this to the porting guide it could also be mentioned in the N&Ns?
=> Add notices about deprecation of org.eclipse.osgi.services bundle and PluginVersionIdentifier class

eclipse-platform-parent/pom.xml
See https://github.com/eclipse-platform/eclipse.platform/issues/1017
FYI @HeikoKlare
=> Add old javax.annotation as an additional javadoc dependency

eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/LegacyXmlResultFormatter.java
* Change the `LegacyXmlResultFormatter` so it shows failed containers too (_e.g._ test classes)
* Refactor the class: extract 1 new method called `writeIfPresentInMap` and call it from 3 existing methods
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1689
* See #1689 for information on how to run the `EclipseTestRunner` and run it
* The generated XML report should have 1 `<testcase>` node showing the failed test class `ErrorOnTearDownClass`, like this:
```xml
<testcase classname="ErrorOnTearDownClass" name="" time="0.014">
<error type="java.lang.RuntimeException">java.lang.RuntimeException
at org.eclipse.test.tests.snippets.resources.ErrorOnTearDownClass.tearDownClass(ErrorOnTearDownClass.java:13)
at …
```
=> Show failed containers in JUnit XML report #1689

eclipse-platform-parent/pom.xml
Currently the locale is determined by the system what can result in slightly different results.
This configures the locale to be always 'en' (+removes an old comment)
=> Specify the locale for the javadoc build

.gitmodules, pom.xml
With https://github.com/eclipse-platform/eclipse.platform.swt/pull/956 the swt native binaries are stored in the `eclipse.platform.swt` repository using git-lfs. The `eclipse.platform.swt.binaries` repository is therefore obsolete.
Part of https://github.com/eclipse-platform/eclipse.platform.swt.binaries/issues/2
=> Remove eclipse.platform.swt.binaries sub-module to reflect merge with eclipse.platform.swt

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml
Work towards fixing
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1707
=> PDE bundles are not needed for building Platform/JDT docs

eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/pom.xml
* tycho-version is already set in parent, no point in repeating it
* resolver=p2 is not supported configuration for ages
=> Remove useless maven configurations

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml
It was missed in the conversion to maven.
=> Add back readmetool example to platform.doc.isv

oomph/Platform.setup
The eclipse.platform.swt sub-module contains Git LFS content. Therefore in order to fully pull it with EGit/JGit the LFS plugin is necessary.
@merks or should we just add it to the parent Platform project? Then it would not be necessary to have it in the SWT setup and the Platform Aggregator setup.
Having it installed is usually not a problem if not used.
@laeubi FYI
=> [Setup] Add JGit LFS to Platform Aggregator setup

JenkinsJobs/Builds/I_build.groovy
Since https://github.com/eclipse-platform/eclipse.platform.swt/pull/973 the I-build (like the SWT build) requires a java-17 (or later) jdk on the `PATH` system environment-variable in order to launch a `jdk>=17` with the 'java' command from the CLI. Just setting the `JAVA_HOME` variable to a path pointing to a jdk-17 is not sufficient since the the java executable is usually located in `$JAVA_HOME/bin`. And while the maven launch script searches in `$JAVA_HOME/bin` for a java executable to run the build itself, a simple java command on the CLI isn't that smart. 
Previously running the `java` command would just run the default default java version on the Jenkins executor.
In general this simplifies the build-configuration because the JDK to use is only defined once and used everywhere. …
=> Declare required jdk and maven as top-level pipeline tools in I-builds

JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy
Applies the following changes to P- and Y-builds:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1727
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1728
=> Declare required jdk as top-level pipeline tool for P- and Y-builds

eclipse-platform-parent/pom.xml
This simplifies overrides by CLI arguments when necessary, e.g. with -Dtycho.baseline.replace=none
=> Configure t-p2-plugin:baselineReplace with property to enable overrides

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml
remove white space from path names
Refs: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1536
=> make path names unix friendly

cje-production/mbscripts/mb220_buildSdkPatch.sh
Maven by default do not print stack traces when a mojo fails ,this makes it quite hard to understand build problems that are caused by unexpected failures.
This adds the -e switch to maven to print full stack trace.
=> Print exception when executing maven

eclipse-platform-parent/pom.xml
As people are ["steady confused"](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1557#issuecomment-1910559050) we better should have slower builds than confusing even experienced committers so they constantly complain about "randomness". Also requested [here](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1557#issuecomment-1910099859).
=> Don't skip api analysis if artifact was replaced to always get messages

eclipse-platform-parent/pom.xml
Currently API tools messages are shown only in the maven log where they are hard to find.
This disable the maven log output and redirects the messages to the compile logs so they can be displayed in Jenkins
=> Redirect API messages to the ECJ log

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/features/org.eclipse.test-feature/forceQualifierUpdate.txt
Update assertj-core to 3.25.3.
Update junit-jupiter-* and junit-vintage-engine to 5.10.2. Update junit-platform-* to 1.10.2.
=> Target platform bundle updates

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/help_preferences.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/help_preferences_content.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-12.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-16.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-19.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-20-fileContent.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-20.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-20team-models.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-22.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-35.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-36.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-42.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-7.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-antcontentassist.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-anteditor.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-anteditorprefs.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-antformatter.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-antprefs.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-antruntimeprefs.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-anttemplates.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-capabilitiespref.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-content-type.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-globalizationprefs.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-securestorage-prefs.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-startup-workspaces.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-texteditorprefs.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/topics_Reference.xml
The titles of the documenation of the preference pages should be uniform. This means:
- Use "Title Case" style and and not "Sentences case" style
- Don't append additional words "Preferences" or "Preference Page"
- Entry in the table of content (tree on the left side) should be the same as the title
=> Unify Titles For Preference Pages Documentation

eclipse-platform-parent/pom.xml
Currently the eclipse-sign goal disables the default meta data generation of a project (as it needs to update the metadata afterwards) but this seem to fail under some circumstances with quite obscure errors.
This removes the disabling of the default-metadata what might be a tiny little slower but seem not to cause any issues in reward.
@akurtakov this seems what currently fails the master build.
=> Do not disable the default metadata generation

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-16.htm
Document "Tab icons and titles in view areas" Section of The Appearance Preference Page #1778
As part of https://github.com/eclipse-platform/eclipse.platform.ui/pull/1071, two preferences were added in the Appearance section.
- hide tab icons in view areas, and 
- show full titles for tabs in view areas
This PR aims at documenting these preferences for eclipse help.
=> Document preferences to hide tab icons and show full texts in view areas

.mvn/jvm.config, eclipse-platform-parent/pom.xml
Do not print an extra message if tests pass/fail even if test failures
are ignored.
Here it was complained that "maven" prints an additional error/warnings when test fails:
- https://github.com/eclipse-platform/eclipse.platform.ui/discussions/1644#discussioncomment-8380264
this now makes the mojo "quiet" so it does not give any message at all and hopes the user notices it otherwise that test failures occurred (e.g. by examine the Test results on Jenkins).
=> Make tycho-surefire-plugin quiet

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
There are no IU updates.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1697
=> Update the orbit URL to the m3 milestone

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-content-type.htm
Documents changes from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1665
=> Document new option of declaring a default editor in preferences

eclipse-platform-parent/pom.xml
Run https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ before merge.
@iloveeclipse @mpalat
=> ECJ version update for M3

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
There are no IU updates.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1697
=> Update the orbit URL to the rc1 milestone

eclipse.platform.common/bundles/org.eclipse.jdt.tips.user/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.tips.user/content/provider.json, eclipse.platform.common/bundles/org.eclipse.jdt.tips.user/pom.xml, eclipse.platform.common/bundles/org.eclipse.jdt.tips.user/src/org/eclipse/jdt/tips/user/internal/JDTTipProvider.java
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1825
=> Change http://www.eclipse.org to https://www.eclipse.org in tips URLs

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml
Version bumps for 4.32 stream
Tracked in
eclipse-platform/eclipse.platform.releng.aggregator#1862
=> Version bumps for 4.32 stream

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr, eclipse.platform.releng/publish-to-maven-central/properties.sh
Update SDK4Mvn.aggr and properties.sh file for publishing 4.31 to maven central.
Refs: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1882
=> Publish 4.31 to Maven central

.github/dependabot.yml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#1643
This broke dependabot opening PRs for maven plugins in eclipse-platform-parent
=> Revert "Prevent two PRs for same update from dependabot"

eclipse-platform-parent/pom.xml
Currently Tycho warns if an item is in the build but not in the baseline but this seems not very interesting for the user so disable it here with 'warnCommon'.
Additionally this now enables to enhance the ECJ logs with warnings about class files that have changed (see https://github.com/eclipse-tycho/tycho/pull/3687)
=> Enhance compile logs with class baseline problems and use warnCommon

.github/workflows/codeQLworkflow.yml, .github/workflows/mavenBuild.yml, .github/workflows/prepareRelease.yml, .github/workflows/updateRelease.yml
For some reason dependabot doesn't catch it but GH runners complain about it using Java 17.
=> Update setup-maven GH action to v5

production/testScripts/configuration/sdk.tests/testScripts/test.xml
Enables the tests in the `org.eclipse.tips.tests` project for which an Ant configuration has been provided via https://github.com/eclipse-platform/eclipse.platform/pull/1147.
=> Add org.eclipse.tips.tests to main test script

.github/workflows/mavenBuild.yml, Jenkinsfile
Java 21 is the next LTS and projects are allowed to use Java 21 in this release, therefore it should become the new primary Java version used to execute the build.
This also will allow us to catch any possible issues with Java 21 used as build VM.
=> Make Java 21 the primary JVM to execute the maven build

eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml
The tests in `org.eclipse.tips.tests` recently enabled for the Ant-based build require the test plug-in to be added to the SDK test feature to be available during the build.
Complements https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1924
=> Add org.eclipse.tips.tests to SDK test feature

eclipse-platform-parent/pom.xml
Trying to fix thousands of "baseline and build for *.class have different contents"
=> Update ecj version to latest in stable I-build

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/testManifest.xml
The test results for `org.eclipse.tips.tests` now show up in the CI test results, e.g. https://download.eclipse.org/eclipse/downloads/drops4/I20240325-1800/testResults.php
Still there is an error about a missing xml file entry on the CI test results page to be fixed by this PR.
The `TestResultsGenerator` used for collecting aggregator build tests results contains a sanity check that requires each test project to be added to a `testManifest.xml`. This adds the `org.eclipse.tips.tests` project recently enabled for the Ant-based build to that XML file.
Complements https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1924
=> Add org.eclipse.tips.tests to testManifest.xml

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/testManifest.xml, eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml, production/testScripts/configuration/sdk.tests/testScripts/test.xml
This adds the test bundles org.eclipse.core.contenttype.tests and org.eclipse.update.configurator.tests to the Ant-based build.
* Adds the bundles to the SDK test feature
* Adds according targets to the main test.xml
* Adds the produced log files to the testManifest.xml
Fixes https://github.com/eclipse-platform/eclipse.platform/issues/219
=> Add core.contenttype.tests and update.configurator.tests to Ant build

.github/workflows/mavenBuild.yml
mac-latest was used and this was mac-12 but due to https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/ is now mac-14.
Switching to mac-13 to still be newer than what it used to be but still latest as there is no temurin java 8 for it leading to https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/8801294125/job/24154512271?pr=1842 :
```
Trying to resolve the latest version from remote
Error: Could not find satisfied version for SemVer '8'.
Available versions: 22.0.1+8, 22.0.0+36, 21.0.3+9.0.LTS,
21.0.2+13.0.LTS, 21.0.1+12.0.LTS, 21.0.0+35.0.LTS, 20.0.2+9, 20.0.1+9,
20.0.0+36, 19.0.2+7, 19.0.1+10, 19.0.0+36, 18.0.2+101, 18.0.2+9,
18.0.1+10, 18.0.0+36, 17.0.11+9, 17.0.10+7, 17.0.9+9, 17.0.8+101,
17.0.8+7, …
```
=> Switch GHA maven build to Mac 13

JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java21.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java22.groovy
Leverage the standard Jenkins pipeline tools section to set up the JDK and ANT instead of downloading the JDK 'manually'.
This uses the JDKs provided in the EF Jenkins instances as listed in
- https://wiki.eclipse.org/Jenkins#JDK
@akurtakov am I right that the previous, more complicated implementation is a left-over from the more complicated past or is there a compelling reason to keep it as it is?
I tested the changes for Java-17 and 22 by replaying the corresponding jobs with the changes applied and AFAICT everything looked good.
=> [I-Build-Tests] Simplify tool provisioning for Linux tests

JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java21.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java22.groovy
Declaring a jdk and ant the usual way in the 'tools' section, because of unknown reasons, breaks the usage of fundamental commands like `xvnc`, `pkill` and `sh`.
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1997#issuecomment-2080385005
=> [I-Build-Tests] Fix breakage of fundamental commands by tools-sections

JenkinsJobs/AutomatedTests/I_unit_mac64_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_macM1_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy
This allows to unify the job definition with the test-jobs for Linux and also allows to simplify some parts of the job a lot.
It also removes the `testSuite` parameter only available in mac tests, since anybody that wants to run another suite than all can just `Replay` the build in the Jenkins web-interface and adjust the suite as desired.
Especially the Windows pipeline needs some more local testing, e.g. with regards to spanning a command over multiple lines, but nevertheless I still would like to gather some early feedback.
=> [I-Build-Tests] Define Mac and Windows jobs as Jenkins-pipeline

cje-production/mbscripts/mb300_gatherEclipseParts.sh
This last step was forgotten in PR https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1917, activating the publication of Eclipse SDK/platform products for the win32.aarch64 environment.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/577
=> [I-Build] Copy built products for Windows on Arm to publication area

eclipse.platform.releng/features/org.eclipse.platform-feature/feature.xml
The fragment 'org.eclipse.core.net.win32.x86_64', that is empty since it was replaced by the architecture independent variant 'org.eclipse.core.net.win32' some time ago is deleted in https://github.com/eclipse-platform/eclipse.platform/pull/1349
=> Remove obsolete core.net.win32.x86_64 fragment from o.e.platform feature

.github/workflows/codeQLworkflow.yml, .github/workflows/mavenBuild.yml
GH Actions transitioned to Node 20 in September 2023 and all projects should transition too (see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)
This gets rid of the warnings in the runs of GH Actions.
=> Update coactions to use Node 20

eclipse.platform.releng/features/org.eclipse.test-feature/forceQualifierUpdate.txt
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2044
=> Force qualifier to resign bundles signed with an expired certificate

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.32/faq.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.32/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.32/recommended.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/eclipse_4_32_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.32/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.32/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.32/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_32_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Porting.xml
Migration guide for Eclipse 4.32 from 4.31
=> Migration Guide Eclipse 4.32

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/features/org.eclipse.test-feature/forceQualifierUpdate.txt
Using latest orbit milestone repo; no new content.
=> Update assertj-core to 2.26.0

JenkinsJobs/Builds/I_build.groovy
Ensure all stages run within the 'jnlp' container and remove defaultContainer 'container' because a container named 'container' isn't defined.
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2101#issuecomment-2152845763
=> [I-build] Fix I-build kubernetes container configuration

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- This version of EMF raises the BREE of all bundles to JavaSE 1.8.
- The other formatting changes are to reduce the number of changes resulting from the use of Update button in the PDE editor.
=> Update the target platform to EMF 2.39 M0

eclipse.platform.releng/features/org.eclipse.platform-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.platform-feature/pom.xml
The o.e.core.resources.win32.x86_64 fragment is removed because the Windows native file-system refresh monitor is migrated to use JNA instead of native code (JNI).
See https://github.com/eclipse-platform/eclipse.platform/pull/1394
=> Remove org.eclipse.core.resources.win32.x86_64 fragment from feature

JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java21.groovy, JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3_java22.groovy, JenkinsJobs/AutomatedTests/I_unit_mac64_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_macM1_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy
Declaring the parameters only within the pipeline definition has the disadvantage that they have to be discovered in the first run and are therefore only available in the second run onwards. This leads to total failures of all I-build tests on the first run each time the seed job to create the Eclipse RelEng jobs ran.
Permanently fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2101
=> [I-Build-Tests] Declare parameters in job configuration

.gitmodules, cje-production/streams/repositories_java23.txt, cje-production/streams/repositories_master.txt, eclipse-platform-sources/sources.xml, oomph/Platform.setup
Adapt to the name changed assumption about the default name in equinox.
See https://github.com/eclipse-equinox/equinox/pull/641
=> Rename rt.equinox.binaries sub-module to equinox.binaries

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-linkhandlersprefs.htm
Contributes to https://github.com/eclipse-platform/eclipse.platform.ui/issues/1901
=> Registering URL Schemes for Signed macOS Apps Is Not Possible

Jenkinsfile
Reduce the number of actual signing by not signing artifacts on master branch builds in this repository (the built artifacts are not published) and not re-signing artifacts in the I-build that are baseline replaced and therefore already signed.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2134
In order for `DO_NOT_RESIGN` to have an effect, signing should happen after a baseline-repacement done in `tycho-p2:p2-metadata`. Currently it is done before. Therefore this is a draft.
=> [Build] Build don't resign signed jars and skip signing in master build

eclipse-platform-parent/pom.xml
Reduce the number of actual signing operations by not re-signing artifacts (in the I-build) are already signed, usually because they have been 'baseline-replaced'.
In order to ensure that signatures of baseline-replaced artifacts can be considered, the p2-baseline-replacement is moved before the `eclipse-jarsigner-plugin`.
Furthermore set 'defaultP2Metadata' to false to skip the default baseline replace.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2134
This is a follow-up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2140.
=> [Build] Don't resign already signed jars

production/testScripts/runTests2.xml
This was removed in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2150 although the property `javaversionEscaped` is still in use.
=> Restore creation of javaversionEscaped property in runTests2 ANT script

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy
Inherit most of the configuration from the centos-8 pod-template.
This extracts the changes made in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2107 on the kubernetes spec.
=> [I/Y/P-Builds] Simplify Kubernetes pod definitions

eclipse.platform.releng/features/org.eclipse.platform-feature/feature.xml
The platform specific fragments 'org.eclipse.core.net.linux' and 'org.eclipse.core.net.win32' are merged into their host bundle 'org.eclipse.core.net' via https://github.com/eclipse-platform/eclipse.platform/pull/1440.
=> Remove o.e.core.net fragments being merged from platform-feature

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/YBuilds/P_build.groovy, JenkinsJobs/YBuilds/Y_build.groovy
This reverts PR https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2157.
The yaml merge strategy for pod templates was changed to 'merge' for all volumes/volumeMounts in:
https://github.com/eclipse-cbi/jiro/pull/377
Now they are all inherited from the pod-template.
=> Revert "[I/Y/P-Builds] Restore mount of toolchains.xml in K8 pod definitions"

.github/workflows/verifyFreezePeriod.yml
=> Update verifyFreezePeriod.yml to ignore milestone promotions

eclipse-platform-parent/pom.xml
It's implicit for ECJ when target>=1.5 , aggregator no longer compiles anything to target < 1.5 and ecj is dropping support for target<1.8.
=> Drop explicit inlineJSR param to tycho

eclipse.platform.common/bundles/org.eclipse.platform.doc.user/contexts_Workbench.xml
Adds a help context for the find/replace overlay which links to the help context for the dialog.
related to
https://github.com/eclipse-platform/eclipse.platform.ui/pull/2045
=> Add help context for the find/replace overlay

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/testManifest.xml, eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml, production/testScripts/configuration/sdk.tests/testScripts/test.xml
This adds the test bundle org.eclipse.core.tests.resource.saveparticipant to the Ant-based build.
* Adds the bundles to the SDK test feature
* Adds according targets to the main test.xml
* Adds the produced log files to the testManifest.xml
Belongs to https://github.com/eclipse-platform/eclipse.platform/pull/1384
=> Add save participant test project to Ant-based build

.github/workflows/licensecheck.yml
As dash project is its own github org the path to the workflow file changes.
=> Fix licensecheck run

eclipse-platform-parent/pom.xml
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2193
=> Latest jarsign service produces CODESIGN.SF/RSA not ECLIPSE_.SF/RSA

eclipse.platform.releng/features/org.eclipse.platform-feature/feature.xml, eclipse.platform.releng/features/org.eclipse.platform-feature/pom.xml
That fragment is removed viahttps://github.com/eclipse-platform/eclipse.platform/pull/1476
=> Remove o.e.core.filesystem.win32.x86_64 fragment from o.e.platform feature

.github/workflows/updateTarget.yml
Currently we need to keep track of new versions manually what can become quite cumbersome.
This creates an (experimental) automatic job that is triggered each day and check if there are updates available and suggests a PR to update them.
=> Add workflow that automatically updates target dependencies

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
+ add extension for rendering tables
Follow-up from #2190, as required by https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1472 based on https://openjdk.org/jeps/467#Tables
=> Markdown support for JEP 467 - extension for tables

.github/workflows/updateTarget.yml
Currently we need to keep track of new versions manually what can become quite cumbersome.
This creates an (experimental) automatic job that is triggered each day and check if there are updates available and suggests a PR to update them.
=> Add workflow that automatically suggests updates of target dependencies

.github/workflows/updateTarget.yml, eclipse.platform.releng.prereqs.sdk/update-rules.xml
This adds a ruleset so we can ignore unwanted versions (beside major updates) from being suggested by the update-target workflow.
This first requires
- https://github.com/eclipse-tycho/tycho/pull/4130
what currently is blocked by IP issue:
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15947
=> Add a ruleset for updating dependencies

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Update commons-logging to 1.3.4.
- The orbit repository contains no changes to the included IUs.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2166
=> Update Orbit dependencies

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.32/incompatibilities.html
To inform about changes in
- https://github.com/eclipse-platform/eclipse.platform/pull/1394
- https://github.com/eclipse-platform/eclipse.platform/pull/1476
- https://github.com/eclipse-platform/eclipse.platform/pull/1440
@akurtakov I think this is the right thing to do, isn't it?
=> Add 'incompatibilities' entry about inlined native fragments

eclipse-platform-parent/pom.xml
3.39.0.v20240820-0604 Need to run https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/
=> Update Latest ECJ Version for RC2

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.33/faq.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.33/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.33/recommended.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/eclipse_4_33_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.33/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.33/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.33/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_33_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Porting.xml
Migration guide for Eclipse 4.33 from 4.32
=> Migration Guide Eclipse 4.33

eclipse.platform.releng.tychoeclipsebuilder/java23patch/eclipse.releng.repository.java23patch/category.xml, eclipse.platform.releng.tychoeclipsebuilder/java23patch/eclipse.releng.repository.java23patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java23patch/org.eclipse.jdt-feature-dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java23patch/org.eclipse.jdt.dummy/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java23patch/org.eclipse.jdt.java23patch/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/java23patch/pom.xml
We need to start making patch builds for Java 23 based on the latest 4.33 build and later on to 4.33 release build.
=> Update P build scripts to Java 23

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
Changing the version of SDK4Mvn.aggr from 4.33 to  4.34-I-Builds post publishing to maven central.
Refs: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2321
=> Changing version from 4.33 to 4.34-I-Builds

oomph/Platform.setup
- The Oomph catalogs are updated such that they aren't needed.
- Rough in early 4.35 redirects for at the end of the current cycle
=> Disable the early 4.34 setup redirects

cje-production/mbscripts/mb300_gatherEclipseParts.sh, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/testManifest.xml
Its content is included in eclipse-Automated-Tests.zip since forever and whoever needs it should install it from p2 repo.
=> Stop generating and publishing eclipse-test-framework.zip

eclipse.platform.releng/bundles/org.eclipse.test.performance/META-INF/MANIFEST.MF, eclipse.platform.releng/bundles/org.eclipse.test.performance/pom.xml, eclipse.platform.releng/bundles/org.eclipse.test/META-INF/MANIFEST.MF, eclipse.platform.releng/bundles/org.eclipse.test/pom.xml
- Both need to be bumped because neither is signed by the latest available signing certificate.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2335
=> Bump version to match jar signatures

.github/workflows/prepareRelease.yml, .github/workflows/updateRelease.yml, eclipse-platform-parent/pom.xml
Also required for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2352.
=> [Build] Unify version configuration of 'tycho-versions-plugin'

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Update com.sun.jna/jna-platform to 5.15.0.
- Update org.eclipse.orbit.xml-apis-ext to new qualifier version.
- Update org.commonmark to 0.23.0.
=> Update that target platform to a new Orbit milestone

JenkinsJobs/Builds/I_build.groovy
Having it commented in the jenkinsfile made it being no standard time build.
=> Enable standard I-build schedule

eclipse.platform.releng/bundles/org.eclipse.test.performance/.classpath, eclipse.platform.releng/bundles/org.eclipse.test/.classpath
- The downstream dependencies in the workspace end up with a sea of red.
=> Remove .classpath attributes about containing only test source

eclipse-platform-parent/pom.xml
Revert to use previous release's API-Tools to hopefully unblock verification builds that are currently suffering from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2360#issuecomment-2364207760.
If this doesn't help, the problem is probably not directly within PDE's API-Tools but in the integration with Tycho.
=> Temporarily use 2024-06 API-Tools for API checks in verification builds

eclipse-platform-parent/pom.xml
Temporarily revert the `tycho-apitools:verify` mojo to version 4.0.8 for API checks to hopefully unblock verification builds that are currently suffering from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2360#issuecomment-2364207760.
=> [Build] Temporarily use tycho-apitools:verify mojo in version 4.0.8

eclipse.platform.releng/bundles/org.eclipse.test.performance/.settings/.api_filters, eclipse.platform.releng/bundles/org.eclipse.test.performance/META-INF/MANIFEST.MF, eclipse.platform.releng/bundles/org.eclipse.test.performance/pom.xml
Dependent bundles should be fixed to require what they need direclty so no need for the reexport any more.
=> Stop requiring and reexporting o.e.test in o.e.test.performance

eclipse-platform-parent/pom.xml
This can for example be used in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2994 and can be applied to future version-baseline check mojos that are probably necessary for
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2352
=> Add overwritable indirection for flag to skip version baseline check

eclipse-platform-parent/pom.xml
It's a prep step decoupling cbi plugin from using tycho internals as tycho 5.0 changed them in prep for Maven 4.
=> Use 1.5.1 snapshot cbi plugin

.github/workflows/checkVersions.yml, .github/workflows/publishVersionCheckResults.yml
If an Eclipse Plugin project is changed the first time in a development cycle build failures due to missing version bumps are very common, for example like in the following case:
```
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.8:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.pde.api.tools.tests:
Only qualifier changed for (org.eclipse.pde.api.tools.tests/1.3.600.v20240905-2015). Expected to have bigger x.y.z than what is available in baseline (1.3.600.v20240806-1811) -> [Help 1]
```
This PR adds a workflow to automatically detect the need for such service version increments whenever a PR is created or updated, using a fast running Maven build that invokes the …
=> Add workflow for automated version increments in pull-requests

eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/toc.xml
- Platform and PDE "Development User Guide" instead of "development user guide".
- "Getting started" is used in stead of "Getting Started" by the other projects.
=> Align Case-Ing to make topic titles consistent

JenkinsJobs/Builds/DockerImagesBuild.jenkinsfile, JenkinsJobs/Builds/FOLDER.groovy
The triggers defined in a Jenkins-pipeline are only applied to the Job-configuration after the first execution of the pipeline. This has the consequence that after each execution of the seed job the configuration of the 'DockerImagesBuild' is reset to have no triggers and consequently it would require a manual execution of that job to restore the cron-trigger each execution of the seed job.
=> [Build] Define cron-trigger for DockerImagesBuild in Job definition

.github/dependabot.yml
This is gone now and these images are no longer built.
=> Stop dependabot docker for centos 8

.github/workflows/checkVersions.yml
Do not just commit every changed file in order to avoid accidental commits of resources changed or generated during builds. For version increments only the following files are relevant:
- META-INF/MANIFEST.MF
- feature.xml
- pom.xml
This became relevant for example in https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/516#issuecomment-2377878801.
=> [Build] Commit only relevant files in version increment workflow

.github/workflows/checkVersions.yml
Stage the relevant kind of files in isolation and don't fail if that kind of file does not exist at all in the repository.
Otherwise the entire step fails if the repo for example doesn't contain a feature.xml, because the previous 'git add' command then fails with:
`fatal: pathspec '*/feature.xml' did not match any files`
This became relevant for example in https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/516
=> [Build] Make staging of relevant files robust against file absence

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/bundles/org.eclipse.releng.tests/META-INF/MANIFEST.MF, eclipse.platform.releng/bundles/org.eclipse.releng.tests/ignoreFiles.txt, eclipse.platform.releng/bundles/org.eclipse.releng.tests/pom.xml, eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml
- The org.hamcrest.core bundle is just an empty hull to provide metadata that redirects all references to it to the new org.hamcrest bundle that avoids split packages with the org.hamcrest.library bundle by combining all the content into a single bundle.
- Nothing in the SDK should require org.hamcrest.core anymore, so it can be removed.
- A new org.junit bundle from Orbit is needed that requires the org.hamcrest bundle instead of the org.hamcrest.core bundle.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2343
=> Remove org.hamcrest.core from Eclipse SDK

cje-production/mbscripts/mb300_gatherEclipseParts.sh, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/testManifest.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox/buildConfigs/equinox-launchers/build.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox/publishingFiles/testManifest.xml
Similiarly like it was done for Windows on ARM:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1917
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2017
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2310.
@yuzibo FYI
=> Add linux.riscv64 environment to eclipse-platform-parent and publish linux.riscv64 artifacts

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product
With
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1901 the auto-registration of link handlers was removed to avoid breaking of code signatures.
In order to use the 'eclipse+command' URI schemes on macOS, this must instead be pre-registered during .app bundle build time before code signing.
=> Eclipse Platform Binary: Register eclipse+command links for macOS

.github/dependabot.yml
In the past we used to have maven updates for platform-parent only as it was not working for /. Fixes allowed to have dependabot run for / but the run for eclipse-platform-parent was not removed which led to 2 PRs being generated for each update there e.g.:
* https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2412
* https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2411
=> Stop generating 2 PRs for maven updates

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Removes the workaround for getting an early version of org.junit
- Updates lucene to 9.12.0.
=> Update the target platform to the latest Orbit and EMF milestones

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml
Part of https://github.com/eclipse-pde/eclipse.pde/issues/1427
=> Fix path to generated apidoc by maven javadoc

oomph/.project, oomph/Platform.setup
Add a reference to the configuration for the eclipse.platform setup added via https://github.com/eclipse-platform/eclipse.platform/pull/1582.
In that PR the project `org.eclipse.platform.setup` is added, which would collide with the project contained in this repository containing the platform-sdk setup.
In order to match the names rename this repo's project from `org.eclipse.platform.setup` to `org.eclipse.platform.sdk.setup`.
=> [Oomph-Setup] Add reference to new eclipse.platform configuration setup and unify name of project containing the platform.setup

JenkinsJobs/Builds/DockerImagesBuild.jenkinsfile, cje-production/dockerfiles/debian/swtnativebuild/Dockerfile, cje-production/dockerfiles/debian/swtnativebuild/scripts/uid_entrypoint
Currently we build the swt natives with centos-8 but this is now gone,
also centos-9 no longer provides stable releases but only
rolling-streams,
This adds a new container based on debian stable and only adds the
absolute minimum required to build the swt natives.
Debian offers quite conservative dependencies and LTS releases
so there is a good chance to have a common baseline that works on
more ahead distributions as well (e.g. GClib /GTK/... versions).
=> Add debian stable based image to build swt natives

eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/TracingSuite.java
Otherwise it's hard to tell which test failed when/first if error are collected in other logfiles only.
=> TracingSuite: add stacktrace to stdout

.github/workflows/checkVersions.yml
To fix the problem discovered in P2: https://github.com/eclipse-equinox/p2/pull/558#issuecomment-2408530095.
=> [Version check] Make SDK number read robust against additional print-out

JenkinsJobs/YBuilds/Y_build.groovy
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2434
=> Update YBuild for java24

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
Use the Windows operating system trust store instead of the cacerts bundled with the JVM.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=567504
=> Bug 567504 - Use system trust store on Windows instead of cacerts

JenkinsJobs/AutomatedTests/I_unit_cen64_gtk3.groovy, JenkinsJobs/AutomatedTests/I_unit_mac_java17.groovy, JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy
The job creation failed with message:
`General error during canonicalization: The sandbox does not currently support multiple assignment`.
Reverting the assignment simplifications hopefully fixes that.
Follow-up of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2005.
=> [I-Build-Tests] Revert multiple assignments

JenkinsJobs/Builds/I_build.groovy
The renaming was initially intended, but reverted to avoid more downstream script changes. Reverting that change was forgotten.
A second follow-up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2005.
This can be submitted immediately too. Now that we change the I-build job, I'll just cancel the running one and restart another one after the I-build job config has been regenerated.
=> [I-Build-Tests] Revert change of I-build test job name for mac

JenkinsJobs/Builds/I_build.groovy
Recently the I-build failed occasionally because the container was killed which was very likely due to excessive memory usage.
Let's see if this makes a difference.
Submitting this immediately as well and will abort the running I-build and restart a new one after the job has been regenerated.
=> [I-Build] Raise max memory limit to 10Gi for I-builds

JenkinsJobs/AutomatedTests/I_unit_win32_java17.groovy
Bug https://bugs.openjdk.org/browse/JDK-8336862 could be the reason for (all/some?) recent Windows test failures. 
Let try the previous version...
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1486 and https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5213
=> Downgrade Windows JDK used for tests from jdk-17.0.12.7 to jdk-17.0.11+9

JenkinsJobs/AutomatedTests/I_unit_linux.groovy, JenkinsJobs/AutomatedTests/I_unit_mac.groovy, JenkinsJobs/AutomatedTests/I_unit_win32.groovy, JenkinsJobs/Builds/I_build.groovy, cje-production/Y-build/publish.xml, cje-production/scripts/publish.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testConfigs.php
and further simplify variable interpolation.
This simplifies later additions of new os-arch combinations.
I expect that this will change the labels and URLs of test reports accordingly, for example in
https://download.eclipse.org/eclipse/downloads/drops4/I20241025-1840/
But I assume that's not a problem, is it?
@akurtakov or @iloveeclipse or anybody else do you have any objections or do you anything that could be missing?
I tested locally that the changes in how to apply the variables in the job configs leads to the desired results, so from my side this is ready.
=> [I-Build] Unify test job names to schema os-arch-javaVersion

production/testScripts/runTests2.xml
All usages depending on the 'testPlatform' variable don't distinguish between architectures.
In case it is attempted to run the tests on a unsupported arch, checking the architecture too produces an explicit error message instead of just having a download that fails because the corresponding artifacts are not available. But those that run I-builds locally or configure a new platform are usually well aware if the executing architecture is supported or not.
And testing for the arch just makes it more complicated to run tests on new platforms.
This helps for example for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/577.
=> [I-Build-Test] Remove CPU-arch as criterion for testPlatform property

production/testScripts/configuration/sdk.tests/testScripts/test.xml
in testScripts/test.xml. The version checks are either always fulfilled nowadays or not used and not updated anymore.
=> [I-Build-Tests] Remove irrelevant determination of Java compliance level

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/logs.php, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/utilityFunctions.php
The underscore in 'x86_64' is still part of the first part, the 'job-name' part, of the configuration label.
Therefore the only the first underscore after x86_64 should be considered as delimiter.
Additionally improve dynamic adaption of listing of log files.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2494 (at least it should).
This will also fix the wrong display of label line breaks. The wrong break-up is also the cause for the wrong numbers because, because simplify speaking, the test-result folder name must start with the 'first line' of the label to be considered a match.
Therefore the jobnames for the linux test-configs are all the same and the first one in the file-system is used for all Linux configs:
=> [I-Build] Fix test result summary configuration label break-up

production/testScripts/runTests2.xml
For the generated `testProperties.php` I couldn't find any reference.
And although the file is indexed with a size of 1.4kB I cannot see any content and if I try to download it with curl it's empty:
- https://download.eclipse.org/eclipse/downloads/drops4/I20241027-1800/testresults/ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/
- https://download.eclipse.org/eclipse/downloads/drops4/I20241027-1800/testresults/ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/testProperties.php
@akurtakov or @laeubi can you say more about this file or is it probably save to stop generating it?
=> Remove generation of unused testProperties.php file

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/testManifest.xml
For the eclipse downloads page at
https://download.eclipse.org/eclipse/downloads/
This unifies the labels for all offered products and artifacts:
- use '64-bit' instead of '64 bit version'
- always list x86_64 artifact first
- unify descriptions of artifacts for other CPU architectures
The current labels can for example be seen at
https://download.eclipse.org/eclipse/downloads/drops4/I20241028-0700/#EclipseSDK
The new labels would be
- `Windows (64-bit)`
- `Windows (64-bit for ARM)`
- `Linux (64-bit)`
- `Linux (64-bit for ARM)`
- `Linux (64-bit for Power PC)`
- `Linux (64-bit for RISC-V)`
- `Mac OSX (64-bit)`
- `Mac OSX (64-bit for ARM)`
Alternatively we could also add the architecture to for the x86_64 artifacts explicitly and label it `(64-bit for x86)`? But I still would list it first …
=> Unify labels for Eclipse products and SWT artifacts at eclipse-downloads

eclipse.platform.releng/bundles/org.eclipse.test/src/org/eclipse/test/AwtScreenshot.java
* On error exit with exit code 3
* add std.err to error message
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1518
=> [test] AwtScreenshot: better error handling

JenkinsJobs/AutomatedTests/I_unit_mac.groovy, JenkinsJobs/AutomatedTests/I_unit_win32.groovy, JenkinsJobs/PerformanceTests/ILR_perf_lin64.groovy, JenkinsJobs/PerformanceTests/ILR_perf_lin64_baseline.groovy, JenkinsJobs/PerformanceTests/I_perf_lin64.groovy, JenkinsJobs/PerformanceTests/I_perf_lin64_baseline.groovy, JenkinsJobs/SmokeTests/smoke_test_ppcle.groovy, JenkinsJobs/SmokeTests/smoke_test_win32.groovy, JenkinsJobs/YBuilds/Y_unit_mac64_java17.groovy, JenkinsJobs/YBuilds/Y_unit_macM1_java17.groovy, JenkinsJobs/YBuilds/Y_unit_win32_java17.groovy, production/testScripts/startTests.sh
@fredg02 or @heurtematte or anybody else, can you tell if `windows2012tests` authentication token is still useful?
I have the impression it is not.
=> [Build] remove windows2012tests authentication token from Jenkins jobs

JenkinsJobs/AutomatedTests/I_unit_linux.groovy, JenkinsJobs/AutomatedTests/I_unit_mac.groovy, JenkinsJobs/AutomatedTests/I_unit_win32.groovy, production/testScripts/configuration/sdk.tests/testScripts/runtests.bat, production/testScripts/configuration/sdk.tests/testScripts/runtests.sh, production/testScripts/configuration/sdk.tests/testScripts/runtestsmac.sh, production/testScripts/runTests2.xml, production/testScripts/test_runTests2.xml.sh
- Use curl instead of wget (the former seems to be available on more machines by default, but I'll very this).
- Remove unnecessary whitespace in print-out and just use
- Remove unnecessary print-outs and unnecessary variable references
=> [I-Build-Tests] Clean-up and unify test launch scripts

production/testScripts/configuration/sdk.tests/testScripts/test.xml
1. Unify archive name computation and make it less static
2. Don't guess os-ws-arch configuration, with the existing infrastructure os, ws and arch properties are explicitly specified anyways.
Additionally sanitize white-space.
This also helps for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/577
=> [I-Build-Tests] Simplify archive name computation and don't guess os, ws and arch

JenkinsJobs/AutomatedTests/I_unit_win32.groovy
Calling 'ant -diagnostics' on Windows somehow exists the bat script immediately. Call it in a sub-cmd-shell to workaround this problem until a completely correct solution is found.
=> [I-Build-Test] Fix call of ant-diagnostics on Windows machines

production/testScripts/configuration/sdk.tests/testConfigs/linux/testAll.sh, production/testScripts/configuration/sdk.tests/testConfigs/macosx/testAll.sh, production/testScripts/configuration/sdk.tests/testConfigs/windows/testAll.bat, production/testScripts/configuration/sdk.tests/testScripts/runtests.bat, production/testScripts/configuration/sdk.tests/testScripts/runtests.sh, production/testScripts/configuration/sdk.tests/testScripts/runtestsmac.sh
For current I-build tests java.ext.dir is never specified.
=> [I-Build-Tests] Remove unused consideration of Java extension directory

JenkinsJobs/AutomatedTests/I_unit_linux.groovy
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1664
See also https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5179
=> [I-Build-Tests] Use JDK23-EA for Linux-Java23 tests

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml
Refs : https://github.com/eclipse-platform/eclipse.platform.ui/pull/2411
Corresponding changes in  the workbench bundle in pom.xml in releng aggregator.
Tested locally and this is the only change that is required from releng aggregator.
=> Adjust bundle path to match platform ui change

JenkinsJobs/AutomatedTests/I_unit_linux.groovy
Follow-up for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2515
I have already replayed the current linux-java17 configuration to use the ubunut image for the smaller `ui` test-suite:
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep434I-unit-linux-x86_64-java17/21/
Once that has passed I'll create a follow-up run with the complete `all` suite to see if all tests pass, then I think this change is save enough to apply it to all other configs as well.
=> [I-Build-Tests] Run Linux tests on 'ubuntu-2404' image agent

eclipse-platform-parent/pom.xml
Requires https://github.com/eclipse-tycho/tycho/pull/4428.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2529
=> [Build] Don't set LIBARCHIVE.creationtime attribute in tar.gz archives

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.34/faq.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.34/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.34/recommended.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/eclipse_4_34_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.34/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.34/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.34/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_34_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Porting.xml
Migration guide for Eclipse 4.34 from 4.33
=> Migration guide for Eclipse 4.34 from 4.33

cje-production/P-build/buildproperties.txt, cje-production/Y-build/buildproperties.txt, cje-production/buildproperties.txt, eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list.txt, eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/api-tools-builder.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testResults.php
Not used in years and just complicate the scripts and stream opening procedures.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2555 .
=> Remove unused apifreeze releng scripts

.github/workflows/updateRelease.yml
With the new reusable workflow for automated version increments in pull-requests, introduced with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2352, it is not necessary anymore to bump versions in advance during release preparation or the enable bumping if the property 'compare-version-with-baselines.skip' is set to false. Everything now happens automatically and these elements can therefore be removed.
Removing these elements avoids partly duplicated configuration and generally reduced the amount of configuration.
=> [Builds] Remove elements unnecessary with the new version-bump workflow

.github/workflows/prepareRelease.yml, eclipse-platform-parent/pom.xml
Actually the both properties 'releaseNumberSDK' and 'releaseNumberPlatform' are always the same and even if the comment mentions they might be different at some time it is better to unify them until then.
Because of this there is now a new 'releaseVersion' defined as a single property.
=> Define a single property for the releaseVersion and use in property

.github/workflows/updateRelease.yml
That workflow now just updates `pom.xml` files.
@laeubi or do I oversaw something?
Follow-up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2387
=> Remove path-patterns not changed anymore by updateRelease-workflow

scripts/newReleasePrep.sh
Since https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2560 the cleanup aproved api list task is no longer needed (actually it wasn't for years).
=> Remove useless step from newReleasePrep.sh

eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/api-tools-builder.xml
It has been removed with
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2560 as it was not configured to do anything for years.
=> Do not call removed dofreezereport task

eclipse-platform-parent/pom.xml, eclipse-platform-parent/saveproperties/mavenproperties.properties
From the three declared Eclipse CBI plugin repositories only the maven-plugins with groupId 'org.eclipse.cbi.maven.plugins' are obtained. And at least with respect to these mavne-plugins, the repository at 
- https://repo.eclipse.org/content/repositories/cbi
seems to be the combination of the co-located repositories:
- https://repo.eclipse.org/content/repositories/cbi-releases
- https://repo.eclipse.org/content/repositories/cbi-snapshot
Therefore it seems unnecessary to declare all three repositories.
@akurtakov can you tell if my analysis and this change is correct or if not, can you tell who can tell?
=> [Build] Unify and clean-up list of declared CBI plugin-repositories

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt, eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/api-tools-builder.xml
Looking at
https://download.eclipse.org/eclipse/downloads/drops4/I20241126-0600/apitools/deprecation/apideprecation.html shows deprecations from Apache Commons IO which are irrelevant for the project as API stability for 3rd party libs can not be guaranteed thus add commons-io to the excluded list and pass the list to apitooling.apideprecation ant task.
=> Do not report deprecations for 3rd party libs

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/logs.php, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/perflogs.php, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testResults.php
Javadoc failures break the build for some time and no separate log files are kept for later inspection.
=> Remove links to non existing javadoc logs

JenkinsJobs/Releng/createMaintenanceBranch.groovy, JenkinsJobs/Releng/tagEclipseRelease.groovy, cje-production/mbscripts/mb110_tagBuildInputs.sh, cje-production/promotion/makeVisible.sh
No longer used so these sed calls just make scripts more complex.
=> Remove remnants from git.eclipse.org

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/pom.xml
Fixes warnings in the log like:
```
12:44:26  [WARNING] Parameter 'includePackedArtifacts' is unknown for
plugin 'target-platform-configuration:4.0.10:target-platform
(default-target-platform)'
12:44:26  [WARNING] Parameter 'includePacked' is unknown for plugin
'tycho-p2-extras-plugin:4.0.10:mirror (mirror-org.eclipse.platform)'
12:44:26  [WARNING] Parameter 'includePacked' is unknown for plugin
'tycho-p2-extras-plugin:4.0.10:mirror
(mirror-org.eclipse.platform.source)'
```
=> Remove unknown parameters from mojos

JenkinsJobs/SmokeTests/smoke_test_opensuse_leap.groovy, JenkinsJobs/SmokeTests/smoke_test_ppcle.groovy, JenkinsJobs/SmokeTests/smoke_test_ubuntu.groovy
Maybe this helps to fix some of the smoke-test failures.
=> [Build] Fix reference to secManager parameter in smoke test jobs

production/testScripts/runTests2.xml
This fixes the regression that the the <testedPlatform>_consolelog.txt is created at the wrong location.
It was missed that the <testedPlatform>_consolelog.txt file was created in the executionDir (because the scripted inlined ran in that directory) in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2516
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2516#issuecomment-2509795054
=> [Build] Create consolelog.txt file in test execution directory again

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
Clears
```
biz.aQute.bndlib(7.1.0)
DEPRECATED	aQute.bnd.build.model.BndEditModel#boolean isCnf()
DEPRECATED	aQute.bnd.build.model.BndEditModel#void
setIncludeResource(List<String>)
DEPRECATED	aQute.bnd.build.model.BndEditModel#void setProject(Project)
DEPRECATED	aQute.bnd.osgi.Constants#INCLUDE_RESOURCE
```
from deprecation reports e.g.
https://download.eclipse.org/eclipse/downloads/drops4/I20241201-1800/apitools/deprecation/apideprecation.html
=> Do not report 3rd party deprecations in I-builds

JenkinsJobs/Builds/I_build.groovy, RELEASE.md, cje-production/mbscripts/mb300_gatherEclipseParts.sh, eclipse-platform-parent/pom.xml
Use the latest ECJ snapshot version from the last successful I-build (without comparator errors) for verification builds, to automatically align with I-builds.
Currently ECJ has to be deployed manually to a JDT snapshot-repository after changes in ECJ that caused comparator-errors:
- https://github.com/eclipse-pde/eclipse.pde/pull/1461#issuecomment-2466780430
This prevents issues like
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1960
- https://github.com/eclipse-pde/eclipse.pde/pull/1467
If there are no other usages of `https://repo.eclipse.org/content/repositories/eclipse-staging`, this should make the JDT Jenkins job to deploy ECJ to it obsolete
- https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/
as well as the target repository and should allow …
=> [Build] Use last successful ECJ snapshot in verification builds

RELEASE.md, eclipse-platform-parent/saveproperties/mavenproperties.properties
Keeping that variable fails the I-build because is is not used and not defined anymore since https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2538.
This should fix the failure of `4.35 I-Build: I20241202-1800`:
```
BUILD FAILED
/home/jenkins/agent/workspace/Builds/I-build-4.35/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/
eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/eclipse_compare.xml:29:
Property cbi-jdt-repo.url was circularly defined.
```
=> [Build] Remove now unused 'cbi-jdt-repo.url' from mavenproperties

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
Changing the version of SDK4Mvn.aggr from 4.34 to 4.35-I-Builds post publishing to maven central.
Refs: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2606
=> Changing version from 4.34 to 4.35-I-Builds

JenkinsJobs/YBuilds/Y_unit_cen64_gtk3.groovy
This aligns the configuration with I-build tests for Linux and is also necessary due to the increased requirements of the latest SWT, that doesn't work on CentOS-8 anymore.
See also https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2899#issuecomment-2515442425.
=> [Y-Build-Tests] Run Linux tests on default 'ubuntu-2404' agent

JenkinsJobs/YBuilds/Y_build.groovy, JenkinsJobs/YBuilds/Y_unit_linux.groovy, JenkinsJobs/YBuilds/Y_unit_mac.groovy, JenkinsJobs/YBuilds/Y_unit_win32.groovy, cje-production/Y-build/publish.xml, cje-production/Y-build/testConfigs.php
This simplifies later additions of new os-arch combinations.
This is similar to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2481, just for Y-build tests.
=> [Build] Unify Y-build test job names to schema os-arch-javaVersion

JenkinsJobs/YBuilds/Y_unit_linux.groovy, JenkinsJobs/YBuilds/Y_unit_mac.groovy, JenkinsJobs/YBuilds/Y_unit_win32.groovy
and slightly clean-up existing pipeline for linux. 
Unify numbers like time-outs and numbers of retained builds.
This is similar to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2004, just for Y-build tests.
=> [Y-Build-Tests] Define Mac and Windows jobs as Jenkins-pipeline

JenkinsJobs/YBuilds/Y_unit_linux.groovy, JenkinsJobs/YBuilds/Y_unit_mac.groovy, JenkinsJobs/YBuilds/Y_unit_win32.groovy
- Simplify environment variable definitions and tool handling
- Remove unnecessary print-outs and whitespace
- Remove unused or unnecessary parameters and property definitions
This contains many elements also applied to I-build tests in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2491.
=> [Y-Build-Tests] Simplify and unify job definitions

JenkinsJobs/SmokeTests/smoke_test_arm64.groovy, JenkinsJobs/SmokeTests/smoke_test_centos9.groovy, JenkinsJobs/SmokeTests/smoke_test_opensuse_leap.groovy, JenkinsJobs/SmokeTests/smoke_test_ppcle.groovy
and simplify the definition of kubernetes-agents by inheriting the base configuration from the 'basic' image.
=> [Build] Unify all smoke test job configurations to be Jenkins-pipelines

JenkinsJobs/SmokeTests/StartSmokeTests.jenkinsfile
Remove unnecessary print-outs and simplify the download and installation of the executing JDK.
Also use a downsized 'basic' agent to trigger the executions on specific test-agents. It's not necessary to occupy for 4GiB of precious memory while just waiting for the test-agents to complete.
=> [Build] Simplify setup and execution script for smoke tests

JenkinsJobs/SmokeTests/StartSmokeTests.jenkinsfile
This makes changes, e.g. using other java versions or adding a new platform simpler.
This also has the effect that ppc64le is now also tested with Java-21 and 23.
=> [Build] Use Jenkins matrix to define setup combinations in smoke tests

JenkinsJobs/SmokeTests/StartSmokeTests.jenkinsfile
Smoke tests are launched by I-builds and Y-builds and their results are currently not stored elsewhere. Therefore we should keep 10 old runs instead of just five.
=> [Build] Double number of kept smoke test runs

JenkinsJobs/AutomatedTests/I_unit_linux.groovy, JenkinsJobs/AutomatedTests/I_unit_mac.groovy, JenkinsJobs/AutomatedTests/I_unit_win32.groovy, JenkinsJobs/YBuilds/Y_unit_mac.groovy, JenkinsJobs/YBuilds/Y_unit_win32.groovy
- Simplify custom JDK download in I-builds on Linux with Java-23 by using the same approach like for Y-builds
- Remove unnecessary '-Dargs=all' property definition for Windows and unnecessary environment variable resets on Mac.
=> [Build] Further simplify and unify I/Y-build test job configurations

.github/workflows/updateRelease.yml
Product files also need to be updated.
=> Adding *.product file for update release.

Jenkinsfile
This ensures that releng scripts are always updated on the download-server as soon as they change in the git repository. Furthermore this avoids the need for the separate Jenkins job to deploy the scripts, thus making
https://ci.eclipse.org/releng/job/Publish_shell_scripts_for_releng_jobs/ obsolete (can be deleted once this is submitted).
=> [Build] Deploy RelEng scripts in master branch build

JenkinsJobs/SmokeTests/FOLDER.groovy, JenkinsJobs/SmokeTests/StartSmokeTests.jenkinsfile
Defining them only in the pipeline has the effect that the jobs forgets it's parameter each time the job-configuration is recreated by the seed-job and thus the subsequent first execution of the smoke-test fails because it has 'forgotten' it's parameters and has to re-discover them on the first pipeline execution again.
Follow-up on
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2637
=> [Build] Define all smoke-test parameters in job definition again

JenkinsJobs/AutomatedTests/I_unit_linux.groovy, JenkinsJobs/AutomatedTests/I_unit_mac.groovy, JenkinsJobs/AutomatedTests/I_unit_win32.groovy, JenkinsJobs/SmokeTests/StartSmokeTests.jenkinsfile, JenkinsJobs/YBuilds/Y_unit_linux.groovy, JenkinsJobs/YBuilds/Y_unit_mac.groovy, JenkinsJobs/YBuilds/Y_unit_win32.groovy
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2623
@merks do you think we should explicitly disallow the security-manager or just remove the argument to explicitly enable it?
Since Java-18 the default value of the `java.security.manager` property is  `disallow` as part of [JEP-411](https://openjdk.org/jeps/411):
- https://bugs.openjdk.org/browse/JDK-8270380
In order to make the builds a bit simpler I would be in favor to just remove the `java.security.manager` argument. With that only the Java-17 tests would run with enabled security-manager and all others would have it disabled. And Java-17 will probably not last long any-ways.
Btw. I have replayed a I-build test with explicit disallowed security-manager in order to test in advance if everything …
=> [Build] Disallow Java security-manager in all I-/Y-/Smoke-tests

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
- Lucene 10 requires Java 21, so the SDK product should indicate it requires Java 21.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2654
=> Update target platform to lucene 10.

JenkinsJobs/AutomatedTests/I_unit_win32.groovy, JenkinsJobs/Builds/I_build.groovy, cje-production/scripts/publish.xml
* Do not start Linux Java 17 tests
* Rename Windows tests to Java 21 to match version used
* Publish correct test results
=> Adjust jenkins scripts for Java 21

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Guide.xml
Many years ago Activites weren't support in e4. That has long since been resolved and when the "not currently in 4.1" note was removed from the main help page in commit 5f66a3ea1ea9e71c32ce4fa63b5148530165bf16 the same update was not made to the table of contents.
=> Remove out of date compatibility note

eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/images/org.eclipse.ui.editors/etool16/next_nav.svg, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/images/org.eclipse.ui.editors/etool16/prev_nav.svg, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/pom.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/images/next_nav.svg, eclipse.platform.common/bundles/org.eclipse.platform.doc.user/images/prev_nav.svg
Fix Icons according to Eclipse UI guideline.
Left and top pixel row should stay empty according to the guideline.
Also: make the "document" in the "wordwrap" and the "block_selection_mode" icon the same hight as they are shown next to each other in the toolbar.
=> Fix Objects inside Icons

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.p2.inf, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
- Define an unconfigure touchpoint to remove -Djava.security.manager=allow from the eclipse.ini which is done to ensure that updates will leave installations in a state that can run with Java 24.
- Do the above for both products and ensure that both products specify -Dosgi.requiredJavaVersion=21
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2623
=> Remove -Djava.security.manager=allow from the products

.github/workflows/licensecheck.yml
Reverts eclipse-platform/eclipse.platform.releng.aggregator#2674
Now that https://github.com/eclipse-dash/dash-licenses/pull/423 is submitted, this should not be necessary anymore.
=> Revert "Run licensecheck with Java 21"

eclipse-platform-parent/pom.xml
Now that all tests can handle a disabled SecurityManger it doesn't have to be enabled by default anymore.
This reverts https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1941
=> Revert "Add java security properties for surefire"

JenkinsJobs/Builds/DockerImagesBuild.jenkinsfile, cje-production/dockerfiles/centos-gtk4-mutter/9-gtk4/Dockerfile, cje-production/dockerfiles/debian/swtnativebuild/Dockerfile, cje-production/dockerfiles/opensuse-gtk3-metacity/15-gtk3/Dockerfile
Install git on all docker-images, which is a prerequisite for
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2609
Install `procps` package in all docker-images for smoke-tests. The 'procps'-package contains the pkill command which is currently
missing according to the smoke-tests logs. Part of
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2642
=> Install git and `procps` package in all docker-images

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testConfigs.php
Follow-up on
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2667
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2666
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2670
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2680
=> [Build] Adapt initial testConfigs.php to move of test-builds to Java-21

JenkinsJobs/SmokeTests/StartSmokeTests.jenkinsfile
The Eclipse SDK starts to require Java-21 and all other tests are just executed on at least Java-21
=> [Build] Drop execution of smoke-tests with Java-17

JenkinsJobs/SmokeTests/FOLDER.groovy, JenkinsJobs/SmokeTests/StartSmokeTests.jenkinsfile
Always archiving artifacts help to debug failures. Avoiding to use a 'main'-agent to just start all test-configurations running on other machines saves precious resources in the Jenkins instance while waiting for the tests to complete.
Additionally simplify post build result notifications.
Part of
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2642
=> [Build] Always archive artifacts in smoke-tests and use no main agent

JenkinsJobs/AutomatedTests/I_unit_linux.groovy, JenkinsJobs/YBuilds/Y_unit_linux.groovy
For the Linux Y-Build for Java-24 the latest Temurin early-access build is downloaded.
=> [Build] Use pre-installed Temurin JDKs in I-/Y-build tests on Linux

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/extension-points/index.html
They have been missed to be added to the docs when added.
=> Add generic editor extension points to docs

JenkinsJobs/YBuilds/Y_build.groovy
instead of to a fixed lists of interested people.
As people and their interest may come and go it's simpler to not have a fixed list of people to which notifications are send.
@jarthana, @mpalat or @stephan-herrmann, what do you think?
=> [Build] Send Y-build results to jdt-dev mailing-list

JenkinsJobs/Builds/I_build.groovy
Current the 'COMPARATOR_ERRORS_SUBJECT' environment variable always contains a line-break, even if otherwise 'empty' (indicating no comparator-error). Trimming the value in the condition removes any leading/trailing white-space.
Follow-up on:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2538
@merks, @akurtakov IIRC we had issues due to not deployed Maven-snapshots (of ECJ)? This was probably the cause because since the changed mentioned above snapshots were not published anymore.
=> [Build] Fix condition of maven-snapshot publication step

JenkinsJobs/Builds/I_build.groovy, JenkinsJobs/Releng/collectPerfResults.groovy, JenkinsJobs/Releng/collectResults.groovy, JenkinsJobs/YBuilds/Y_build.groovy, JenkinsJobs/YBuilds/collectYbuildResults.groovy, cje-production/mbscripts/mb010_createEnvfiles.sh, cje-production/scripts/publish.xml
Because in the 'Collect Result' jobs the publish.xml ANT script is executed remotely on the download-server via SSH the environment variables defined in the shell on the build-server are not available. As a workaround, define the 'testsConfigExpected' property explicitly as command-line argument.
Also rename 'TESTS_CONFIGURATIONS_EXPECTED' to
'TEST_CONFIGURATIONS_EXPECTED' to avoid a double-plural.
Follow-up to
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2693
=> [Build] Fix export of 'TEST_CONFIGURATIONS_EXPECTED' in SSH execution

eclipse-platform-parent/pom.xml
Especially for
- https://github.com/eclipse-tycho/tycho/pull/4561
this will hopefully fix or make it less likely that API analysis fails in verification builds. Beside that there are some pending changes that could have an impact to platform builds so it would be better to make sure everything works until the next release.
=> Use 4.0.11-SNAPSHOT in the build

eclipse-platform-parent/pom.xml
Now that there is Java 21 content this would allow such code to be accepted.
Additionally, maven-javadoc-plugin uses that to decide which Java version to link javadoc to aka with this change String will link to Java 21 and not Java 17.
=> Switch javadoc source to 21

JenkinsJobs/Builds/build.jenkinsfile
- Declare ANT as top-level tool instead of multiple `withAnt()` steps
- Use dir-step and leverage `CJE_ROOT` environment variable to change the working directory
- Use `readProperties()` step to read build-properties and trim them immediately after reading
- Remove duplicated environment variable exports
- Replace duplicated `BUILD_VERSION` env-variable by `RELEASE_VER`
- Remove unused environment variables `POM_UPDATES_SUBJECT` and `POM_UPDATES_BODY`, which are left-overs of Bug 578179 respectively commit 6a93348887705263333e7748a8c3f5f3cce3d82a
- Send plain-text mails instead of HTML content to simply the creation of the mail body.
- Simplify references to variables in Groovy string-templates.
- Remove unnecessary initial `cleanWs()` step. The build runs inside a kubernetes-container …
=> [Build] Simplify and clean-up I/Y-build Jenkins pipeline

JenkinsJobs/Builds/FOLDER.groovy, JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/JobDSL.json, JenkinsJobs/YBuilds/FOLDER.groovy, RELEASE.md
and restore ability to define I/Y-builds jobs for other branches, only through the job definition.
This ability was lost for I-builds in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2709. For maintenance branches the `build.jenkinsfile` would have to be modified directly, like it is done for Y- and P-builds.
Furthermore use the error() step instead of throwing an 'IllegalStateException' because the latter doesn't always seem to be permitted.
=> [Build] Use default declarative checkout for I/Y-builds

JenkinsJobs/YBuilds/collectYbuildResults.groovy
Don't use xvnc, which is not available on the 'basic' agent and also not necessary (for a headless build task) [1].
Use The unified  'cje-production/scripts/publish.xml' ANT script. The script customized for Y-builds is not necessary anymore since [2].
Follow-up for
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2611 [1]
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2693 [2]
=> [Build] Fix Y-Build test result collection

JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/Releng/publishToMaven.jenkinsfile
Restore the previous (correct) definition of the 'snapshotOrRelease' parameter.
Follow-up on
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2718
=> [Build] Fix invocation of 'PublishToMaven' job from I-build job

JenkinsJobs/Releng/publishToMaven.jenkinsfile
- Make scripts easier to understand for Java-programms that aren't UNIX-shell/bash experts.
- Separate the eclipse.platform.releng.aggregator repository clone from the working directory into a separate folder.
I'm also contemplating to move the validation into the matrix to avoid defining the list of projects twice. Performance-wise this doesn't make a difference but further simplifies the configuration a bit.
The only downside is that, if the validation only fails for one project (e.g. jdt) then the other projects would likely still be published. On the other hand if there is a validation error it it's probably systematic and the validation probably fails for all projects.
=> [Build] Simplify verification of Maven artifacts to publish

JenkinsJobs/Releng/publishToMaven.jenkinsfile
Using Maven-deamon reduces the runtime of the repository validation from ~14min to ~1.5min and the publication steps for the different projects from ~23min respectively ~5min to ~9min respectively ~2min.
Overall the runtime is reduced from ~42min to ~16min.
=> [Build] Use Maven-deamon to speed up Maven artifact publication

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
Fixes the
org.apache.lucene.core(10.1.0)
DEPRECATED	org.apache.lucene.search.TopFieldCollectorManager#TopFieldCollectorManager(Sort, int, FieldDoc, int, boolean)
DEPRECATED	org.apache.lucene.search.TopScoreDocCollectorManager#TopScoreDocCollectorManager(int, ScoreDoc, int, boolean)
DEPRECATED	org.apache.lucene.util.Version#LUCENE_9_12_0 in e.g. https://download.eclipse.org/eclipse/downloads/drops4/I20250108-0430/apitools/deprecation/apideprecation.html
=> Exclude deprecations in lucene.core from reporting

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
We should not report 3rd party deprecations as there is no API promise for them.
Fixes commons-beanutils appearing in the report after https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/d9a1570180e013c7b4fe208a9ccc035cd27cf3e6
=> Exclude commons-beanutils from deprecation report

JenkinsJobs/YBuilds/Y_unit_tests.groovy
The openjdk and temurin early-access builds for Java-24 differ.
As requested in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3228#issuecomment-2580579288.
=> [Y-Build] Use openjdk-24-ea+31 for tests under linux-java24

JenkinsJobs/Releng/publishToMaven.jenkinsfile, eclipse-platform-parent/pom.xml
Passing the 'MAVEN_GPG_PASSPHRASE' as environment variable fixes many build warnings:
'''
[WARNING] Do not store passphrase in any file (disk or SCM repository),
[WARNING] instead rely on GnuPG agent or provide passphrase in
[WARNING] MAVEN_GPG_PASSPHRASE environment variable for batch mode.
'''
Additionally using the Bouncy Castle (BC) signer is not only faster but also simplifies the setup as it can use the keyring in armored form and thus avoids the import step.
=> [Build] Apply best practices to Maven artifact singing and use BC-signer

Jenkinsfile
Removing that property definition was forgotten in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2140
=> [Build] Remove unnecessary 'gpg.passphrase' property in master build

JenkinsJobs/Releng/publishToMaven.jenkinsfile
This leverages the ability to launch multi-file source-code programs add in Java-22 via JEP-458:
- https://openjdk.org/jeps/458
Technically it's not a problem to use JDK-23 or 24 (as soon as it's released) in this internal part of the build, yet I still hesitate with this because I worry a bit that it might be forgotten to update the JDK tool as soon as the non-LTS releases are out of maintenance since we usually don't use them anywhere else and it's therefore not on our TODO-list.
=> [Build] Launch EnrichPom.java as source program in Maven publication

eclipse.platform.releng.tychoeclipsebuilder/eclipse/extras/produceChecksum.sh, eclipse.platform.releng.tychoeclipsebuilder/eclipse/helper.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/buildproperties.phpHoldForLocalTests, eclipse.platform.releng.tychoeclipsebuilder/equinox/helper.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox/publishingFiles/templateFiles/index.template.php
The checksum signature is gone since:
https://archive.eclipse.org/eclipse/downloads/drops4/R-4.16-202006040540/
This is caused by a failure in the signing process because recent versions of GPG ask for the passphrase via a dialog by default. In order obtain it through a environment variable one has disable pinentry using: --pinentry-mode loopback
- Remove unnecessary specification of '--yes' option.
- Remove attempt to read 'bashUtilities.shsource' as it seems to have been gone in general.
- specify the 'client' through a environment variable in the caller
=> [Build] Fix signing of the artifact-checksums list on download page

JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/YBuilds/P_build.groovy, cje-production/P-build/mb220_buildSdkPatch.sh, cje-production/mbscripts/mb011_loadPGPKeys.sh, cje-production/mbscripts/mb220_buildSdkPatch.sh, eclipse.platform.releng.tychoeclipsebuilder/eclipse/extras/produceChecksum.sh, eclipse.platform.releng.tychoeclipsebuilder/pom.xml
Importing the secret-key is not necessary when signing with the bouncy-castle signer. Therefore just import the key where the `gpg` executable is used (i.e. when signing the list of artifact checksums).
=> [I/Y-Build] Simplify GPG-signing in I/Y-builds

JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/YBuilds/P_build.groovy
1. Remove unnecessary 'unset' of empty environment variables
2. Remove use of obsolete SSH-agent for git.eclipse.org
3. Unify and fix artifact archiving and make it more specific
The archiving step in case of build-failures resulted in no artifacts being archived.
=> [I/Y/P-Build] Various minos clean-ups of I/Y/P-Builds

JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/Builds/markStable.groovy, JenkinsJobs/Builds/markUnstable.groovy, JenkinsJobs/Releng/makeVisible.groovy
Update or fix all invocations of a 'update-download-index' job to invoke `Releng/updateIndex`, because its definition is under version-control. The other previously referenced jobs are either manually defined/maintained (with equal definition) or don't exist.
This fixes the index-update for the `Mark (Un)Stable` and `Make Visible` job and allows to delete the manually defined `eclipse.releng.updateIndex` job:
- https://ci.eclipse.org/releng/job/eclipse.releng.updateIndex/
=> [Build] Fix and unify invocations of 'update-download-index' job

eclipse-platform-parent/pom.xml
Tycho has a [new mojo to check dependency ranges](https://github.com/eclipse-tycho/tycho/blob/main/RELEASE_NOTES.md#new-check-dependencies-mojo) this adds a new profile `dependency-check` to activate / execute this mojo, currently this is just the plugin execution itself but we maybe later add more options when things evolve.
=> Add new profile dependency-check to verify dependency ranges

JenkinsJobs/PerformanceTests/FOLDER.groovy
Rename the performance-tests job to have the abbreviation '-perf-' in its name because the scripts that collect its results rely on it.
Follow-up on
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2697
=> [Build] Fix the collection of results for performance-tests

.mvn/jvm.config, JenkinsJobs/Builds/build.jenkinsfile, Jenkinsfile, cje-production/buildproperties.txt
This avoids confusion which value is actually used and allows to reduce the memory demand of the container used for I-builds.
Defining it in the corresponding pipeline allows fine-tuning for the circumstances of the corresponding build and it's settings.
I'll have to verify in an experiment that we can really reduce the memory-limit of the container used for I-builds.
=> [Build] Define max heap size for Maven only via environment variables

eclipse-platform-parent/pom.xml
With the reusable workflow for automated version increments in pull-requests it is not necessary anymore to enable bumping versions if the property 'compare-version-with-baselines.skip' is set to false. Everything now happens automatically and this profile can therefore be removed.
This is extracted from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2387#discussion_r1784365777.
=> [Builds] Remove unused 'version-bump' profile from eclipse-parent pom

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
In latest I-build report there are:
```
bcpg(1.80.0)
DEPRECATED	org.bouncycastle.openpgp.operator.PublicKeyKeyEncryptionMethodGenerator#WILDCARD
DEPRECATED	org.bouncycastle.openpgp.operator.PublicKeyKeyEncryptionMethodGenerator#PublicKeyKeyEncryptionMethodGenerator
setUseWildcardKeyID(boolean)
bcprov(1.80.0)
DEPRECATED	org.bouncycastle.asn1.x509.DeltaCertificateDescriptor#ASN1Sequence
getValidity()
DEPRECATED	org.bouncycastle.asn1.x509.DeltaCertificateDescriptor#DeltaCertificateDescriptor
trimTo(TBSCertificate, Extensions)
DEPRECATED	org.bouncycastle.asn1.x509.ExtensionsGenerator#void
addExtension(Extensions)
DEPRECATED	org.bouncycastle.crypto.digests.AsconDigest
DEPRECATED	org.bouncycastle.crypto.digests.AsconXof
DEPRECATED	org.bouncycastle.crypto.engines.AsconEngine
```
seen at …
=> Do not generate deprecation report for bouncycastle jars

.github/workflows/checkDependencies.yml
Currently the job fails for bundles that do not generate a report, as this is not an error, we skip the PR creation if the step did not created any report.
=> Skip PR creation if no report was produced

eclipse-platform-parent/pom.xml
Since a while we have new API Tools check in the IDE and there where no complains, so it seems time to enable this in the verification builds as well to capture potential problems before the final release.
=> Use current i build API tools

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
Cleans up the report which is today
(https://download.eclipse.org/eclipse/downloads/drops4/I20250123-1800/apitools/deprecation/apideprecation.html ) mostly deprecations from this project.
Report should contain only bundles developed by the project.
=> Exclude Apache Httpclient 4 from deprecation reports

eclipse-platform-parent/pom.xml
This allows to individually configure the mojos and call them on the CLI e.g. with mvn tycho-cleancode:quickfix@quickfixes without further parameters.
Also unifies some tab versus whitespace.
=> Use named executions to configure cleanups/quickfixes

.github/workflows/checkVersions.yml
That way it should be possible to use it for equinox by using:
`extra-maven-args: '-f bundles'`
then at laest it will already work for the bundles (that don't seem to need the binary repo), also useful for other use cases (e.g. enable extra checks or similar)
=> Add support for supply extra maven args

oomph/Platform.setup
- Remove the ssl text modification because the ssl projects are no longer imported.
=> Modify ECF setup to eliminate API errors

.github/workflows/README.MD, .github/workflows/callUpdateTarget.yml, .github/workflows/updateTarget.yml, eclipse-platform-parent/pom.xml
The workflow to update the target file is quite convenient and proven to work well.
This now moves the configuration into the pom and makes the workflow a shared one so it can be used in other projects easily.
=> Make Update target a shared workflow and move configuration into pom

.github/workflows/cleanCode.yml
Currently we only have a Java 21 VM for the cleancode action but JDT works best with a real JVM (especially for those without a release option like Java 8), so this one install some more so they are available at the toolchains and can be discovered by Tycho to setup a JDT JRE in the cleanups.
=> Install more jvms for the cleancode action

JenkinsJobs/AutomatedTests/I_unit_tests.groovy
See also https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5603
@jukzi this relates to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1664 respectively https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2523 doesn't it?
=> [I-Build-Tests] Revert to installed temurin-jdk23-latest for Linux-J23

eclipse-platform-parent/pom.xml
Nowadays the 'build-individual-bundles' profile seems to be used for partial builds in sub-projects.
And there are no references to the removed profile nor the property referenced in it within the Eclipse SDK.
=> [Build] Remove unused 'partial-build' Maven profile

eclipse-platform-parent/pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2793
=> [Y-Build] Use latest Y-build repository as baseline for comparison

JenkinsJobs/Builds/DockerImagesBuild.jenkinsfile, cje-production/dockerfiles/debian/swtgtk3nativebuild/Dockerfile, cje-production/dockerfiles/debian/swtgtk3nativebuild/scripts/uid_entrypoint
To verify locally that this built a suitable eclipse/eclise*.so:
1. Add `USER 1000` to end of Dockerfile
2. in dir of Dockerfile `docker build --pull -t swtgtk3nativebuild .`
3. `EQUINOX=/scratch/eclipse/oomph/swt-master/git/equinox`
4. `LIBRARY_GTK=$EQUINOX/features/org.eclipse.equinox.executable.feature/library/gtk`
5. `docker run --rm -it -v$EQUINOX:$EQUINOX -w$LIBRARY_GTK swtgtk3nativebuild make -f make_linux.mak`
6. `make -f make_linux.mak install EXE_OUTPUT_DIR=#### LIB_OUTPUT_DIR=####`
8. Test eclipse works
7. run `objdump -R` on the exe and so to ensure no new glibc symbols
I don't know how to verify this on the build machine. Do we just merge it so that new images are available
Prerequisite of https://github.com/eclipse-equinox/equinox/issues/830
=> Add Docker image to build natives with older dependencies

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Required for
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1638
Contributes to
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/1438
=> Add jsvg 1.7.0 to eclipse-sdk target

.github/workflows/checkDependencies.yml
Currently the PR step is skipped if no report file is written, but then the delete branch option do not work.
This now creates a dummy description file so the PR job can always run.
=> Create a dummy description if no version problems are found

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml, eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
The final step of
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/423
=> Remove now unused Apache JXPath dependencies

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
... but not in the product ...
This way it can be installed from the site but is not available by default.
=> Include org.eclipse.equinox.slf4j in the repository

JenkinsJobs/Builds/build.jenkinsfile
=> [I/Y-build] Change mail subject if build is skipped to lower-case

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.35/faq.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.35/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.35/recommended.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/eclipse_4_35_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.35/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.35/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.35/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_35_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Porting.xml
Migration guide for Eclipse 4.35 from 4.34
=> Migration guide for Eclipse 4.35 from 4.34

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
Cleans irrelevant entries as can be seen at
https://download.eclipse.org/eclipse/downloads/drops4/I20250305-1800/apitools/deprecation/apideprecation.html
=> Exclude JUnit bundles from deprecation report

eclipse-platform-parent/pom.xml
Needed in order to reduce hard coded years (e.g. in generated javadoc).
=> Split releaseYear in its own property in parent

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml
Using https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2897 it will remove the need to update it (which has been forgotten during the whole 2024 - it's still 2023 in our 2025-03 release).
=> Set copyright year to release year in javadoc

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
Publish to Maven central 4.35
Update SDK4Mvn.aggr file (`properties.sh` file was removed in a previous commit related to updating maven job https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/a999440157c01973facfce4e69c48d19fe0d3961)
Refs: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2889
cc/ @MohananRahul @merks
=> Publish 4.35 to maven central

Jenkinsfile
- The infocenter war is building in parallel typically with infocenter product assembly and this randomly runs out of heap space, so with a little more heap available we should avoid this problem.
=> Increase MAVEN_OPTS = '-Xmx3300m' to avoid out-of-memory building war

JenkinsJobs/Releng/checkCompositesValidity.groovy
Has been failing since "June 12, 2024" but went unnoticed as it was sending mails to Sravan only.
Problem was it tried to run with Java 11 but now Java 21 and during the whole period Java 17 was needed.
=> Fix checkCompositesValidity

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
Changing the version of SDK4Mvn.aggr from 4.35 to 4.36-I-Builds post publishing to maven central.
Refs: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2889
=> Changing version from 4.35 to 4.36-I-Builds

eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/pom.xml, eclipse.platform.common/bundles/org.eclipse.jdt.doc.user/reference/preferences/java/editor/ref-preferences-folding.htm
This PR contains the help page update for https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1825.
=> add preference help for custom folding regions

JenkinsJobs/Releng/collectResults.groovy
Should fix annoying and big "Releng: Missing testManifest.xml Files" section on downloads page.
=> Supply testManifest file name directly

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html
The eclipse.appName sytem property allows users to specify on the command line the appName to be used for a specific Eclipse instance. The appName Display property is used by window managers and desktop environments for identification and grouping. This is helpful to distinguish Eclipse instances (e.g., JDT vs CDT) as per default these all are using the same identifier.
Eclipse UI PR:
https://github.com/eclipse-platform/eclipse.platform.ui/pull/2631 
Root Issue: eclipse-packaging/packages#253
=> Add documentation for the added eclipse.appName System Property

eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml
The SVG fragment needs to be available in SDK tests product as SWT tests require that fragment and the SDK does not currently not include it.
=> Add SWT SVG fragment to SDK tests feature

.mvn/jvm.config
These extra outputs clutter the build output and make it harder to find and analyze problems.
Such options should be enable temporarily when issue is analyzed and removed after that.
=> Reduce noise in the build output

eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml
The SVG fragment needs to be available in SDK tests product as SWT tests require that fragment and the SDK does not currently not include it. The transitive dependency to the JSVG bundle has been missing and is added by this change.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/1944
=> Add JSVG bundle to SDK tests feature

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
Based on content of
https://download.eclipse.org/eclipse/downloads/drops4/I20250403-1800/apitools/deprecation/apideprecation.html , these jetty bundles are not something the project can claim API stability thus excluding from the list.
=> Add more bundles for which to not show deprecations

eclipse-platform-parent/pom.xml
It's not used and only generates churn in the repo to keep jacoco plugin uptodate (as in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2965 )
=> Remove jacoco profile

eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/library.xml, eclipse.platform.releng/bundles/org.eclipse.releng.tests/META-INF/MANIFEST.MF, eclipse.platform.releng/bundles/org.eclipse.releng.tests/pom.xml, eclipse.platform.releng/bundles/org.eclipse.releng.tests/test.xml
All usages of the `PLUGIN_PATH` system-property have been removed and that property and it's definition ANT property `plugin-path` can be removed.
This is the completion of the following PRs that have made the final removals of remaining usages of the `PLUGIN_PATH` system-property:
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/2024
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/2039
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/2931
=> [Build] Remove definition PLUGIN_PATH system-property for I-build tests

JenkinsJobs/Builds/markBuild.groovy, cje-production/mbscripts/mb620_promoteUpdateSite.sh, cje-production/promotion/makeVisible.sh, production/testScripts/updateTestResultsPages.sh
Adding a new I-build to the I-build composite seems to not work at the moment and running Eclipse to perform the addition with Java-17 although the Eclipse-SDK/Platform products now require Java-21 could be a cause.
A Java-21 JDK was installed via
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5780
I'm not entirely sure the addition started to fail with the latest I-build, but after running the [Mark Stable](https://ci.eclipse.org/releng/job/Builds/job/markStable/) job, modified to use Java-21, it worked. Running it explicitly previously with Java-17 didn't add the build to the composite.
Maybe this was also just a caching issue at the storage-server, but still this change should be applied.
=> [Build] Always run Eclipse at the storage-server with Java-21

.github/actions/install-maven-parent-action/action.yml, .github/workflows/checkVersions.yml, .github/workflows/codeQLworkflow.yml, .github/workflows/mavenBuild.yml
In order to mitigate the current outage of the EF-hosted storage, which will probably continue to block builds for at least a few days (https://www.eclipse.org/lists/eclipse.org-committers/msg01493.html) this implements a quick-fix to avoid the need for said EF infrastructure for the shared GitHub workflows. This is achieved by the following actions:
- Obtain the eclipse-parent pom.xml and the sdk.target project from the GH repository and install it within the build into the local Maven cache
- Revert Tycho to use it's latest release 4.0.12, which is available from Maven-Central
Especially the latter could cause problems for builds that rely on the new features only available in Tycho 4.0.13-SNAPSHOT. Therefore this is currently designed as opt-in feature.  But looking at …
=> [Build|GH] Add quick-fix to avoid need for EF-infrastrucutre

.github/workflows/codeQLworkflow.yml, .github/workflows/mavenBuild.yml
In the shared GH workflows use long option names to be more readable.
Also don't fail the build on test-failures because the the additional test-result check fails in case of test-failures. This simplifies the distinction between 'hard' failures, like compile-errors and test-failures.
Similar to
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1492
- https://github.com/eclipse-equinox/equinox/pull/677
=> [Build|GH] Unify Maven arguments and replace use of coactions/setup-xvfb

eclipse-platform-parent/pom.xml
They are not used nowadays anyways as the generated api-tools 'report' is used instead by the Jenkins quality-gates.
See also
- https://github.com/eclipse-tycho/tycho/pull/4897
- https://github.com/eclipse-tycho/tycho/pull/4908
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1932
Currently using these options produces warnings in the build logs.
=> [Build] Remove configuration of deprecated tycho-apitools-plugin options

.gitmodules, Jenkinsfile
This simplifies trying out changes in a submodule and their effect on the entire Eclipse-SDK in advance. Instead of always fetching the latest commit from the master branch of the specified remote, fetch the latest commit of the branch specified in `.gitmodules` from each submodule's remote (also specified in `.gitmodules`).
In order to try out a change with the entire Eclipse-SDK, now one just has to update the affected submodules in the `.gitmodules` file to point to the git-repository and the branch providing the change(s).
Before, one either had to push changes to the 'master' branch of the alternative repository providing a change or had to disable the fetch in this Jenkins pipeline and record the change's commit in this aggregator repository along with changing the of the remote in …
=> [Build] Use latest commit of branch specified in .gitmodules file

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
Since we migrated it from CDT, there should be a way for CDT to get rid of this bundle. Adding it to the update site would allow this without platform explicitly referencing it (yet).
=> Add terminal control to update site

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- required for PR https://github.com/eclipse-pde/eclipse.pde/pull/1763
- this bundle contains util classes which are often used in bnd / bndtools which we partly migrate to PDE (for example specifically we need `aQute.libg.glob.Glob`
=> add bnd / biz.aQute.libg

.github/workflows/cleanCode.yml
currently an unlimited number of PRs are created for cleanups. Especially when enabling new cleanups this can lead to a massive amount of PRs created what are hard to manage and probably block the CI.
This now enables a limit of 10 open PRs at a time.
=> Limit number of cleanup PRs

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
- Specify the root features explicitly to avoid aggregating tests.
- Use includedIUPattern to specify which IUs we want to aggregated, i.e., only JDT, PDE, and Platform IUs.
- Use validateNexusPublishingRequirements to ensure we don't miss any required content in the pom.
- Use excludeFeatures to exclude features, binary content, and purely metadata content.
=> Use the latest feature of the CBI p2 Aggregator for SDK4Mvn.aggr

JenkinsJobs/Releng/publishToMaven.jenkinsfile
- There is no need to filter out wanted content because the aggregator only aggregates what we want to publish.
- There is no need to enrich the poms because the aggregator creates poms the meet the nexus publishing requirements and tests that the poms do actually conform.
- There is no need to create javadoc stubs because the aggregator generates one (for every artifact with a corresponding `sources.jar`.
- There is no need to recompute checksums because nothing is modified.
=> Simplify publishToMaven.jenkinsfile

eclipse.platform.releng/features/org.eclipse.platform-feature/pom.xml
- Reorder the excluded plugins alphabetically.
=> Exclude source generation for all linux file system fragments

.github/workflows/mavenBuild.yml
As currently some P2 tests fail and the executing shell might be the cause.
Follow-up on:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2998
=> [Build] Run mavenBuild-workflow with CMD shell on Windows

eclipse.platform.releng/features/org.eclipse.sdk.tests/feature.xml
Part of:
- https://github.com/eclipse-platform/eclipse.platform/pull/1865
=> Remove removed o.e.jsch.tests plugin from sdk.tests feature

eclipse-platform-parent/pom.xml
Fixes https://github.com/eclipse-platform/eclipse.platform/issues/1868
=> Enables the unnecessary whitespace clean-up

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
Update common-io to 2.19.0, due to CVE-2024-47554
=> Backport: Common-io to 2.19.0

oomph/Platform.setup
The launch configuration is maintained directly in the website's git-repository since:
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/348
=> Remove creation of HTTPServer launch config from website Oomph setup

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- The biz.aQute.bnd updates are from the upgrade button reordering alphabetically.
- Update to Orbit milestone, though no content changes that affect the Platform.
=> Update ECF to 3.16.1

JenkinsJobs/Builds/FOLDER.groovy, JenkinsJobs/JobDSL.json
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3075
=> Create new test jobs for 4.37

.github/workflows/checkVersions.yml
This ensures that the workflow for automated version increments always operates on the latest content from the I-builds repository and discards cached data.
At least that's my hope and that worked locally for me. Let's see if it also helps in the CI.
=> [Build] Update snapshots in Version-Increment workflow

JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile
Use the actual email of the `eclipse-releng-bot` as recorded in the EF-API (https://api.eclipse.org/bots) and that is also associated with it's Github account.
Fixes
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6227
=> [Build] Fix mail of Eclipse Releng Bot

cje-production/buildproperties.txt, cje-production/scripts/checkComposites/checkComposites.sh
and Update check composites script to verify 4.37 repositories
=> Update Comparator repo to 4.37-I-builds repo

eclipse-platform-parent/pom.xml
Tycho 4.x is EOL now and we should use the next release to identify potential issues with Tycho 5.x so they can be fixed and released at the end of the release cycle.
**This should be merged as soon as master opens.**
=> Use Tycho 5.0.0-SNAPSHOT in the build

eclipse.platform.releng/features/org.eclipse.sdk/feature.xml
- These bundles are only required by the removed source features.
=> Add the isv bundles to org.eclipse.sdk

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
- Remove EMF's features from the category.xml
- Restore source features accidentally committed in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3107.
=> Replace EMF's features with EMF's bundles in the target platform

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/equinoxp2tests.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/resources/label.properties, eclipse.platform.releng.tychoeclipsebuilder/eclipse-junit-tests/src/main/scripts/getPreviousRelease.sh, production/testScripts/configuration/streamSpecific.properties
Fix https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3114
=> Update previous release version to 4.36 GA across build scripts

cje-production/mbscripts/mb500_createRepoReports.sh
Java 17 is not good anymore thus running it failed. As the analyzers product has been fixed to include the JRE itself
=> Fix running p2repo analyzers

cje-production/buildproperties.txt, eclipse-platform-parent/pom.xml
Update R4_36 maintenance branch with release version for 4.36+ changes
Fixes #3072
=> Update R4_36 maintenance branch with release version for 4.36+ changes

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target, eclipse.platform.releng/features/org.eclipse.test-feature/feature.xml
This is required for 
- https://github.com/eclipse-platform/eclipse.platform/pull/1762
currently it contains the cdt-main, but probably should reference the M2 repo (where relevant API was added) or a future CDT release.
Even though the bundle is **named cdt** it actually depends on nothing than JNA, therefore it can be used without really depend on CDT releases like any other API bundle (we just can't depend on new API if such would be ever added).
In a product one then would need to include the terminal feature (that includes the API and native fragments) to actually use the terminal console feature of platform.
FYI @merks @jonahgraham @akurtakov @stbischof
=> Add CDT core native API bundle for compilation

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
org.eclipse.tm.terminal.view.core is currently not meant to be referenced in any feature but needs to be consumable e.g. by CDT. To do so we need to have it part of the update-site.
=> Add org.eclipse.tm.terminal.view.core to be part of the repository

.github/workflows/publishVersionCheckResults.yml
It it's a constant source of confusion that the commit with version increments is not pushed to the PR, in case edits by maintainers are disabled or the PR is created from an organization repository (which makes edits in general impossible).
This now adds a warning for that case to at least explain contributors the situation.
FYI @HeikoKlare and @fedejeanne, as you or your colleagues have encountered this problems regularly in the past.
=> Warn if workflow for automated version increments cannot modify PR

eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/templateFiles/index.template.php
Update downloads index template to new acknowledgements link schema and all other old links to the eclipse website.
Relates to
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/361
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/365
=> Update links to Eclipse website in downloads index template

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
API stability for JUnit is not guaranteed by Eclipse project thus it shouldn't be included in reports like
https://download.eclipse.org/eclipse/downloads/drops4/I20250617-1800/apitools/deprecation/apideprecation.html
=> Silence deprecation warnings for junit jars

.github/workflows/publishVersionCheckResults.yml
and skip the comment creation step on the step level when no version increment is needed.
As suggested in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3136#issuecomment-2982556906, this enhances the warning message if a required version increment could not be applied automatically by the bot, to now look like:
Thanks Christoph for the suggestion. With that I think the warning is definitively visible enough.
=> Improve warning message if automated version increments cannot modify PR

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
- Update org.apache.lucene to 10.2.2.
- Move org.commonmark to be a direct-from-maven dependency.
- Update jsoup to 1.21.1.
=> Update the TP to latest Orbit milestone

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product
All the content should still be there as materialize-products has includeSources=true property set.
=> Do not include source features in SDK

eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr
- Remove the org.eclipse.tm.terminal.control bundle which has been renamed.
=> Include org.eclipse.terminal.feature.feature.group in SDK4Mvn.aggr

eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/pom.xml
* Do not duplicate setting tycho-version to same constant
* Set the Equinox repository name proper.
=> Improve pom files

JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/Releng/FOLDER.groovy
to fix addition for Y-builds.
Also unify the new display name of 'Modify P2 Composite Repository' job.
Follow-up on
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3165
=> [I/Y-build] Generalize addition of new builds to composite repository

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
Source bundles are handled just fine by Tycho and PDE so this is useless artifact.
=> Do not include tips source feature

JenkinsJobs/Releng/publishToMaven.jenkinsfile
and only send mails on failures (not on aborted builds). Also keep only the build artifacts of the two latest builds.
=> [RelEng] Migrate to Maven-Daemon tool provided by RelEng-Jenkins

JenkinsJobs/Releng/deployToMaven.jenkinsfile
This simplifies distinguishing deployments in case more than one was done recently.
CC @elsazac this is what I suggest in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6130#note_4565661
Future deployments will have names similar to
- `PLATFORM_R-4.36-202505281830`
- `PDE_R-4.36-202505281830`
- `JDT_R-4.36-202505281830`
and the second 'tag' part must match the id of the repo that was passed to the Maven deploy job.
=> [RelEng] Include release in name of deployment to Maven Central Portal

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
Sources will be auto published without the use of deprecated (at least by tycho) source feature usage.
=> Publish o.e.sdk.examplese not source

eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/pom.xml
- This is in preparation for discontinuing source features (and source bundles) from the Equinox and p2 SDK features.
=> Include all sources in equinox-sdk, i.e., o.e.equinox.sdk.product

.github/workflows/cleanCode.yml
The defect was discovered during attempt to apply this workflow to Mylyn. 
It was not possible to reach it earlier, since token for Mylyn was not available
=> `clean-bundles` should consider configured branch

JenkinsJobs/Releng/promoteBuild.jenkinsfile, cje-production/promotion/promoteSites.sh, eclipse-platform-parent/pom.xml, eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/pom.xml
Since 4.28 respectively 2023-06 the property 'p2.mirrorsURL' is not added to release repositories anymore, which effectively disables the use of mirrors.
This happened accidentally because the JDKs installed at the Jenkins agents running the release process became insufficient then.
In order to simplify the release process, the P2-repositories produced by I-builds alredy have their final name set.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3201
This is currently a draft as it has to be tested first.
=> [RelEng] Simplify creation of release P2 repo and restore its mirrorsURL

eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
Define the IU categories for the eclipse artifacts directly in the `category.xml`.
This simplifies the management of those categories and adds them to each build repository. Due to the latter it's not necessary anymore to define the categories in a separated, colocated metadata repository, which is just hosting these categories (which is cumbersome to maintain), e.g. for the 4.36 release:
https://download.eclipse.org/eclipse/updates/4.36/categories/
This is required for (and with more context):
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3215
The current state of this PR is based on and replicates the
<details>
<summary>current `category/content.xml` file content</summary>
```
<?metadataRepository …
```
=> [Build] Define IU categories directly within each build repository

JenkinsJobs/Releng/FOLDER.groovy, JenkinsJobs/Releng/deployToMaven.jenkinsfile, JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile, JenkinsJobs/Releng/promoteBuild.jenkinsfile, JenkinsJobs/Releng/publishPromotedBuild.jenkinsfile, JenkinsJobs/shared/githubAPI.groovy, RELEASE.md
Automate the following tasks that are current executed manually as part of the build promotion and publication jobs
- Trigger Maven-Central staging for release promotions
- Update acknowledgements on each promotion (to have the list up-to-date even for Milestones, etc.)
- Trigger publication immediately for Milestone- and RC-promotions
- Only defer for release promotion
- Send mail on milestone/RC/release publication
- And remove mail template generation from promotion job
- Requires https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6536
Extract code to interact with the GitHub-API into a dedicated Groovy-file, which is shared among all using jobs.
@MohananRahul can you please check if the proposed changes are fine?
@elsazac as per updated documentation, with this the promotion to …
=> [RelEng] Automate more tasks in promotion/publication jobs

eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/META-INF/MANIFEST.MF, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/pom.xml, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.37/faq.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.37/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/4.37/recommended.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/porting/eclipse_4_37_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.jdt.doc.isv/topics_Porting.xml, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.37/faq.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.37/incompatibilities.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/4.37/recommended.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/porting/eclipse_4_37_porting_guide.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/topics_Porting.xml
Migration guide for Eclipse 4.37
=> Migration guide for Eclipse 4.37 from 4.36

JenkinsJobs/Releng/modifyP2CompositeRepository.jenkinsfile
Use the new `modify-composite-repository` Tycho mojo added via (respectively the back-port)
- https://github.com/eclipse-tycho/tycho/pull/5228
This also uses the Maven profile already added in
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3204
=> [RelEng] Use new Tycho mojo to modify a composite P2-repository

JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile
Unify the printing of processed/computed parameters with the other RelEng jobs (which is more compact).
Enhance processing of the `PREVIOUS_RELEASE_CANDIDATE_ID` parameter to
- handle RC2a/b/c... builds
- service versions
=> [RelEng] Simplify input processing in release preparation pipeline

JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile
This was for example done manually in
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3209
and as it's not documented it was forgotten in the initial release preparation and done later.
On the long run it would be great if we could just reference the corresponding variables here, like in other places (but I have to admit that I haven't tested if it's already possible).
=> [RelEng] Update p2-repos in products in release preparation pipeline

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/feature_manifest.html
Replace pipe with comma, since pipe means "or" / choice. But that would mean you can only use one of the elements. Comma means that feature must contain the following elements, which is what we want here
I found an archived site which uses comma: https://archive.eclipse.org/eclipse/downloads/documentation/2.0/html/plugins/org.eclipse.platform.doc.isv/reference/misc/feature_archive.html
=> docs/help: fix DTD for P2 feature.xml

JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile, RELEASE.md, scripts/newReleasePrep.sh
Introduce the possibility to perform custom changes in each sub-module to prepare it for a new development cycle.
Projects that require additional custom changes can implement them in a script named exactly `prepareNextDevCycle.sh`.
=> [RelEng] Support individual updates in release preparation pipeline

oomph/Platform.setup, oomph/PlatformSDKConfiguration.setup
The images repository has been archived. This also removes it form the SDK Oomph setup.
=> Remove images repository from Oomph setup

JenkinsJobs/Builds/FOLDER.groovy, JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile, JenkinsJobs/YBuilds/FOLDER.groovy, RELEASE.md
and simplify the definition and activation of the RC schedule: Update the cron-trigger to it's final value immediately. The extra builds are then triggered when the RC period arrives without activating that schedule manually.
This also simplifies the cron-triggers by just using the complement for the RC schedule (at least for I-builds) and by continuing the RC schedule for the sign-off Thursday. Nowadays we don't have to worry too much about extra triggers as an I/Y build is skipped when nothing has changed:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2706,
From a RelEng POV this has the advantage that the RC schedule doesn't have to be activated by an extra config/code-change but is just specified as necessary from the beginning.
FYI @akurtakov, …
=> [RelEng] Update build configuration in release preparation pipeline

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/extension-points/index.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/about_customization.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/api-usage-rules.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/bidi.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/buddy_loading.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/bundle_manifest.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/eclipse-install.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/eclipsestarter.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/feature_archive.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/feature_manifest.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/index.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/launcher.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/launcher_ini.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/message_bundles.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/multi_user_installs.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/naming.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/overview-platform.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/p2_dropins_format.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/platform-scheme-uri.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/plugin_archive.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/plugin_dtd.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/plugin_manifest.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/project_description_file.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/terminology.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/ui_accessibility_tips.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/services/index.html
This change includes:
- Changing the doctype to "html".
- Simplifying the "Content-Type" meta element to only retain the encoding. The remaining attributes match the default settings and can be omitted.
- Removing the obsolete "charset attribute of the "link" element. The encoding is specified via the "Content-Type" header of the linked document.
- Removing the redundant "type" attribute for the "style" element. CSS is the default type and can therefore be omitted.
- Removing the obsolete "Content-Style-Type" meta element. Styles use CSS by default, so there is no need to set it globally for the document.
- Removing the obsolete "Content-Language" meta element. The document language is specified at the root element.
- Converting the obsolete "name" attribute of anchor points to "id" …
=> Migrate "reference" documents to HTML5

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/bundle_security.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/login_extensions.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_actions_touchpoints.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_customizing_metadata.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_director.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_metadata.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_mirror.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_pgp.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/p2_publisher.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/api-usage-rules.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/bidi.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/eclipsestarter.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/feature_archive.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/feature_manifest.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/launcher.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/naming.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/overview-platform.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/plugin_archive.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/plugin_manifest.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/project_description_file.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/reference/misc/runtime-options.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/samples/samples.html, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/whatsNew/platform_isv_whatsnew.html
=> Fix more docs html validation problems

JenkinsJobs/Releng/promoteBuild.jenkinsfile
This allows the release tag and build-update branches to be overwritten if a very late re-spin of the release build happens, i.e. after the release was already promoted (but not yet published).
=> [RelEng] Force push tags and update branches in promotion pipeline

.mvn/extensions.xml, eclipse-platform-parent/pom.xml
This back-ports
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3266
to un-break the build on the maintenance branch as the snapshot repository is gone in the meantime.
=> [Build] Use Tycho 5 release on R4_37_maintenance

JenkinsJobs/Releng/publishPromotedBuild.jenkinsfile
For releases this warning doesn't seem suitable for me, does it?
I assume it became a copy-past fact at some point in the past.
=> [RelEng] Remove non-production warning in release announcement mail

JenkinsJobs/Releng/publishPromotedBuild.jenkinsfile
Don't launch Maven to output the interpolated `releaseName` property, but instead read the `releaseYear` and `releaseMonth` properties from the raw (`eclipse-platform-parent/pom.xml`) file.
This avoids problems if at the time of the release (candidate) build a snapshot version was used, e.g. of Tycho, that's not available anymore at the time of the publication (because e.g. that Tycho version was released in the meantime).
=> [RelEng] Make read of releaseName more robust in publication pipeline

JenkinsJobs/AutomatedTests/I_unit_tests.groovy, JenkinsJobs/Builds/FOLDER.groovy, JenkinsJobs/JobDSL.json, JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile, JenkinsJobs/Releng/promoteBuild.jenkinsfile, JenkinsJobs/YBuilds/FOLDER.groovy, JenkinsJobs/YBuilds/Y_unit_tests.groovy, JenkinsJobs/shared/utilities.groovy, eclipse.platform.releng/features/org.eclipse.test-feature/feature.xml
when preparing a new dev cycle. This used to be done in the past but was forgotten or just stopped to be done and was then done manually. On the master keep the old and new job until the old job is finally removed when the release is promoted.
=> [RelEng] Move previous release's I-build job to maintenance branch

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf_config.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf_operation.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf_rcp.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf_steps.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf_steps_content.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf_steps_general.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf_steps_rn_migration.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/cnf_troubleshooting.htm
This cleans up the metadata and simplifies anchors.
Contributes to
=> Migrate "Common Navigator Framework" Guides to HTML5

JenkinsJobs/AutomatedTests/I_unit_tests.groovy, JenkinsJobs/Builds/build.jenkinsfile
Java-24 is not the latest version anymore and tests for Java-25 are already set up.
=> [Build] Remove java-24 test configuration after Java-25 release

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/ant.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/ant_contributing_task.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/ant_developing.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/ant_eclipse_tasks.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/ant_expanding_classpath.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/ant_running_buildfiles_programmatically.htm
This cleanup up the metadata and fixes broken links.
Contributes to
=> Migrate "Ant" Guides to HTML5

JenkinsJobs/AutomatedTests/I_unit_tests.groovy, JenkinsJobs/Builds/FOLDER.groovy, JenkinsJobs/JobDSL.json, JenkinsJobs/Releng/FOLDER.groovy, JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile, JenkinsJobs/Releng/promoteBuild.jenkinsfile, JenkinsJobs/YBuilds/FOLDER.groovy, JenkinsJobs/YBuilds/Y_unit_tests.groovy, RELENG.md, cje-production/buildproperties.txt
Split the configuration of built branches per stream and specify it individually per build type (I- and Y-build). Additionally specify individually per build type and stream the cron trigger schedule of the corresponding build.
This allows to configure all managed builds individually.
When preparing a new release, add new and move old stream as before. But preserve the old build's schedule and don't overwrite especially the Y-build schedule with the new streams schedule even if a Java release is imminent (this wrongly happened before).
For Y builds, also add the new stream immediately, but disable it, when a java release is imminent and the the new BETA-Java branch is not created. The old stream's Y-build can then continue until the Java release to feed the P-build and the new build can …
=> [RelEng] Split stream, branch and schedule configuration for I/Y builds

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
The references to CDT p2 site are updated to 12.2.0 release, to include the Terminal feature's native fragment for Linux riscv64.
A separate PR for the platform module is eclipse-platform/eclipse.platform#2170
Fixes #3352
=> add riscv64 native fragment for Terminal feature.

eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_FilteredItemsSelectionDialog.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_FilteredItemsSelectionDialog_example.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_FilteredItemsSelectionDialog_example_advanced.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_applications.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_settings.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_standard.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_wizards.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_wizards_exportWizards.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_wizards_extensions.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_wizards_importWizards.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_wizards_multipage.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_wizards_newWizards.htm, eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/guide/dialogs_wizards_wizarddialogs.htm
=> Convert "Dialog" pages to HTML5

cje-production/dockerfiles/debian/swtgtk3nativebuild/Dockerfile
This PR is supplemental to https://github.com/eclipse-equinox/equinox/pull/1056.
Fixes https://github.com/eclipse-equinox/equinox/issues/1037.
=> add gcc-aarch64-linux-gnu to swtgtk3nativebuild to enable cross-compilation

.github/workflows/htmlvalidator.yml
Taken from
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3342
=> Run htmlvalidator on *.htm files too

.github/workflows/mavenBuild.yml
Since it is the next LTS release and JDK 25 reached General Availability on 16 September 2025 we should make is available so bundles can use it to test compatibility and new features.
=> Make Java 25 available in github actions

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
Deprecations in it are outside of project control so shouldn't be reported. (https://download.eclipse.org/eclipse/downloads/drops4/I20251002-1800/apitools/deprecation/apideprecation.html )
=> Exclude junit-platform-launcher from analyzed bundles

JenkinsJobs/Builds/build.jenkinsfile
The p2-repository is available on the storage/download server just like it's archived.
=> [Build] Keep the artifacts of less build and skip archiving the p2-repo

JenkinsJobs/Releng/collectTestResults.jenkinsfile
Check if results for other test configurations have been published yet and if the corresponding directory already exists on the storage server.
Additionally use the `eclipse-platform` instead of the `eclipse-SDK` product. The former is smaller, but sufficient for the executed tasks.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3386
=> [Build] Fix collection of the first test results

JenkinsJobs/Releng/collectTestResults.jenkinsfile
Delete the test results of previous runs of the same test configurations for the same build, i.e. if a test was run again.
=> [Build] Further refine test result collection to consider reruns

eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target
⚠️ To be merged after https://github.com/eclipse-platform/eclipse.platform.swt/pull/2597 as SWT still depends on JSVG 1.x until that PR is processed.
=> Remove com.github.weisj.jsvg version 1.7.2 from target platform

eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt
Third party dependencies are beyond project's control so deprecations in them shouldn't be reported.
https://download.eclipse.org/eclipse/downloads/drops4/I20251006-1800/apitools/deprecation/apideprecation.html
=> Exclude asm commons from deprecations report

JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/YBuilds/Y_unit_tests.groovy, JenkinsJobs/seedJob.jenkinsfile, RELENG.md
since P-builds are now managed in the JDT JIPP.
If applied the build-tools have to be adjusted too:
- https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/blob/c5f7ecf1951d44311e24ce7bd6b505189aabb4da/bundles/org.eclipse.build.tools/src/org/eclipse/releng/generators/TestResultsGenerator.java#L812
@stephan-herrmann, @jarthana and @mpalat is this fine for you?
I don't know if you reference these jobs directly in Jenkins. If yes, you would have to adjust some URLs
=> [Build] Remove P-build reference from Y-Builds Jenkins folder

JenkinsJobs/AutomatedTests/I_unit_tests.groovy, JenkinsJobs/Builds/build.jenkinsfile, JenkinsJobs/Releng/prepareNextDevCycle.jenkinsfile, JenkinsJobs/YBuilds/Y_unit_tests.groovy, JenkinsJobs/buildConfigurations.json, RELENG.md, cje-production/mbscripts/mb010_createEnvfiles.sh
The buildConfigurations.json becomes the central and only source for configurations of all I/Y-builds and their associated tests. It's read by the seed-job to create the corresponding Jenkins jobs and during I/Y-builds executions.
This avoids a definition of test configurations split over multiple files and avoids continuous changes in the build pipeline file due to regular version, Java or infrastructure updates.
=> [I/Y-Build] Unify build configurations into buildConfigurations.json
